// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch: the fragments in ./de/, composed in the order of ./en.ts.
// Rewritten on every run; the values live in the fragments (see ./de.lock.json).
import type { LocaleTree } from './types';
import { common } from './de/common';
import { planets } from './de/planets';
import { signs } from './de/signs';
import { settings } from './de/settings';
import { timeline } from './de/timeline';
import { topNav } from './de/topNav';
import { chartForm } from './de/chartForm';
import { chartInfoPanel } from './de/chartInfoPanel';
import { chartManager } from './de/chartManager';
import { chartSwitcher } from './de/chartSwitcher';
import { chartWheel } from './de/chartWheel';
import { coordReadout } from './de/coordReadout';
import { creditsModal } from './de/creditsModal';
import { eclipseHud } from './de/eclipseHud';
import { expandedSidebar } from './de/expandedSidebar';
import { importChartModal } from './de/importChartModal';
import { lineMeanings } from './de/lineMeanings';
import { map } from './de/map';
import { missions } from './de/missions';
import { profile } from './de/profile';
import { placeSearch } from './de/placeSearch';
import { teleportHud } from './de/teleportHud';
import { localSpaceHud } from './de/localSpaceHud';
import { aspectLinesHud } from './de/aspectLinesHud';
import { autoFlip } from './de/autoFlip';
import { skyTimes } from './de/skyTimes';
import { captureHud } from './de/captureHud';
import { synastryHud } from './de/synastryHud';
import { wheel } from './de/wheel';
import { minorBodies } from './de/minorBodies';
import { translateOffer } from './de/translateOffer';
import { bindingLanguage } from './de/bindingLanguage';

export default {
  common,
  planets,
  signs,
  settings,
  timeline,
  topNav,
  chartForm,
  chartInfoPanel,
  chartManager,
  chartSwitcher,
  chartWheel,
  coordReadout,
  creditsModal,
  eclipseHud,
  expandedSidebar,
  importChartModal,
  lineMeanings,
  map,
  missions,
  profile,
  placeSearch,
  teleportHud,
  localSpaceHud,
  aspectLinesHud,
  autoFlip,
  skyTimes,
  captureHud,
  synastryHud,
  wheel,
  minorBodies,
  translateOffer,
  bindingLanguage,
} satisfies LocaleTree;
