// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español: the fragments in ./es/, composed in the order of ./en.ts.
// Rewritten on every run; the values live in the fragments (see ./es.lock.json).
import type { LocaleTree } from './types';
import { common } from './es/common';
import { planets } from './es/planets';
import { signs } from './es/signs';
import { settings } from './es/settings';
import { timeline } from './es/timeline';
import { topNav } from './es/topNav';
import { chartForm } from './es/chartForm';
import { chartInfoPanel } from './es/chartInfoPanel';
import { chartManager } from './es/chartManager';
import { chartSwitcher } from './es/chartSwitcher';
import { chartWheel } from './es/chartWheel';
import { coordReadout } from './es/coordReadout';
import { creditsModal } from './es/creditsModal';
import { eclipseHud } from './es/eclipseHud';
import { expandedSidebar } from './es/expandedSidebar';
import { importChartModal } from './es/importChartModal';
import { lineMeanings } from './es/lineMeanings';
import { map } from './es/map';
import { missions } from './es/missions';
import { profile } from './es/profile';
import { placeSearch } from './es/placeSearch';
import { teleportHud } from './es/teleportHud';
import { localSpaceHud } from './es/localSpaceHud';
import { aspectLinesHud } from './es/aspectLinesHud';
import { autoFlip } from './es/autoFlip';
import { skyTimes } from './es/skyTimes';
import { captureHud } from './es/captureHud';
import { synastryHud } from './es/synastryHud';
import { wheel } from './es/wheel';
import { minorBodies } from './es/minorBodies';
import { translateOffer } from './es/translateOffer';
import { bindingLanguage } from './es/bindingLanguage';

export default {
  common,
  planets,
  signs,
  settings,
  timeline,
  topNav,
  chartForm,
  chartInfoPanel,
  chartManager,
  chartSwitcher,
  chartWheel,
  coordReadout,
  creditsModal,
  eclipseHud,
  expandedSidebar,
  importChartModal,
  lineMeanings,
  map,
  missions,
  profile,
  placeSearch,
  teleportHud,
  localSpaceHud,
  aspectLinesHud,
  autoFlip,
  skyTimes,
  captureHud,
  synastryHud,
  wheel,
  minorBodies,
  translateOffer,
  bindingLanguage,
} satisfies LocaleTree;
