// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — do not edit by hand. Lists the shipped core catalogs.
import type { LocaleTree, ShippedLocale } from './types';

export const coreLocaleLoaders: Partial<Record<ShippedLocale, () => Promise<{ default: LocaleTree }>>> = {
  de: () => import('./de'),
  es: () => import('./es'),
  pt: () => import('./pt'),
  ru: () => import('./ru'),
  tr: () => import('./tr'),
};
