// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil): the fragments in ./pt/, composed in the order of ./en.ts.
// Rewritten on every run; the values live in the fragments (see ./pt.lock.json).
import type { LocaleTree } from './types';
import { common } from './pt/common';
import { planets } from './pt/planets';
import { signs } from './pt/signs';
import { settings } from './pt/settings';
import { timeline } from './pt/timeline';
import { topNav } from './pt/topNav';
import { chartForm } from './pt/chartForm';
import { chartInfoPanel } from './pt/chartInfoPanel';
import { chartManager } from './pt/chartManager';
import { chartSwitcher } from './pt/chartSwitcher';
import { chartWheel } from './pt/chartWheel';
import { coordReadout } from './pt/coordReadout';
import { creditsModal } from './pt/creditsModal';
import { eclipseHud } from './pt/eclipseHud';
import { expandedSidebar } from './pt/expandedSidebar';
import { importChartModal } from './pt/importChartModal';
import { lineMeanings } from './pt/lineMeanings';
import { map } from './pt/map';
import { missions } from './pt/missions';
import { profile } from './pt/profile';
import { placeSearch } from './pt/placeSearch';
import { teleportHud } from './pt/teleportHud';
import { localSpaceHud } from './pt/localSpaceHud';
import { aspectLinesHud } from './pt/aspectLinesHud';
import { autoFlip } from './pt/autoFlip';
import { skyTimes } from './pt/skyTimes';
import { captureHud } from './pt/captureHud';
import { synastryHud } from './pt/synastryHud';
import { wheel } from './pt/wheel';
import { minorBodies } from './pt/minorBodies';
import { translateOffer } from './pt/translateOffer';
import { bindingLanguage } from './pt/bindingLanguage';

export default {
  common,
  planets,
  signs,
  settings,
  timeline,
  topNav,
  chartForm,
  chartInfoPanel,
  chartManager,
  chartSwitcher,
  chartWheel,
  coordReadout,
  creditsModal,
  eclipseHud,
  expandedSidebar,
  importChartModal,
  lineMeanings,
  map,
  missions,
  profile,
  placeSearch,
  teleportHud,
  localSpaceHud,
  aspectLinesHud,
  autoFlip,
  skyTimes,
  captureHud,
  synastryHud,
  wheel,
  minorBodies,
  translateOffer,
  bindingLanguage,
} satisfies LocaleTree;
