// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский: the fragments in ./ru/, composed in the order of ./en.ts.
// Rewritten on every run; the values live in the fragments (see ./ru.lock.json).
import type { LocaleTree } from './types';
import { common } from './ru/common';
import { planets } from './ru/planets';
import { signs } from './ru/signs';
import { settings } from './ru/settings';
import { timeline } from './ru/timeline';
import { topNav } from './ru/topNav';
import { chartForm } from './ru/chartForm';
import { chartInfoPanel } from './ru/chartInfoPanel';
import { chartManager } from './ru/chartManager';
import { chartSwitcher } from './ru/chartSwitcher';
import { chartWheel } from './ru/chartWheel';
import { coordReadout } from './ru/coordReadout';
import { creditsModal } from './ru/creditsModal';
import { eclipseHud } from './ru/eclipseHud';
import { expandedSidebar } from './ru/expandedSidebar';
import { importChartModal } from './ru/importChartModal';
import { lineMeanings } from './ru/lineMeanings';
import { map } from './ru/map';
import { missions } from './ru/missions';
import { profile } from './ru/profile';
import { placeSearch } from './ru/placeSearch';
import { teleportHud } from './ru/teleportHud';
import { localSpaceHud } from './ru/localSpaceHud';
import { aspectLinesHud } from './ru/aspectLinesHud';
import { autoFlip } from './ru/autoFlip';
import { skyTimes } from './ru/skyTimes';
import { captureHud } from './ru/captureHud';
import { synastryHud } from './ru/synastryHud';
import { wheel } from './ru/wheel';
import { minorBodies } from './ru/minorBodies';
import { translateOffer } from './ru/translateOffer';
import { bindingLanguage } from './ru/bindingLanguage';

export default {
  common,
  planets,
  signs,
  settings,
  timeline,
  topNav,
  chartForm,
  chartInfoPanel,
  chartManager,
  chartSwitcher,
  chartWheel,
  coordReadout,
  creditsModal,
  eclipseHud,
  expandedSidebar,
  importChartModal,
  lineMeanings,
  map,
  missions,
  profile,
  placeSearch,
  teleportHud,
  localSpaceHud,
  aspectLinesHud,
  autoFlip,
  skyTimes,
  captureHud,
  synastryHud,
  wheel,
  minorBodies,
  translateOffer,
  bindingLanguage,
} satisfies LocaleTree;
