// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe: the fragments in ./tr/, composed in the order of ./en.ts.
// Rewritten on every run; the values live in the fragments (see ./tr.lock.json).
import type { LocaleTree } from './types';
import { common } from './tr/common';
import { planets } from './tr/planets';
import { signs } from './tr/signs';
import { settings } from './tr/settings';
import { timeline } from './tr/timeline';
import { topNav } from './tr/topNav';
import { chartForm } from './tr/chartForm';
import { chartInfoPanel } from './tr/chartInfoPanel';
import { chartManager } from './tr/chartManager';
import { chartSwitcher } from './tr/chartSwitcher';
import { chartWheel } from './tr/chartWheel';
import { coordReadout } from './tr/coordReadout';
import { creditsModal } from './tr/creditsModal';
import { eclipseHud } from './tr/eclipseHud';
import { expandedSidebar } from './tr/expandedSidebar';
import { importChartModal } from './tr/importChartModal';
import { lineMeanings } from './tr/lineMeanings';
import { map } from './tr/map';
import { missions } from './tr/missions';
import { profile } from './tr/profile';
import { placeSearch } from './tr/placeSearch';
import { teleportHud } from './tr/teleportHud';
import { localSpaceHud } from './tr/localSpaceHud';
import { aspectLinesHud } from './tr/aspectLinesHud';
import { autoFlip } from './tr/autoFlip';
import { skyTimes } from './tr/skyTimes';
import { captureHud } from './tr/captureHud';
import { synastryHud } from './tr/synastryHud';
import { wheel } from './tr/wheel';
import { minorBodies } from './tr/minorBodies';
import { translateOffer } from './tr/translateOffer';
import { bindingLanguage } from './tr/bindingLanguage';

export default {
  common,
  planets,
  signs,
  settings,
  timeline,
  topNav,
  chartForm,
  chartInfoPanel,
  chartManager,
  chartSwitcher,
  chartWheel,
  coordReadout,
  creditsModal,
  eclipseHud,
  expandedSidebar,
  importChartModal,
  lineMeanings,
  map,
  missions,
  profile,
  placeSearch,
  teleportHud,
  localSpaceHud,
  aspectLinesHud,
  autoFlip,
  skyTimes,
  captureHud,
  synastryHud,
  wheel,
  minorBodies,
  translateOffer,
  bindingLanguage,
} satisfies LocaleTree;
