// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/aspectLinesHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const aspectLinesHud = {
  title: 'Aspectos',
  closeAria: 'Cerrar Aspectos',
  closeHint: 'Cierra esta ventana. Las líneas siguen activas: desactívalas desde Configuración ▸ Avanzado ▸ Líneas.',
  filters: {
    label: 'Filtros',
  },
  harmonious: {
    title: 'Armónicos',
    hint: 'Líneas de sextil y de trígono. Una sola familia por geometría: cada línea se lee como un sextil desde un extremo de su eje y como un trígono desde el otro.',
  },
  challenging: {
    title: 'Desafiantes',
    hint: 'Líneas de cuadratura: una cuadratura a un extremo de un eje es una cuadratura al otro, así que esta familia va aparte.',
  },
  mcAxis: {
    title: 'Eje del Medio Cielo',
    hint: 'Líneas en aspecto al MC (cada una también se puede leer desde el IC).',
  },
  ascAxis: {
    title: 'Eje del horizonte',
    hint: 'Líneas en aspecto al Ascendente (cada una también se puede leer desde el Descendente).',
  },
  orbs: {
    label: 'Orbes de aspecto',
    infoTitle: 'Orbes de aspecto',
    infoHint: 'Distancia máxima a la exactitud (en grados) en la rueda de la carta y en las listas de aspectos. Las líneas de aspecto del mapa marcan el ángulo exacto y no usan orbe.',
  },
} as const;
