// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/autoFlip.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const autoFlip = {
  suppress: 'No volver a mostrar',
  ok: 'Entendido',
  'overlay-frame-held': {
    title: 'Marco de la capa retenido en Ángulos de la revolución',
    body: 'Una carta de revolución es un momento propio, con sus propios ángulos, y el mapa se dibuja ahora respecto a ellos y no a los natales. El marco anterior queda en pausa, no se borra: vuelve al salir de la revolución, o de inmediato con la ✕ del chip.',
  },
  'line-system-held': {
    title: 'Geodésico está en pausa',
    body: 'El sistema de líneas Geodésico proyecta el zodiaco tropical sobre las longitudes de la Tierra, así que no existe una versión sideral que dibujar. Tu elección queda en pausa, no se borra: pon de nuevo el zodiaco en Tropical y regresará.',
  },
  'line-projection': {
    title: 'Estas líneas se dibujan In Mundo',
    body: 'Todo programa tiene que decidir dónde «está» un cuerpo antes de poder dibujar su línea. In Mundo lo sitúa donde se encuentra en el cielo, latitud incluida. In Zodiaco primero aplana esa latitud sobre la eclíptica.',
  },
  'theme-held': {
    title: 'Tu tema está en pausa',
    body: 'El tema que elegiste no está disponible ahora mismo, así que la aplicación se muestra con el que usabas antes. No se borra nada: regresará tal como lo dejaste en cuanto vuelva a estar disponible.',
  },
  'theme-edits-held': {
    title: 'Tu propia versión está en pausa',
    body: 'Tu propia versión de este tema no está disponible ahora mismo, así que en su lugar se muestra su versión estándar. No se borra nada: la tuya regresará tal como la dejaste en cuanto vuelva a estar disponible.',
  },
  'language-detected': {
    title: 'Ahora en el idioma de tu navegador',
    body: 'AstroLina ya tiene una traducción al idioma que pide tu navegador, y se abre en ella. Para volver al inglés o elegir otro idioma, ve a {route}.',
  },
  'language-held': {
    title: 'El idioma que elegiste está en pausa',
    body: 'El idioma que elegiste se traduce en este dispositivo, lo que ahora mismo no es posible aquí, así que la aplicación se muestra en su idioma habitual. Tu elección se conserva, no se borra. Para elegir otro idioma, ve a {route}.',
  },
} as const;
