// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/captureHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const captureHud = {
  title: 'Captura',
  closeAria: 'Cerrar Captura',
  closeHint: 'Cierra la herramienta Captura.',
  subject: {
    label: 'Captura',
    map: 'Mapa',
    mapHint: 'Exporta el mapa encuadrado: tus líneas sobre el mundo, con la carta como panel opcional al lado.',
    chart: 'Carta',
    chartHint: 'Exporta solo la carta: la rueda (o las posiciones) ocupa todo el encuadre, dibujada como en la barra lateral, con aspectos, anillo de la capa y todo. Sin mapa, mismo pie de imagen.',
  },
  aspect: {
    label: 'Encuadre',
    square: '1:1',
    squareHint: 'Encuadre cuadrado (1:1): ideal para publicaciones y avatares.',
    portrait: '4:5',
    portraitHint: 'Encuadre vertical (4:5): el formato alto para los feeds del teléfono.',
    landscape: '16:9',
    landscapeHint: 'Encuadre horizontal (16:9): panorámico, para diapositivas y encabezados.',
  },
  transparent: {
    title: 'Transparente (Espacio local)',
    hint: 'Un solo interruptor para una exportación limpia del espacio local: oculta las flechas de las líneas, rotula las líneas como el resto de la carta (las etiquetas se pegan a los bordes del encuadre, sin grados de rumbo) y deja en blanco el mapa base para que la exportación conserve un fondo transparente, lista para superponer a un plano de planta o a tu propio fondo. Todo vuelve cuando se cierra Captura o Espacio local.',
    needLs: 'Activa primero Espacio local (Ver ▸ Espacio local): esta exportación transparente y limpia se basa en la brújula y las líneas del espacio local.',
  },
  lsLabels: {
    name: {
      title: 'Rotular nombre',
      hint: 'Escribe el nombre de cada planeta tras su glifo en la etiqueta del espacio local (p. ej., «♂ Marte»).',
    },
    degrees: {
      title: 'Grados',
      hint: 'Escribe el rumbo de cada línea del espacio local a lo largo de la línea, justo por dentro de su etiqueta, hacia el centro de la brújula.',
    },
  },
  view: {
    none: 'Ninguno',
    noneHint: 'Sin detalles de la carta en el encuadre: solo el mapa, el marcador, las etiquetas de los bordes y el pie de imagen.',
    wheel: 'Rueda',
    wheelHint: 'Muestra la carta como rueda en el encuadre, la misma de la barra lateral. Planetas / Ángulos la completan; Balance agrega debajo la cuadrícula elemento·modalidad.',
    list: 'Lista',
    listHint: 'Muestra la carta como una lista de posiciones de planetas / ángulos (y el recuento elemento·modalidad), las mismas filas de la barra lateral.',
    phoneTitle: 'No disponible en teléfonos',
    phoneHint: 'Un encuadre del tamaño de un teléfono es demasiado pequeño para mostrar con claridad la rueda o la lista junto al mapa, así que aquí los detalles quedan desactivados. Para exportar la propia carta, cambia Captura a Carta: entonces la rueda llena el encuadre y se lee bien a este tamaño.',
    tooSmallHint: 'Este encuadre es demasiado pequeño para mostrar la rueda junto al mapa: se dibujaría con el borde cortado. Elige un encuadre más ancho (16:9 es el que más espacio tiene), agranda la ventana, desactiva Balance para devolverle espacio a la rueda o cambia Captura a Carta para exportar solo la rueda.',
    tooSmallBody: 'En este encuadre no cabe una rueda legible junto al mapa, así que los detalles están desactivados. Una captura de la carta le da a la rueda todo el encuadre.',
    switchToChart: 'Capturar solo la carta',
    tooSmallCardHint: 'Este encuadre no puede darle a la rueda el espacio que necesita una carta completa: los aspectos y el anillo de la capa piden más ancho del que hay aquí, y un encuadre ancho y bajo casi no le deja altura a la rueda. Elige 1:1 o 4:5, agranda la ventana, desactiva Balance para devolverle espacio a la rueda o, en su lugar, captura las posiciones como Lista.',
    tooSmallCardBody: 'Este encuadre es demasiado pequeño para dibujar la carta completa, así que en su lugar se muestran las posiciones. Una ventana más alta —o un encuadre 1:1 o 4:5— le da a la rueda el espacio que necesita.',
    clippedBody: 'Algunos detalles no caben en este encuadre y quedarían cortados en la exportación. Prueba un encuadre más ancho, una ventana más grande o menos grupos.',
  },
  extras: {
    label: 'Detalles',
    angles: 'Ángulos',
    anglesHint: 'Agrega los ángulos de la carta (AS, MC, DS, IC…) al panel, después de los planetas.',
    balance: 'Balance',
    balanceHint: 'Agrega el balance de elementos + modalidades: qué planetas caen en Fuego/Tierra/Aire/Agua y Cardinal/Fijo/Mutable.',
  },
  caption: {
    label: 'Pie de imagen',
    name: 'Nombre',
    nameHint: 'Muestra el nombre de la carta en el pie de imagen.',
    date: 'Fecha',
    dateHint: 'Muestra la fecha de nacimiento en el pie de imagen.',
    time: 'Hora',
    timeHint: 'Muestra la hora de nacimiento en el pie de imagen.',
    location: 'Lugar',
    locationHint: 'Muestra el lugar en el pie de imagen: el lugar de nacimiento, o tu marcador cuando coloques uno.',
    coordinates: 'Coordenadas',
    coordinatesHint: 'Muestra la latitud y la longitud completas del lugar en el pie de imagen: el lugar de nacimiento, o tu marcador cuando coloques uno.',
    calculations: 'Cálculos',
    calculationsHint: 'Muestra en el pie de imagen los sistemas de cálculo activos (la misma línea que la vista Info) y, mientras haya una dibujada, la capa temporal con su fecha.',
    discreet: 'El Modo discreto está activado, así que el nombre, la fecha de nacimiento y la hora se dejan en blanco aquí y en la imagen exportada. Presiona P para mostrarlos.',
  },
  calcOverlay: {
    transits: 'Tránsitos',
    progressed: 'Prog. secundarias',
    'tertiary-progressed': 'Prog. terciarias',
    'solar-arc': 'Arco solar',
    'primary-directions': 'Direcciones primarias',
    cyclo: 'CCG',
  },
  share: {
    title: 'Compartir',
    hint: 'Abre el menú de compartir de tu dispositivo para guardar o enviar la imagen (teléfonos y equipos de escritorio compatibles).',
    sheetTitle: 'AstroLina Cartografía',
    sheetText: 'AstroLina — astrocartografía web para mentes curiosas',
  },
  download: {
    title: 'Descargar',
    hint: 'Guarda la vista encuadrada como archivo PNG.',
  },
  copy: {
    title: 'Copiar',
    hint: 'Copia la vista encuadrada al portapapeles, lista para pegar.',
    done: 'Copiado',
  },
  link: {
    title: 'Copiar enlace',
    hint: 'Copia un enlace que abre esta carta y esta vista. Los datos de nacimiento viajan en el enlace, así que compártelo solo con personas que puedan verlos.',
    done: 'Enlace copiado',
    warnAria: 'Aviso de privacidad del enlace',
    warnBody: 'NOTA: Este enlace contiene todos los datos de nacimiento de la carta (fecha, hora y lugar).',
    warnSuppress: 'No volver a recordármelo',
    warnConfirm: 'Copiar enlace',
    warnCancel: 'Cancelar',
  },
  busy: 'Generando…',
  failed: 'La exportación falló. Vuelve a intentarlo.',
  failedReason: {
    'no-frame': 'La vista del mapa no estaba lista. Vuelve a abrir Captura e inténtalo una vez más.',
    'no-canvas': 'Este navegador no le dio a la exportación una superficie de dibujo.',
    'taint-basemap': 'Los mosaicos del mapa no permitieron la exportación. La causa habitual es la prevención de rastreo o un bloqueador de contenido: permite este sitio y vuelve a intentarlo.',
    encode: 'La imagen era demasiado grande para codificarla. Prueba una proporción de encuadre más pequeña.',
    overlay: 'No se pudieron dibujar el pie de imagen y las etiquetas, así que no se generó ninguna imagen. Recarga la aplicación y vuelve a intentarlo.',
  },
} as const;
