// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/chartManager.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const chartManager = {
  dialogLabel: 'Cartas',
  title: 'Mis cartas',
  comparisonTitle: 'Sinastría con {name}',
  comparisonLabel: 'Sinastría',
  searchPlaceholder: 'Buscar nombres o lugares…',
  searchLabel: 'Buscar cartas',
  clearSearch: 'Borrar búsqueda',
  filter: {
    label: 'Filtro por etiqueta',
    all: 'Todas',
    starred: 'Estrella',
    space: 'Espacio',
    unknown: 'Desconocida',
    shared: 'Compartida',
  },
  folders: {
    new: 'Nueva carpeta',
    newChild: 'Nueva subcarpeta',
    rename: 'Renombrar carpeta',
    remove: 'Quitar',
    moveTo: 'Mover a',
    unfiled: 'Sin carpeta',
    nameLabel: 'Nombre de carpeta',
    namePlaceholder: 'Nombre de carpeta',
  },
  discreet: {
    hide: 'Activar el Modo discreto',
    show: 'Desactivar el Modo discreto',
  },
  empty: 'Aún no hay cartas guardadas.',
  noMatches: 'Ninguna carta coincide.',
  addQuery: 'Agregar «{name}»',
  editingHeader: 'Editando {name}',
  saveChanges: 'Guardar cambios',
  addChart: 'Agregar carta',
} as const;
