// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/chartSwitcher.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const chartSwitcher = {
  noChart: 'Sin carta seleccionada',
  tip: 'Cambia, edita o agrega una carta',
  tabHint: '{key} cambia a tu carta anterior; presiónala otra vez para recorrer las cinco más recientes.',
  empty: 'Aún no hay cartas guardadas.',
  searchAdd: 'Buscar + Agregar nombre',
} as const;
