// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/chartWheel.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const chartWheel = {
  resizeLabel: 'Cambiar tamaño de rueda',
  shrink: 'Reducir rueda',
  enlarge: 'Ampliar rueda',
  openSidebar: 'Abrir la rueda completa',
  openSidebarHint: 'Una rueda más grande, con aspectos y la tabla de planetas, en la barra lateral.',
  openSidebarLabel: 'Mostrar la barra lateral de la carta',
  placeholder: 'Sin carta seleccionada',
  noChart: 'SIN CARTA (CCG)',
} as const;
