// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/common.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const common = {
  close: 'Cerrar',
  cancel: 'Cancelar',
  edit: 'Editar',
  delete: 'Eliminar',
  keep: 'Conservar',
  locationFallbackOcean: 'Océano',
  tzWarning: '⚠ Zona horaria pre-1970 fuera de EE. UU./UE: verifica el horario de verano en un atlas',
  timeUnknownBanner: 'Hora de nacimiento desconocida',
  provisionalTimeBanner: '⚠ Probando {time}: provisional, sin guardar',
  locked: {
    feature: '{feature} es una función de {tier}.',
    featureAnyTier: '{feature} no está en tu plan.',
  },
  cardinal: {
    north: 'N',
    south: 'S',
    east: 'E',
    west: 'O',
  },
  hud: {
    dragToMove: 'Arrastra para mover',
    dockKey: 'Doble',
    dockHint: 'para acoplar · se ajusta al centro',
    recentreHint: 'para volver a centrar',
    collapse: 'Contraer panel',
    expand: 'Expandir panel',
    collapseHint: 'Muestra u oculta los controles.',
    closeNamed: 'Cerrar {name}',
  },
} as const;
