// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/creditsModal.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const creditsModal = {
  title: 'Créditos y licencias',
  thanks: {
    tip: 'Agradecimientos especiales',
    hint: 'Ver créditos',
    title: 'Agradecimientos especiales',
    leadRole: 'La astróloga detrás de AstroLina',
    leadBody: 'Esta aplicación nació como su práctica, y sigue respondiendo a ella. Los métodos que sigue, las convenciones que respeta y el criterio detrás de cada línea que traza son suyos: explicados con paciencia, y a menudo más de una vez, hasta que el software estuvo a la altura del oficio.',
    othersHeading: 'Gracias también a',
    body: 'Dos profesionales de la astrología dedicaron a este proyecto su tiempo, sus conocimientos y muchísima paciencia: respondieron preguntas, revisaron convenciones y ayudaron a que una herramienta incipiente se afianzara. Sin estas dos personas sería algo menor.',
    role: 'Profesional de la astrología',
  },
  intro: 'AstroLina se basa en datos abiertos y software de código abierto. Los textos completos de las licencias están disponibles en el repositorio del proyecto.',
  notice: {
    lead: 'Estamos empezando y agradecemos tu ayuda.',
    body: 'La astronomía es sólida: Swiss Ephemeris, datos del JPL, contrastados con el servicio Horizons de la NASA con diferencias muy inferiores a un segundo de arco. La aplicación que la rodea es una primera versión, y hace tanto que no pudimos llegar a todos los rincones antes del lanzamiento. Así que, si una línea parece incorrecta, una cifra parece extraña o algo simplemente no hace lo que pediste, avísanos: cada informe lo lee una persona, y queremos que esta sea una herramienta en la que puedas confiar.',
    report: 'Informa de un problema.',
  },
  groups: {
    astrolina: 'AstroLina',
    mapsPlaces: 'Mapas y lugares',
    astronomy: 'Astronomía',
    typeSoftware: 'Tipografía y software',
  },
  notes: {
    astrolina: '© 2026 AstroLina. Software libre y de código abierto bajo la GNU Affero General Public License v3.0.',
    sourceCode: 'Código fuente completo, disponible según la AGPL. Se aceptan contribuciones.',
    openstreetmap: 'Datos del mapa base (también acreditados en el propio mapa).',
    openfreemap: 'Teselas vectoriales, fuentes para etiquetas y sprites gratuitos.',
    mapStyles: 'MapTiler Basic, OSM Bright, Dark Matter, Positron y Fiord Color, algunos adaptados. © MapTiler.com y colaboradores de OpenMapTiles; © Mapbox; © CartoDB.',
    geonames: 'Búsqueda sin conexión de nombres de lugares y consulta de ciudades.',
    photon: 'Búsqueda en línea de lugares y direcciones; datos © colaboradores de OpenStreetMap.',
    swisseph: 'Posiciones planetarias (JPL DE441). © Astrodienst AG, mediante @swisseph/browser.',
    nasaEclipse: 'Catálogos de eclipses solares y lunares (fechas, tipos, serie Saros). Predicciones de eclipses de Fred Espenak y Jean Meeus (NASA/GSFC).',
    jplSbdb: 'Clases orbitales en las que se basan las etiquetas de planetas menores.',
    noto: 'Glifos astrológicos. © 2022 The Noto Project Authors.',
    maplibre: 'Renderizado interactivo del mapa.',
    rtlText: 'Etiquetas del mapa de derecha a izquierda: letras árabes enlazadas, árabe y hebreo en orden de lectura. © 2017 Mapbox.',
    icu: 'El código de conformación tipográfica y de texto bidireccional del complemento de etiquetas de derecha a izquierda. © Unicode, Inc.',
    other: 'Y otras bibliotecas con licencia MIT listadas en el repositorio del proyecto.',
  },
  footer: ' · Los cálculos de astrocartografía y el diseño de la interfaz son propios de AstroLina; las efemérides y los datos de mapas en que se basan se acreditan más arriba.',
} as const;
