// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/eclipseHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const eclipseHud = {
  title: 'Eclipses',
  choose: 'Elige un eclipse',
  prev: 'Eclipse anterior',
  next: 'Eclipse siguiente',
  locate: 'Volar a este eclipse',
  all: 'Todos',
  searchPlaceholder: 'Buscar año, tipo o Saros…',
  noMatches: 'Ningún eclipse coincide.',
  saros: 'Saros {n}',
  barToggle: {
    show: 'Mostrar datos del eclipse',
    hide: 'Ocultar datos del eclipse',
  },
} as const;
