// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/localSpaceHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const localSpaceHud = {
  title: 'Espacio local',
  closeAria: 'Cerrar Espacio local',
  closeHint: 'Desactiva la vista del espacio local.',
  lsOrigin: {
    pin: 'Desde el marcador',
    pinHint: 'Espacio local relocalizado: las líneas parten del marcador activo (el lugar de nacimiento cuando no hay nada fijado).',
    birthplace: 'Lugar de nacimiento',
    birthplaceHint: 'Las líneas siguen ancladas al lugar de nacimiento aunque haya un marcador puesto.',
    home: 'Hogar',
    homeHint: 'Traza los rumbos desde donde vive ahora la persona de esta carta: defínelo o cámbialo aquí mismo. Usa el lugar de nacimiento mientras no haya un hogar definido.',
    homeUnset: 'No hay hogar definido para esta carta: los rumbos parten del lugar de nacimiento hasta que definas uno.',
  },
  hideInbound: {
    title: 'Líneas entrantes',
    hint: 'La continuación entrante de cada línea del espacio local: la mitad discontinua que apunta al antípoda del cuerpo, opuesta a su rumbo saliente (continuo). Desactívala para dejar solo las mitades salientes.',
  },
  hideDegrees: {
    title: 'Grados',
    hint: 'El rumbo en cada etiqueta saliente, en grados y minutos. Desactivado, las etiquetas solo muestran LS y el glifo.',
  },
  hideCompass: {
    title: 'Brújula',
    hint: 'La rueda de brújula del horizonte local que aparece en el origen al acercar el zoom.',
  },
  flyToOrigin: {
    title: 'Volar al origen',
    hint: 'Desciende al horizonte local: lleva la cámara al origen del que parten las líneas.',
  },
} as const;
