// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/map.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const map = {
  ctrl: {
    zoomIn: 'Acercar',
    zoomOut: 'Alejar',
    resetBearing: 'Restablecer rumbo e inclinación',
  },
  pin: {
    natal: 'Lugar natal (clic derecho para quitarlo)',
    custom: 'Lugar fijado (clic derecho para quitarlo)',
    home: 'Hogar: donde reside ahora esta carta (clic derecho para quitar el marcador)',
  },
  home: {
    tip: 'Hogar',
    hint: 'Haz clic para leer la carta aquí',
  },
  flyToZenith: 'Volar al cenit de {prefix}{planet}',
  flyToAspectPoint: 'Volar a donde el grado de {aspect} de {planet} está en el cenit (haz clic de nuevo para volver)',
  flyToMidpoint: 'Volar a donde el punto medio {planetA}/{planetB} está en el cenit (haz clic de nuevo para volver)',
  aspectNames: {
    sextile: 'sextil',
    square: 'cuadratura',
    trine: 'trígono',
  },
  flyToParan: 'Volar a la intersección de este paran (haz clic de nuevo para volver)',
  flyToLocalSpaceOrigin: 'Volar al origen del espacio local (el marcador)',
  ecliptic: 'Eclíptica',
  polarNote: 'Zona polar: pasada la cresta de esta línea, la salida y la puesta intercambian sus lugares.',
  eclipse: {
    central: 'Línea central',
    pathEdge: 'Borde de la trayectoria central',
    isoline: 'Eclipse máximo: {pct}',
    outerLimit: 'Límite de visibilidad — dentro de esta línea se ve algo del eclipse',
    horizon: 'Línea de salida/puesta lunar en {phase}',
    localMax: '{pct} del Sol cubierto aquí, a las {time} (UTC)',
    lunarAllVisible: 'Todo el eclipse es visible desde aquí',
    lunarPartView: 'Parte del eclipse es visible desde aquí ({n} de {total} contactos)',
  },
  eclipseCard: {
    notVisible: 'Eclipse no visible desde aquí',
    utc: 'UTC',
    c1: 'Inicio parcial',
    c2: 'Inicio de totalidad',
    c2Annular: 'Inicio del anillo',
    max: 'Máximo',
    c3: 'Fin de totalidad',
    c3Annular: 'Fin del anillo',
    c4: 'Fin parcial',
    atSunrise: 'a la salida del Sol',
    atSunset: 'a la puesta del Sol',
    maxValue: 'Magnitud {mag} · {obsc} cubierto',
    duration: 'Duración',
    phase: {
      P1: 'Inicio penumbral',
      U1: 'Inicio parcial',
      U2: 'Inicio de totalidad',
      max: 'Máximo',
      U3: 'Fin de totalidad',
      U4: 'Fin parcial',
      P4: 'Fin penumbral',
    },
    belowHorizon: 'Luna bajo el horizonte',
    moonrise: 'Salida lunar',
    moonset: 'Puesta lunar',
  },
  lineCard: {
    distance: '{label} {km} km / {mi} mi',
  },
  zenithTitle: 'Cenit de {planet}',
  zenithSub: 'donde {planet} está justo sobre la cabeza',
  nadirTitle: 'Nadir de {planet}',
  nadirSub: 'donde {planet} está justo bajo los pies',
  geoReadout: {
    place: '{place} GE',
    coords: '{lat} {lng} GE',
    as: 'AS',
    mc: 'MC',
  },
  geoLegend: {
    aria: 'Leyenda del sombreado de zonas',
    isolate: 'Ver solo zonas: {group}',
    clear: 'Ver todas las zonas',
  },
  zoomOutToWide: 'Alejar a una vista amplia',
  zoomOut: 'Alejar',
  webgl: {
    unsupportedTitle: 'Este mapa necesita WebGL',
    unsupportedBody: 'Tu navegador no le está dando a esta página un contexto gráfico WebGL, así que no se puede dibujar el mapa.',
    tipsHeading: 'Algunas cosas que puedes probar:',
    tipAccel: 'Activa la aceleración por hardware en la configuración de tu navegador y luego recarga la página.',
    tipShield: 'Permite WebGL / canvas en este sitio si usas una protección contra el fingerprinting o de privacidad.',
    tipBrowser: 'O abre AstroLina en otro navegador actualizado.',
    lostTitle: 'El mapa perdió su contexto gráfico',
    lostBody: 'Esto puede ocurrir cuando al dispositivo le queda poca memoria gráfica. A menudo se recupera solo; si no, recarga la página.',
    reload: 'Recargar la página',
  },
} as const;
