// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/missions.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const missions = {
  guideTitle: 'Misiones',
  title: 'Guía',
  close: 'Descartar',
  skipTip: 'Saltar esta guía',
  ok: 'Entendido',
  okLocked: 'Termina todas las misiones para continuar',
  dontShowAgain: 'No volver a mostrar',
  prevGuide: 'Guía anterior',
  nextGuide: 'Guía siguiente',
  guidePosition: 'Guía {current} de {total}',
  gesture: {
    double: 'Doble',
    right: 'Botón derecho',
    hold: 'Mantener',
    shift: 'Shift',
    drag: 'Arrastrar',
    click: 'Clic',
    tap: 'Tocar',
    doubleTap: 'Doble toque',
    longPress: 'Toque largo',
    touchDrag: 'Tocar y arrastrar',
    twoFinger: 'Arrastrar con 2 dedos',
    pinch: 'Pellizcar',
    snap: 'Ajustar',
  },
  pill: {
    double: 'Doble {icon} clic',
    right: 'Clic {icon} derecho',
    hold: 'Mantener {icon} y arrastrar',
    shiftDrag: 'Arrastrar {icon} con Shift',
    rightDrag: 'Arrastrar {icon} con botón derecho',
    tapSnap: 'Tocar {icon} Ajustar',
    holdShift: 'Mantener {icon} Shift',
  },
  mapBasics: {
    subtitle: 'Cómo colocar un marcador {pin}',
    createPin: 'para colocar un marcador',
    removePin: 'para quitar un marcador',
    placeNatal: 'para poner el marcador natal',
  },
  measureBasics: {
    subtitle: 'Cómo usar la herramienta {ruler} Medir',
    drawLine: 'y {drag} para dibujar una línea',
    touchDrawLine: 'para dibujar una línea',
    shiftSnap: 'sobre una línea mientras mides para ajustarte a ella: la distancia exacta a esa línea',
    rightCancel: 'para cancelar la herramienta',
    touchSnap: 'y arrastrar sobre una línea para ajustar',
    touchCancel: 'de nuevo la herramienta Medir para salir',
  },
  zoomBasics: {
    subtitle: 'Cómo hacer {zoom} zoom rápido',
    zoomOut: 'en el botón «Alejar»',
    quickZoom: 'para crear un cuadro de zoom',
    perspective: 'para cambiar la perspectiva (solo en la vista de proyección de globo 3D)',
    touchQuickZoom: 'para acercar o alejar',
  },
} as const;
