// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/placeSearch.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const placeSearch = {
  scopeLabel: 'Lugar',
  noMatches: 'Sin coincidencias.',
  failed: 'No se pudo hacer esa búsqueda. Vuelve a intentarlo.',
  scopeAria: 'Ámbito de búsqueda',
  more: 'Mostrar más',
} as const;
