// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/planets.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const planets = {
  Sun: {
    name: 'Sol',
    theme: 'Tu identidad esencial, tu vitalidad y aquello en lo que brillas.',
  },
  Moon: {
    name: 'Luna',
    theme: 'Emociones, instinto y lo que te hace sentir como en casa.',
  },
  Mercury: {
    name: 'Mercurio',
    theme: 'La mente: cómo piensas, aprendes y te comunicas.',
  },
  Venus: {
    name: 'Venus',
    theme: 'Amor, belleza, placer y lo que valoras.',
  },
  Mars: {
    name: 'Marte',
    theme: 'Impulso, valor y cómo te afirmas y actúas.',
  },
  Jupiter: {
    name: 'Júpiter',
    theme: 'Crecimiento, suerte y donde la vida se expande y se siente generosa.',
  },
  Saturn: {
    name: 'Saturno',
    theme: 'Disciplina, límites y las lecciones de la madurez, ganadas a pulso.',
  },
  Uranus: {
    name: 'Urano',
    theme: 'Cambio repentino, libertad y tu chispa de rebeldía.',
  },
  Neptune: {
    name: 'Neptuno',
    theme: 'Sueños, intuición, espiritualidad y la bella ilusión.',
  },
  Pluto: {
    name: 'Plutón',
    theme: 'Poder, intensidad y una profunda transformación y renacimiento.',
  },
  NorthNode: {
    name: 'Nodo N',
    theme: 'Tu frontera de crecimiento: donde la vida te llama a avanzar y la pertenencia te encuentra.',
  },
  SouthNode: {
    name: 'Nodo S',
    theme: 'Terreno conocido: dones heredados, raíces profundas y lo que ya puedes soltar.',
  },
  Lilith: {
    name: 'Lilith',
    tipName: 'Luna Negra Lilith',
    theme: 'Instinto crudo e indómito, y donde te niegas a que te domen.',
  },
  Chiron: {
    name: 'Quirón',
    theme: 'El sanador herido: la sanación a través de tu herida más profunda.',
  },
  Ceres: {
    name: 'Ceres',
    theme: 'Cuidado, nutrición y los ciclos vitales de pérdida y retorno.',
  },
  Pallas: {
    name: 'Palas',
    theme: 'Estrategia, habilidad y resolución lúcida de problemas.',
  },
  Juno: {
    name: 'Juno',
    theme: 'Compromiso, pareja y lo que necesitas para sentir que hay igualdad.',
  },
  Vesta: {
    name: 'Vesta',
    theme: 'Devoción, enfoque y la llama interior que mantienes sagrada.',
  },
  Fortune: {
    name: 'Fortuna',
    theme: 'Facilidad, florecimiento y donde prosperan el cuerpo y la vida mundana.',
  },
} as const;
