// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/profile.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const profile = {
  planTag: {
    new: 'NUEVO',
    adv: 'AVZ',
    tip: 'Modo avanzado',
    hint: 'Muestra funciones más avanzadas, pensadas para astrólogos con experiencia.',
    tipBasic: 'Modo estándar',
    hintBasic: 'Oculta las funciones avanzadas para una vista más simple y estándar.',
  },
} as const;
