// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/settings.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const settings = {
  sections: {
    appearance: 'Apariencia',
    mapFilters: 'Filtros del mapa',
    calculation: 'Cálculo',
    advanced: 'Avanzado',
  },
  headings: {
    theme: 'Tema',
    privacy: 'Privacidad',
    details: 'Detalles',
    projection: 'Proyección',
    language: 'Idioma',
    planets: 'Planetas',
    points: 'Puntos',
    minorBodies: 'Cuerpos menores',
    angles: 'Ángulos',
    lines: 'Líneas',
    lineSystem: 'Sistema de líneas',
    lineProjection: 'Proyección de las líneas',
    geoGrid: 'Cuadrícula geodésica',
    lunarNode: 'Nodo lunar',
    houseSystem: 'Sistema de casas',
    zodiac: 'Zodiaco',
    aspectOrbs: 'Orbes de aspecto',
    primaryRate: 'Clave de dir. primarias',
    display: 'Visualización',
    arc: 'Arco',
    progAngles: 'Ángulos',
    magnitudeSteps: 'Pasos de magnitud',
    fortuneFormula: 'Parte de la Fortuna',
    rulerships: 'Regencias',
  },
  details: {
    roadsRivers: 'Carreteras/Ríos',
    roadsRiversHint: 'Muestra el trazado de carreteras y ríos del mapa base. Ocúltalo para tener un fondo más limpio detrás de las líneas de astrocartografía.',
    placeNames: 'Nombres/Etiquetas',
    placeNamesHint: 'Muestra los nombres de ciudades y países del mapa base. Es independiente de las etiquetas de las líneas ACG, que se mantienen en cualquier caso.',
  },
  shiftTag: 'Shift',
  natal: {
    title: 'Carta natal',
    hint: 'La carta natal de base. Ocúltala y la capa ocupa su lugar: asume las líneas, la rueda y los datos de la carta.',
  },
  languageUnavailable: 'Próximamente.',
  machine: {
    section: 'Traducción automática',
    sectionHint: 'Los idiomas de arriba vienen con AstroLina. Los idiomas de abajo se traducirán automáticamente en este dispositivo.',
    hint: 'Se traduce del inglés en este dispositivo, a medida que usas la aplicación. Algunas expresiones pueden ser imprecisas.',
    downloadHint: 'Se traduce del inglés en este dispositivo. La primera vez, el modelo de traducción se descarga en él.',
    partialHint: 'Parte de la aplicación sigue en inglés. Vuelve a elegir este idioma para terminar de descargar la traducción en este dispositivo.',
    heldDownloadHint: 'Tu elección, en pausa hasta que la traducción vuelva a descargarse en este dispositivo. Elige este idioma para descargarla.',
    heldHint: 'Este dispositivo no puede traducir a este idioma ahora mismo. Tu elección se conserva y volverá cuando sea posible.',
    cacheHint: 'Se muestra con lo que este dispositivo tradujo antes. Aquí ya no puede traducir, así que el texto nuevo queda en inglés.',
    downloading: 'Descargando {language} en este dispositivo… {percent}%',
    translating: 'Traduciendo a {language}…',
    failed: 'No se pudo configurar {language} en este dispositivo.',
    disclosure: 'Traducción automática en este dispositivo. Algunas expresiones pueden ser imprecisas; lo que aún no se ha traducido se muestra en inglés.',
  },
  dock: {
    open: 'Abrir configuración',
    close: 'Cerrar configuración',
  },
  userRate: {
    label: 'Grados por año',
  },
  parans: {
    title: 'Parans',
    hint: 'Latitudes donde dos cuerpos son angulares en el mismo momento: uno sale mientras otro culmina, y así sucesivamente. Los parans de tu carta siguen activos junto a una capa.',
    blockedCyclo: 'No hay un único momento del cielo: la ciclocartografía lee juntos cuerpos progresados y en tránsito. Muestra la Carta natal para recuperar los parans propios de la carta.',
    blockedOverlay: 'Los parans se leen en la carta, y esta capa ocupa su lugar. Muestra la Carta natal para recuperar los parans de la carta.',
  },
  aspectLines: {
    title: 'Líneas de aspecto',
    hint: 'Líneas de un planeta en sextil (⚹), cuadratura (□) o trígono (△) al MC o al Ascendente: cada aspecto dos veces, una por lado. Un trígono al AS es también sextil al DS; pasa el cursor por la línea para ver ambas lecturas. Conjunciones y oposiciones son las líneas de ángulo del planeta, ya en el mapa.',
    openHud: 'Personalizar',
    openHudHint: 'Abre la ventana Aspectos: filtra las líneas del mapa por cualidad y eje, y ajusta todos los orbes de aspecto a la vez.',
  },
  midpointLines: {
    title: 'Líneas de punto medio',
    hint: 'Líneas donde el punto medio de dos cuerpos visibles cae exactamente sobre un ángulo (p. ej., Su/Mo MC). In Mundo usa el punto medio corporal (AR y declinación medias); In Zodiaco, el clásico punto medio en longitud. Reduce el filtro de planetas para que el conjunto siga siendo legible.',
    blockedCyclo: 'Aquí un punto medio promediaría un cuerpo progresado y otro en tránsito en un solo punto: algo incoherente entre dos épocas.',
  },
  zenithNadir: {
    title: 'Cenits/Nadires',
    hint: 'Marca dónde está cada cuerpo en lo alto (cenit: círculo en la línea MC) y bajo los pies (nadir: rombo en la línea IC). Pasa el cursor para identificarlo; haz clic para volar allí.',
  },
  aspectOrbs: {
    hint: 'Distancia máxima a lo exacto (grados) por aspecto en la rueda y las listas de aspectos. Luminares amplía cada orbe con el Sol o la Luna; Paralelos es el orbe de declinación.',
    setDegrees: 'Ajustar grados',
    orbAria: 'Orbe para aspectos de {aspect}, en grados',
    lumLabel: 'Luminares +',
    lumHint: 'Grados de orbe adicionales siempre que interviene el Sol o la Luna.',
    lumAria: 'Orbe adicional cuando interviene un luminar, en grados',
    declinationLabel: 'Paralelos',
    declinationAria: 'Orbe para aspectos de paralelo y contraparalelo, en grados de declinación',
  },
  zodiac: {
    tropical: {
      label: 'Tropical',
      hint: 'Signos anclados a las estaciones (0° Aries = el equinoccio de marzo). La opción occidental por defecto.',
    },
    lahiri: {
      label: 'Sideral · Lahiri',
      hint: 'Signos anclados a las estrellas fijas, según el ayanamsa de Lahiri (el estándar védico, hoy ~24° por detrás del tropical). Cambia la rueda y los datos; las líneas del mapa marcan eventos independientes del zodiaco y no se mueven.',
    },
    'fagan-bradley': {
      label: 'Sideral · Fagan/Bradley',
      hint: 'Signos anclados a las estrellas fijas, según el ayanamsa de Fagan/Bradley (el estándar sideral occidental). Cambia la rueda y los datos; las líneas del mapa no se mueven.',
    },
  },
  natalLines: {
    title: 'Líneas natales',
    hint: 'Las líneas de ángulo de la carta natal en Ascendente, MC, Descendente e IC y, junto a una capa, sus parans. La rueda y los datos siguen; las líneas ocultas no admiten clic.',
  },
  starLines: {
    title: 'Estrellas fijas',
    hint: 'Líneas de ángulo de las estrellas fijas clásicas (Régulo, Espiga, Algol y compañía): líneas punteadas salpicadas de pequeñas estrellas, en un tono común de luz estelar. Se omiten las líneas de salida/puesta de las estrellas circumpolares; allí la lectura tradicional son los parans.',
    bright: 'Estrellas destacadas',
    brightHint: 'Las cuatro estrellas reales y las clásicas más brillantes (18 estrellas).',
    all: 'Lista completa',
    allHint: 'Todo el conjunto de trabajo incluido (40 estrellas). El mapa estará muy cargado.',
  },
  nightShade: {
    title: 'Sombra nocturna',
    hint: 'Sombrea la mitad de la Tierra que está de noche en el momento mostrado.',
  },
  discreet: {
    title: 'Modo discreto',
    hint: 'Oculta nombres, fechas y lugares de nacimiento en toda la pantalla —incluidos el pie de imagen de una captura y la imagen que exporta— para que puedas trabajar con alguien a tu lado. El mapa y sus líneas no cambian, y un documento que te pongas a preparar sigue mostrando los datos reales.',
  },
  orbZones: {
    title: 'Zonas de orbe',
    hint: 'Zonas de influencia sombreadas: una franja de distancia terrestre en torno a cada línea planetaria y cada paran. La influencia decae al alejarse; el borde es convención, no abismo.',
    unitAria: 'Unidad de distancia de la zona de orbe (km o mi)',
    lineAria: 'Zona de orbe de líneas, ancho por lado',
    paranLabel: 'Parans',
    paranAria: 'Orbe de parans, ancho por lado',
  },
  theme: {
    glass: {
      label: 'Cristal',
      hint: 'Paneles plateados esmerilados sobre un mapa luminoso y detallado de tierras crema y mares azul pálido.',
    },
    dark: {
      label: 'Oscuro',
      hint: 'Un mapa de pizarra profunda bajo paneles oscuros, pensado para trasnochar, donde cada línea destaca.',
    },
    vintage: {
      label: 'Tierra',
      hint: 'Un aire cálido de atlas: mares de azul suave y tierras arenosas, enmarcados en paneles de marrón pergamino.',
    },
    customize: 'Personalizar',
    customizeHint: 'Abre el editor de temas: colores, estilos de línea y efectos, desde unas pocas opciones generales hasta cada valor individual.',
    customHeld: 'No disponible por ahora. Mientras tanto, la app se muestra con el tema que usabas antes de este; tu elección se conserva, no se borra.',
    customEditsHeld: 'Tu propia versión de este tema no está disponible por ahora, así que se muestra su versión estándar; la tuya se conserva, no se borra.',
    outlineUnavailable: 'El mapa Contorno solo tiene costas: no tiene carreteras, ríos ni nombres de lugares. Elige otro Mapa en Personalizar para usar esto; tu elección se conserva.',
    lockedNote: 'Aún no disponible para esta cuenta. Presiona para ver qué lo desbloquea.',
    keptNote: 'Puedes quedártelo. Si cambias a otro tema, para volver a este necesitarás lo que muestra la insignia.',
  },
  projection: {
    hint: 'Cómo se dibuja el mundo, no dónde está cada cosa. Ambas vistas sitúan las mismas coordenadas, y toda distancia que muestra la app (la fila de distancia mínima de la ficha de una línea, la medición con clic y arrastre, las zonas de orbe) es una distancia real sobre el terreno medida en la esfera. Aun así, ninguna vista sirve para juzgar la cercanía a ojo: Plano estira la escala hacia los polos y el globo la comprime hacia su borde, así que lee la distancia en lugar del hueco.',
    '2d': {
      label: 'Plano',
      hint: 'Mapa clásico Web-Mercator',
    },
    '3d': {
      label: 'Globo',
      hint: 'Globo 3D giratorio',
    },
  },
  lineSystem: {
    celestial: {
      label: 'Celeste',
      hint: 'Astrocartografía estándar: ángulos situados por el cielo (tiempo sideral)',
    },
    geodetic: {
      label: 'Geodésico',
      hint: 'Mapeo geodésico: el zodiaco proyectado sobre las longitudes de la Tierra (Greenwich = 0° Aries, siempre tropical), independiente de la hora de nacimiento',
    },
  },
  geoGrid: {
    mc: {
      title: 'Meridianos MC',
      hint: 'Doce meridianos, cada 30° al este de Greenwich. En un mapa geodésico, cada uno marca dónde empieza un signo del MC; el signo se indica en la parte superior del mapa.',
    },
    asc: {
      title: 'Curvas del Ascendente',
      hint: 'Donde cada signo empieza a ascender: cada lugar de una curva tiene 0° de ese signo en el Ascendente. Activo por defecto si no hay líneas de la carta; tu elección prevalece.',
    },
    zones: {
      title: 'Sombreado de zonas',
      hint: 'Rellena las doce zonas del MC: elemento como color, modalidad como tono (Cardinal, la más oscura; Mutable, la más clara). La leyenda del mapa aísla un elemento o una modalidad.',
    },
    presentation: {
      title: 'Presentación',
      hint: 'Sube el sombreado de las zonas de tenue a intenso, para mostrárselas a otra persona.',
    },
  },
  coordSystem: {
    mundo: {
      label: 'In Mundo',
      hint: 'Las líneas usan el lugar propio de cada cuerpo en el cielo (AR / dec). Idéntico a In Zodiaco para el Sol, que está en la eclíptica; la mayor diferencia, en Plutón y la Luna.',
    },
    zodiaco: {
      label: 'In Zodiaco',
      hint: 'Los cuerpos se proyectan sobre la eclíptica antes de dibujar las líneas (una opción ACG habitual por defecto).',
    },
  },
  fortuneFormula: {
    hint: 'La Parte de la Fortuna es una Parte calculada de vitalidad y bienestar mundano: un punto en la eclíptica, no un cuerpo en el cielo, así que solo un marco zodiacal puede situarla. Sus líneas en el mapa necesitan la Proyección de las líneas en In Zodiaco (o el sistema de líneas Geodésico). Al relocalizar el marcador del mapa se recalcula en la rueda de la carta para ese lugar, mientras que las líneas del mapa conservan tu Fortuna natal.',
    sect: {
      label: 'Según la secta (día/noche)',
      hint: 'Nacimientos de día: Ascendente + Luna − Sol; de noche se invierte a Ascendente + Sol − Luna. La convención tradicional.',
    },
    ptolemaic: {
      label: 'Ptolemaica (fija)',
      hint: 'Ascendente + Luna − Sol para todas las cartas, de día o de noche. La convención histórica alternativa.',
    },
  },
  rulership: {
    hint: 'Qué tabla de regencias usa la lectura de dignidad esencial de la rueda de la carta. Moderna AGREGA los tres planetas exteriores sin quitar ninguno: Marte conserva Escorpio junto a Plutón, y ambos están en exilio en Tauro, su opuesto. Elegir Tradicional quita las filas de esos tres y nada más.',
    traditional: {
      label: 'Tradicional',
      hint: 'Solo la tabla de los siete planetas: Marte rige Escorpio, Saturno Acuario y Júpiter Piscis. Urano, Neptuno y Plutón no rigen nada, así que no tienen dignidad.',
    },
    modern: {
      label: 'Moderna',
      hint: 'Los mismos siete, más Plutón en Escorpio, Urano en Acuario y Neptuno en Piscis. Esos tres signos tienen dos regentes, y cada fila indica su época.',
    },
  },
  inert: {
    fortuneMundo: 'Una Parte es un punto de la eclíptica sin posición en el cielo, así que In Mundo no tiene dónde situarla. Para ver esta línea, pon la proyección en In Zodiaco (Cálculo).',
    fortuneAdvanced: 'La Parte de la Fortuna es una lectura de Avanzado: activa Avanzado para usarla.',
    geodeticSidereal: 'El sistema de líneas Geodésico lleva el zodiaco TROPICAL a las longitudes de la Tierra: no hay versión sideral. Elige Tropical (Avanzado) para usarlo; tu elección se conserva.',
    geodeticHeld: 'Geodésico está en revisión mientras comprobamos cómo se dibuja: preferimos pausarlo a dibujar un mapa que no podamos respaldar. Tu elección se conserva, no se borra; vuelve pronto.',
    skyHeldWhy: 'No disponible en los mapas geodésicos, que no giran con el cielo.',
    skyHeldFix: 'Cambia el sistema de líneas a Celeste, en Cálculo, para usarlo.',
    skyHeld: 'No disponible en los mapas geodésicos, que no giran con el cielo. Cambia el sistema de líneas a Celeste, en Cálculo, para usarlo.',
    skyHeldAction: 'Abrir Cálculo',
    skyHeldForNow: 'No disponible por ahora en los mapas geodésicos.',
    skyHeldForNowFull: 'No disponible por ahora en los mapas geodésicos. Cambia el sistema de líneas a Celeste, en Cálculo, para usarlo.',
    anglesHeld: 'En los mapas geodésicos, los ángulos de un lugar salen de sus coordenadas, así que no se mueven con el tiempo.',
    paransHeld: 'Los parans no se muestran en los mapas geodésicos.',
    paransHeldFull: 'Los parans no se muestran en los mapas geodésicos. Cambia el sistema de líneas a Celeste, en Cálculo, para usarlo.',
  },
  nodeType: {
    true: {
      label: 'Nodo verdadero',
      hint: 'Nodo verdadero (osculador): sigue la órbita instantánea de la Luna; oscila ±~1,5° en torno al medio y puede ir directo un tiempo (predeterminado).',
    },
    mean: {
      label: 'Nodo medio',
      hint: 'El promedio suavizado a largo plazo; siempre se mueve retrógrado a ritmo constante.',
    },
  },
  houseSystem: {
    placidus: {
      label: 'Placidus',
      hint: 'División temporal por semiarcos (el predeterminado moderno habitual)',
    },
    koch: {
      label: 'Koch',
      hint: 'Semiarco sobre la latitud de nacimiento (GOH)',
    },
    regiomontanus: {
      label: 'Regiomontanus',
      hint: 'Divisiones iguales del ecuador celeste',
    },
    campanus: {
      label: 'Campanus',
      hint: 'Divisiones iguales del primer vertical',
    },
    porphyry: {
      label: 'Porfirio',
      hint: 'Cada cuadrante dividido en tres en longitud eclíptica',
    },
    alcabitus: {
      label: 'Alcabitus',
      hint: 'Semiarco antiguo sobre los arcos diurno / nocturno',
    },
    meridian: {
      label: 'Meridiano',
      hint: 'Arcos iguales de 30° del ecuador desde el MC, proyectados por círculos horarios; la 1.ª cúspide es un Punto Este, no el Ascendente. Bien definido en todas las latitudes.',
    },
    morinus: {
      label: 'Morinus',
      hint: 'Arcos iguales del ecuador proyectados por círculos de los polos de la eclíptica; no usa ni el Ascendente ni el MC, así que funciona sin problemas incluso en latitudes polares.',
    },
    whole: {
      label: 'Signo entero',
      hint: 'Cada casa es un signo entero a partir del signo ascendente',
    },
    equal: {
      label: 'Iguales',
      hint: 'Casas de 30° medidas desde el Ascendente',
    },
  },
  primaryRate: {
    ptolemy: {
      label: 'Ptolomeo (1°/año)',
      hint: 'Un año por grado.',
    },
    naibod: {
      label: 'Naibod (59′08″/año)',
      hint: '0,985647° por año, el movimiento medio del Sol.',
    },
    cardan: {
      label: 'Cardano (59′12″/año)',
      hint: '0,986667° por año.',
    },
    'kepler-ra': {
      label: 'Movimiento solar diario (AR)',
      hint: 'Clave de Kepler: el movimiento diario del Sol natal en ascensión recta × años.',
    },
    'solar-long': {
      label: 'Movimiento solar diario (longitud)',
      hint: 'Movimiento diario del Sol natal en longitud eclíptica × años.',
    },
    'placidus-ra': {
      label: 'Arco solar verdadero (AR)',
      hint: 'Usa como clave la distancia real que ha recorrido el Sol progresado a esta edad, no una tasa anual fija. Como la velocidad del Sol varía durante el año, el arco se acumula de forma desigual: esta clave va algo por delante o por detrás de las opciones de tasa fija según la estación del nacimiento.',
    },
    user: {
      label: 'Clave del usuario',
      hint: 'Ingresa abajo tus propios grados por año.',
    },
    control: {
      tip: 'La clave de las direcciones primarias',
      hint: 'Las direcciones primarias modelan la rotación diaria: los ángulos de la carta avanzan mientras los cuerpos mantienen sus lugares natales en el cielo. La tasa es la clave: cuánto arco se acumula por año de vida. Las escuelas difieren, y la diferencia es real: a lo largo de una vida, Ptolomeo y Naibod se separan más de un año.',
    },
  },
  positioning: {
    'relative-to-natal': {
      label: 'Ángulos natales',
      short: 'Natales',
      tip: 'Los ángulos propios de la carta natal',
      hint: 'Mantiene fijo el marco natal: solo el movimiento secundario propio de los planetas mueve las líneas. Se elimina la rotación diurna. Responde: ¿dónde caería en la Tierra este tránsito sobre Ascendente, MC, Descendente o IC? Las líneas derivan en semanas y meses, al ritmo propio de cada planeta.',
      returnHintSolar: 'Dibuja los planetas de la revolución respecto a los ángulos natales. El Sol de la revolución vuelve a su grado natal y el Sol no tiene latitud eclíptica, así que sus líneas caen exactamente sobre las líneas del Sol natal en cualquiera de las dos proyecciones: el mismo lugar cada año.',
      returnHintLunar: 'Dibuja los planetas de la revolución respecto a los ángulos natales. La Luna de la revolución vuelve a su longitud natal, así que en In Zodiaco sus líneas caen sobre las líneas de la Luna natal; en In Mundo quedan cerca pero no exactamente encima, porque la latitud de la Luna ha cambiado desde el nacimiento.',
    },
    'transit-moment': {
      label: 'Ángulos del tránsito',
      short: 'Tránsito',
      returnLabel: 'Ángulos de la revolución',
      returnShort: 'Revolución',
      tip: 'Los ángulos del propio momento',
      returnTip: 'Los ángulos propios de la carta de la revolución',
      hint: 'Lee el cielo en el propio marco del momento: las líneas llevan el movimiento primario y todo el conjunto barre 15° por hora, una vuelta completa al día. La línea de cada cuerpo marca dónde es realmente angular en ese instante. No interviene la carta natal. Se lee en un instante, no en una estación.',
      returnHint: 'Una carta de revolución es un momento en sí mismo, con sus propios ángulos. El mapa se dibuja respecto a los ángulos de la revolución en lugar de los natales.',
    },
  },
  arcMethod: {
    'sa-long': {
      label: 'Arco solar — en longitud',
      angles: 'Hace avanzar los ángulos la distancia que el Sol progresado ha recorrido hasta el instante propio de esta capa, medida a lo largo de la eclíptica.',
      bodies: 'Hace avanzar cada cuerpo la distancia que el Sol progresado de esta carta ha recorrido realmente, medida a lo largo de la eclíptica. El método clásico.',
    },
    'sa-ra': {
      label: 'Arco solar — en ascensión recta',
      angles: 'Hace avanzar los ángulos la distancia que el Sol progresado ha recorrido hasta el instante propio de esta capa, medida a lo largo del ecuador.',
      bodies: 'Hace avanzar cada cuerpo la distancia que el Sol progresado de esta carta ha recorrido realmente, medida a lo largo del ecuador.',
    },
    'naibod-long': {
      label: 'Naibod, tasa media — en longitud',
      angles: 'Hace avanzar los ángulos a la tasa media del Sol durante el intervalo propio de esta capa, midiendo a lo largo de la eclíptica.',
      bodies: 'Hace avanzar cada cuerpo al ritmo del movimiento anual medio del Sol, medido a lo largo de la eclíptica.',
    },
    'naibod-ra': {
      label: 'Naibod, tasa media — en ascensión recta',
      angles: 'Hace avanzar los ángulos a la tasa media del Sol durante el intervalo propio de esta capa, midiendo a lo largo del ecuador.',
      bodies: 'Hace avanzar cada cuerpo al ritmo del movimiento anual medio del Sol, medido a lo largo del ecuador.',
    },
    headerAngles: 'Cuánto avanzan los ángulos',
    headerBodies: 'Cuánto avanzan los cuerpos',
  },
  progAngles: {
    natal: {
      label: 'Ángulos natales',
      short: 'Natales',
      tip: 'Los ángulos propios de la carta natal',
      hint: 'Los planetas progresados se leen respecto a los ángulos natales. El marco de la carta natal se mantiene fijo, así que solo se mueven los planetas.',
    },
    progressed: {
      label: 'Ángulos progresados',
      short: 'Progresados',
      tip: 'Los ángulos propios de la carta progresada',
      hint: 'La carta progresada tiene un momento propio —un día tras nacer por cada año de vida—, así que tiene ángulos propios. El mapa se dibuja con ellos en lugar de con los natales.',
      hintTertiary: 'La carta terciaria tiene un momento propio —un día tras nacer por cada mes tropical (27,32 días)—, así que tiene ángulos propios. El mapa se dibuja con ellos, no con los natales.',
    },
    idle: {
      tip: 'No vigente',
      hint: 'Los ángulos se mantienen en la carta natal, así que no se les aplica ningún arco. Elegir un cálculo aquí también cambia el mapa a Ángulos progresados.',
    },
  },
  eclipses: {
    kind: {
      total: 'Total',
      annular: 'Anular',
      hybrid: 'Híbrido',
      partial: 'Parcial',
      penumbral: 'Penumbral',
    },
    body: {
      solar: 'Solar',
      lunar: 'Lunar',
    },
    details: {
      maximum: 'Máximo',
      maximumValue: '{date} · {time} (UTC)',
      type: 'Tipo',
      central: 'central',
      nonCentral: 'no central',
      magnitude: 'Magnitud',
      gamma: 'Gamma',
      saros: 'Serie Saros',
      lunation: 'Lunación',
      sunPosition: 'Grado del eclipse',
      sunPositionTip: 'El grado zodiacal del eclipse: el Sol y la Luna se encuentran aquí en {sign}.',
      moonPositionTip: 'El grado zodiacal de la Luna eclipsada en {sign}: está opuesta al Sol.',
      hemisphere: 'Hemisferio',
      north: 'Norte',
      south: 'Sur',
      duration: 'Duración máx.',
      width: 'Ancho de trayectoria',
      widthValue: '{n} km',
      umbralMag: 'Magnitud umbral',
      penumbralMag: 'Magnitud penumbral',
      penumbralDur: 'Fase penumbral',
      partialDur: 'Fase parcial',
      totalDur: 'Fase total',
    },
    contacts: {
      heading: 'Contactos natales',
      none: 'Ningún contacto a menos de 3°: este eclipse pasa en silencio por la carta.',
      aspect: {
        conjunction: 'en conjunción',
        square: 'en cuadratura',
        opposition: 'en oposición',
      },
      asc: 'Ascendente',
      mc: 'Medio Cielo',
    },
    otherLines: {
      title: 'Otras líneas',
      hint: 'Todo el mapa salvo el eclipse, quitado de golpe para leer sola la trayectoria; desactivado, se impone a los demás interruptores de líneas. Quedan la rueda de la carta y los datos.',
    },
    chartLines: {
      title: 'Carta del eclipse',
      hint: 'La carta del máximo del eclipse —el cielo calculado para ese instante—, agregada a la rueda de la carta como segundo anillo junto a la carta natal.',
    },
    isoStep: {
      '10': {
        label: '10%',
        hint: 'Nueve contornos: una cuadrícula de referencia densa.',
      },
      '20': {
        label: '20%',
        hint: 'Cuatro contornos: un término medio equilibrado.',
      },
      '25': {
        label: '25%',
        hint: 'Tres contornos en pasos de un cuarto (la convención clásica de los mapas de eclipses).',
      },
    },
  },
  lineType: {
    MC: {
      hint: 'Medio Cielo (carrera, vida pública)',
    },
    IC: {
      hint: 'Fondo del Cielo (hogar, raíces)',
    },
    ASC: {
      hint: 'Ascendente (yo, identidad)',
    },
    DSC: {
      hint: 'Descendente (relaciones)',
    },
    VX: {
      hint: 'Vértex (encuentros predestinados); también agrega Vx a la rueda de la carta',
    },
    AVX: {
      hint: 'Anti-Vértex (el extremo oriental del eje); también agrega Avx a la rueda',
    },
  },
} as const;
