// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/synastryHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const synastryHud = {
  title: 'Sinastría',
  chooseComparison: 'Elegir carta de comparación',
  choosePrompt: 'Elige una carta para comparar',
  barToggle: {
    show: 'Ver opciones de sinastría',
    hide: 'Ocultar opciones de sinastría',
  },
  method: {
    label: 'Tipo',
    davison: {
      label: 'Davison',
      hint: 'Punto medio en tiempo y lugar de las dos cartas, calculado como una carta real.',
    },
    composite: {
      label: 'Comp. puntos medios',
      hint: 'Cada planeta y ángulo en el punto medio de las dos cartas, y cada planeta con una latitud y una declinación reales. El marco del mapa sigue el Medio Cielo compuesto.',
    },
  },
  generate: {
    label: 'Generar',
    hint: 'Crea la carta, la activa y quita la carta de comparación de la sinastría.',
    needPartner: 'Elige primero arriba una carta de comparación.',
    compositeParent: 'Una carta compuesta no se puede volver a combinar; elige dos cartas normales.',
  },
} as const;
