// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/timeline.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const timeline = {
  nubMode: {
    transits: 'Tránsitos',
    progressed: 'Prog. secundarias',
    'tertiary-progressed': 'Prog. terciarias',
    'solar-arc': 'Arco solar',
    'primary-directions': 'Primarias',
    cyclo: 'CCG',
  },
  nubFallback: 'Capa',
  barToggle: {
    show: 'Mostrar línea de tiempo',
    hide: 'Ocultar línea de tiempo',
    hint: 'El deslizador de fecha y los controles de reproducción. El asa se queda en ambos casos.',
  },
  drawer: {
    show: 'Mostrar opciones de vista',
    hide: 'Ocultar opciones de vista',
  },
  cyclo: {
    label: 'Mezcla',
    spName: 'Planetas personales progresados',
    spTip: 'Sp — progresado secundario',
    spHint: 'El Sol, la Luna, Mercurio, Venus y Marte se leen en posiciones progresadas secundarias: a un día por año siguen legibles junto a los exteriores. Sus líneas llevan la etiqueta Sp.',
    trName: 'Cuerpos exteriores en tránsito',
    trTip: 'Tr — en tránsito',
    trHint: 'Todo desde Júpiter hacia fuera —más los nodos, Lilith, Quirón y los asteroides— se lee en su posición real de tránsito. Sus líneas llevan la etiqueta Tr.',
  },
  positioning: {
    groupAria: 'Marco de la capa',
    lockedNoTime: 'Hora de nacimiento desconocida: no hay marco natal que mantener, así que el mapa solo puede mostrar el cielo del momento.',
    heldForReturn: 'En pausa mientras el mapa está en una revolución: una carta de revolución solo es ella misma en su propio marco. Elegirlo pone fin a la pausa y devuelve el mapa a este marco.',
  },
  units: {
    minute: 'Minuto',
    hour: 'Hora',
    day: 'Día',
    week: 'Semana',
    month: 'Mes',
    year: 'Año',
  },
  unitsLower: {
    minute: 'minuto',
    hour: 'hora',
    day: 'día',
    week: 'semana',
    month: 'mes',
    year: 'año',
  },
  minorLabel: {
    minute: '1 min',
    hour: '10 min',
    day: '6 horas',
    week: '1 día',
    month: '5 días',
    year: '1 mes',
  },
  stepWords: {
    minute: '{n, plural, =1 {minuto} other {minutos}}',
    hour: '{n, plural, =1 {hora} other {horas}}',
    day: '{n, plural, =1 {día} other {días}}',
    week: '{n, plural, =1 {semana} other {semanas}}',
    month: '{n, plural, =1 {mes} other {meses}}',
    year: '{n, plural, =1 {año} other {años}}',
  },
  stepSymbol: {
    minute: '{n, plural, other {min}}',
    hour: '{n, plural, other {h}}',
    day: '{n, plural, other {d}}',
    month: '{n, plural, one {mes} other {meses}}',
  },
  transport: {
    stepBack: 'Retroceder {count} {unit}',
    stepForward: 'Avanzar {count} {unit}',
    stepBackAria: 'Retroceder',
    stepForwardAria: 'Avanzar',
    play: 'Reproducir',
    pause: 'Pausar',
    stepAmountIn: {
      minute: 'Tamaño del paso, en minutos',
      hour: 'Tamaño del paso, en horas',
      day: 'Tamaño del paso, en días',
      month: 'Tamaño del paso, en meses',
    },
    stepAmountInAria: {
      minute: 'Tamaño del paso en minutos',
      hour: 'Tamaño del paso en horas',
      day: 'Tamaño del paso en días',
      month: 'Tamaño del paso en meses',
    },
  },
  ruler: {
    aria: 'Recorrer la fecha',
  },
  now: {
    label: 'Ahora',
    tip: 'Ir al momento actual',
  },
  returns: {
    label: 'Revoluciones',
    reframes: 'Toma prestado el marco del mapa para el momento propio de la revolución. En el marco natal, el cuerpo que regresa queda fijado en su grado natal, así que sus líneas nunca se moverían de una revolución a la siguiente. Tu marco queda en pausa, no se borra, y vuelve cuando sales de la revolución.',
    chip: {
      solar: 'Revolución solar',
      lunar: 'Revolución lunar',
      tip: 'El mapa está en una revolución',
      hint: 'El marco de la capa se toma prestado mientras el mapa está en una revolución, porque los ángulos de una carta de revolución son los suyos propios. El marco anterior queda en pausa debajo y vuelve al salir. Pasar de una revolución a otra con las flechas mantiene la pausa.',
      clear: 'Salir de la revolución',
      clearHint: 'Devuelve el marco de la capa a donde estaba. La fecha se queda donde está.',
      clearAria: 'Salir de la revolución y restaurar el marco de la capa',
    },
    solar: {
      name: 'Solar',
      chartName: 'Revolución solar',
      snap: 'Revolución solar más cercana',
      snapAria: 'Saltar a la revolución solar más cercana',
      prev: 'Revolución solar anterior',
      prevAria: 'Revolución solar anterior',
      next: 'Revolución solar siguiente',
      nextAria: 'Revolución solar siguiente',
    },
    lunar: {
      name: 'Lunar',
      chartName: 'Revolución lunar',
      snap: 'Revolución lunar más cercana',
      snapAria: 'Saltar a la revolución lunar más cercana',
      prev: 'Revolución lunar anterior',
      prevAria: 'Revolución lunar anterior',
      next: 'Revolución lunar siguiente',
      nextAria: 'Revolución lunar siguiente',
    },
  },
  scale: {
    label: 'Escala',
  },
  rate: {
    label: 'Clave',
  },
  dateField: {
    tipChartZone: 'Momento de tránsito / progresado, en la zona horaria de la carta',
    tipChartZonePlace: 'Momento de tránsito / progresado, en la hora de {place}: el lugar de nacimiento de la carta, que puede no ser donde estás',
    tipUtc: 'Momento de tránsito / progresado, en UTC',
  },
  datePicker: {
    open: 'Editar fecha y hora',
    title: 'Definir fecha y hora',
    scrollKey: 'Desplazar',
    scrollHint: 'para aumentar o disminuir',
    apply: 'Aplicar',
    yearRange: 'Este selector abarca de {min} a {max}: un año fuera de ese rango se ajusta al extremo más cercano.',
  },
  labelFull: {
    transits: 'Tránsitos · {datetime} (UTC)',
    progressed: 'Prog. secundarias · edad {years}',
    'tertiary-progressed': 'Prog. terciarias · edad {years}',
    'solar-arc': 'Arco solar · {deg}°',
    'primary-directions': 'Direcciones primarias · {deg}°',
    cyclo: 'Ciclo·carto·grafía · {datetime} (UTC)',
    synastry: 'Sinastría · {partner}',
    eclipses: 'Eclipse · {datetime} (UTC)',
  },
  measure: {
    progressedAge: 'Edad {years}',
  },
} as const;
