// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/topNav.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const topNav = {
  overlay: {
    menuLabel: 'Capa',
    none: {
      label: 'Ninguna',
      hint: 'Solo la carta natal, sin ninguna técnica temporal aplicada.',
    },
    blocked: {
      composite: 'Una carta compuesta es una carta de punto medio, no un momento: no hay instante de nacimiento que esta técnica pueda hacer avanzar. Cambia a una carta de una sola persona para usarla.',
      'no-time': 'La hora de nacimiento de esta carta es desconocida, así que no hay un momento natal exacto que hacer avanzar: una técnica basada en él lo estaría inventando sin decirlo. Agrega una hora de nacimiento para usar esto.',
      davison: 'Esta carta ya es de dos personas, así que no queda nadie que agregar. Cambia a una carta de una sola persona para construir una sinastría.',
    },
    modes: {
      transits: {
        label: 'Tránsitos',
        desc: 'Dónde están los planetas ahora mismo, sobre tu carta natal.',
      },
      progressed: {
        label: 'Prog. secundarias',
        tipTitle: 'Progresiones secundarias',
        desc: 'Progresiones secundarias: un despliegue simbólico de un día por año.',
      },
      'tertiary-progressed': {
        label: 'Prog. terciarias',
        tipTitle: 'Progresiones terciarias',
        desc: 'Progresiones terciarias: un día por cada mes tropical (27,32 días), una manecilla más fina para la cronología.',
      },
      'solar-arc': {
        label: 'Arco solar',
        desc: 'Cada punto avanzado por el arco del Sol de un grado por año.',
      },
      'primary-directions': {
        label: 'Direcciones primarias',
        desc: 'Un antiguo método de cronología impulsado por la rotación del cielo.',
      },
      cyclo: {
        label: 'Ciclocartografía',
        tipTitle: 'Ciclocartografía (CCG)',
        desc: 'El híbrido de Jim Lewis: los planetas personales progresados por progresión secundaria, con Júpiter y los siguientes en tránsito, en un solo mapa.',
      },
      synastry: {
        label: 'Sinastría',
        desc: 'La carta de otra persona superpuesta a la tuya, para las relaciones.',
      },
      eclipses: {
        label: 'Eclipses',
        desc: 'Trayectorias de eclipses solares y contornos de magnitud, y dónde es visible un eclipse lunar, en todo el mapa.',
      },
    },
  },
  status: {
    natal: 'NATAL',
    hover: 'CURSOR',
    pinned: 'FIJADO',
    'natal-pinned': 'MARCADOR NATAL',
  },
  sidebarToggle: {
    showAria: 'Mostrar la barra lateral de la carta',
    hideAria: 'Ocultar la barra lateral de la carta',
    showTip: 'Mostrar la carta en la barra lateral',
    hideTip: 'Ocultar la barra lateral',
  },
  pin: {
    centerTip: 'Centrar el mapa en el marcador',
    pinNatalTip: 'Marcar el lugar natal',
    controlsTip: 'Controles del marcador del mapa',
  },
  tools: {
    menuLabel: 'Herramientas',
    measure: 'Medir distancia',
    measureItem: 'Medir',
    measureHint: 'Haz clic y arrastra en el mapa para medir la distancia por círculo máximo',
    toolbarHint: '{click} y {drag} en el mapa para medir{rightExit}',
    measureKm: '{n} km',
    measureMi: '{n} mi',
    snap: 'Ajustar',
    snapTip: 'Ajusta el extremo a las líneas de la carta (o mantén presionada la tecla Shift)',
    slideItem: 'Deslizar',
    slideHint: 'Desliza el mundo bajo las líneas natales fijas: avanza el tiempo para mostrar cómo se forman los parans a lo largo del día. Funciona en vista plana o de globo.',
    slideUnavailable: 'Deslizar necesita las líneas natales dibujadas. No disponible mientras Líneas natales esté desactivado (Avanzado ▸ Líneas, Shift+N), Otras líneas las haya retirado o una capa ocupe el lugar de la carta.',
    slideToolbarHint: '{pan} para deslizar el mundo bajo las líneas fijas',
    slideNudgeBack1h: 'Una hora atrás',
    slideNudgeBack4m: 'Cuatro minutos atrás (≈ 1° de giro)',
    slideNudgeFwd4m: 'Cuatro minutos adelante (≈ 1° de giro)',
    slideNudgeFwd1h: 'Una hora adelante',
    slideReset: 'Volver al cielo natal',
    slidePrevEvent: 'Saltar a la salida, culminación o puesta anterior en el punto activo',
    slideNextEvent: 'Saltar a la siguiente salida, culminación o puesta en el punto activo',
    slideElapsedTip: 'Tiempo deslizado desde el momento de la carta',
    slideClockTip: 'Hora del reloj y fecha en el lugar de nacimiento, en la zona horaria de la carta',
    slideAngleTip: 'Rotación alrededor del polo',
    captureItem: 'Captura',
    captureHint: 'Encuadra el mapa y expórtalo como PNG: elige una relación de aspecto, decide qué incluir y luego descárgalo o cópialo.',
    captureToolbarHint: '{pan} y {zoom} para componer dentro del encuadre{escExit}',
    hintKey: {
      click: 'Clic',
      tap: 'Tocar',
      doubleClick: 'Doble {icon} clic',
      doubleTap: 'Doble {icon} toque',
      drag: 'Arrastrar',
      pan: 'Desplazar',
      zoom: 'Zoom',
      esc: 'Esc',
      rightClick: 'Clic {icon} derecho',
      toExit: 'para salir',
    },
  },
  view: {
    menuLabel: 'Ver',
    coordinates: 'Coordenadas',
    coordinatesHint: 'Datos en vivo del lugar del punto activo, sus coordenadas y los ángulos de la carta relocalizada.',
    minimap: 'Minimapa',
    minimapHint: 'La rueda de la carta natal, en pequeño en una esquina mientras exploras el mapa.',
    settings: 'Configuración',
    settingsHint: 'Temas, sistemas de casas, zodiaco y cómo se dibujan la carta y el mapa.',
    teleport: 'Teletransporte',
    teleportHint: 'Busca cualquier lugar y haz volar el mapa directamente hasta allí.',
    skyTimes: 'Horarios del cielo',
    skyTimesHint: 'Los horarios diarios de salida, culminación y puesta en el punto activo, en la franja inferior.',
    localSpace: 'Espacio local',
    localSpaceHint: 'Líneas de dirección desde el origen de la carta hacia cada planeta: tu brújula del espacio local.',
    info: 'Info',
    infoHint: 'Una etiqueta en la esquina que resume los sistemas activos de la carta: marco de las líneas, casas y zodiaco.',
    guides: 'Guías',
    guidesHint: 'Vuelve a ver las guías de introducción como un glosario de los controles del mapa.',
  },
} as const;
