// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Español for ../en/wheel.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../es.lock.json). Keys, order and layout are rewritten on every run.
export const wheel = {
  house: 'Casa {number, selectordinal, other {#}}',
  signMeanings: {
    aries: 'Fuego · Cardinal · iniciativa',
    taurus: 'Tierra · Fijo · estabilidad',
    gemini: 'Aire · Mutable · curiosidad',
    cancer: 'Agua · Cardinal · cuidado',
    leo: 'Fuego · Fijo · expresión personal',
    virgo: 'Tierra · Mutable · precisión',
    libra: 'Aire · Cardinal · equilibrio',
    scorpio: 'Agua · Fijo · intensidad',
    sagittarius: 'Fuego · Mutable · aventura',
    capricorn: 'Tierra · Cardinal · ambición',
    aquarius: 'Aire · Fijo · innovación',
    pisces: 'Agua · Mutable · imaginación',
  },
  houseMeanings: {
    h1: 'Yo · identidad · primeras impresiones',
    h2: 'Dinero · posesiones · autoestima',
    h3: 'Comunicación · hermanos · aprendizaje',
    h4: 'Hogar · familia · raíces',
    h5: 'Creatividad · romance · hijos',
    h6: 'Trabajo · salud · rutina diaria',
    h7: 'Pareja · matrimonio · el «otro»',
    h8: 'Intimidad · recursos compartidos · renacimiento',
    h9: 'Viajes · filosofía · estudios superiores',
    h10: 'Carrera · reputación · vida pública',
    h11: 'Amigos · comunidad · esperanzas',
    h12: 'Soledad · lo oculto · espiritualidad',
  },
  tip: {
    longitude: 'Longitud {lon}',
    latitude: 'Latitud {lat}',
    minorCluster: '{n, plural, one {# cuerpo menor} other {# cuerpos menores}}',
    minorLine: '{name} {lon}',
    minorMore: '+{n} más',
    overlayMinor: '{name} · {chart}',
    overlayMinorCluster: '{chart}: {n, plural, one {# cuerpo menor} other {# cuerpos menores}}',
    minorLineOverlay: '{name} {lon} · {chart}',
    fortuneGeodetic: 'A partir del Ascendente geodésico',
    fortuneGeodeticDay: 'A partir del Ascendente geodésico, como nacimiento de día. Con un nacimiento de noche, se reflejaría respecto al Ascendente',
    fortuneGeodeticNight: 'A partir del Ascendente geodésico, como nacimiento de noche. Con un nacimiento de día, se reflejaría respecto al Ascendente',
    rangeNote: 'Hora de nacimiento desconocida: en cualquier punto de este tramo, en la fecha de nacimiento',
  },
  planetMeanings: {
    Sun: 'Identidad · vitalidad · ego',
    Moon: 'Emociones · instinto · necesidades',
    Mercury: 'Mente · comunicación',
    Venus: 'Amor · belleza · valores',
    Mars: 'Impulso · energía · acción',
    Jupiter: 'Crecimiento · suerte · expansión',
    Saturn: 'Disciplina · estructura · límites',
    Uranus: 'Cambio · libertad · revelación',
    Neptune: 'Sueños · intuición · espíritu',
    Pluto: 'Poder · transformación',
    NorthNode: 'Camino del alma · crecimiento',
    SouthNode: 'Pasado · dones innatos',
    Lilith: 'Sombra · instinto en bruto',
    Chiron: 'El sanador herido',
    Ceres: 'Cuidado · ciclos',
    Pallas: 'Sabiduría · estrategia',
    Juno: 'Compromiso · pareja',
    Vesta: 'Enfoque · devoción',
    Fortune: 'Fortuna · vitalidad · facilidad',
  },
  angles: {
    As: {
      title: 'Ascendente',
      sub: 'Signo ascendente, el yo y las primeras impresiones',
    },
    Ds: {
      title: 'Descendente',
      sub: 'Relaciones y el «otro»',
    },
    Mc: {
      title: 'Medio Cielo (Medium Coeli)',
      sub: 'Carrera, reputación y vida pública',
    },
    Ic: {
      title: 'Fondo del Cielo',
      sub: 'Hogar, raíces y vida privada',
    },
    Vx: {
      title: 'Vértex',
      sub: 'Encuentros predestinados y momentos decisivos; el punto oeste del primer vertical',
    },
    Avx: {
      title: 'Anti-Vértex',
      sub: 'El extremo oriental del eje del Vértex, opuesto al Vértex',
    },
  },
  motion: {
    retrograde: 'Retrógrado',
    stationary: 'Estacionario',
  },
} as const;
