// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/aspectLinesHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const aspectLinesHud = {
  title: 'Aspekte',
  closeAria: 'Aspekte schließen',
  closeHint: 'Dieses Fenster schließen. Die Linien bleiben eingeschaltet – unter Einstellungen ▸ Erweitert ▸ Linien ausschalten.',
  filters: {
    label: 'Filter',
  },
  harmonious: {
    title: 'Harmonisch',
    hint: 'Sextil- und Trigonlinien. Geometrisch eine Familie: Jede Linie ist vom einen Ende ihrer Achse aus ein Sextil und vom anderen aus ein Trigon.',
  },
  challenging: {
    title: 'Herausfordernd',
    hint: 'Quadratlinien – ein Quadrat zum einen Ende einer Achse ist auch ein Quadrat zum anderen, daher steht diese Familie für sich.',
  },
  mcAxis: {
    title: 'Achse der Himmelsmitte',
    hint: 'Linien im Aspekt zum MC (jede auch vom IC aus lesbar).',
  },
  ascAxis: {
    title: 'Horizontachse',
    hint: 'Linien im Aspekt zum Aszendenten (jede auch vom Deszendenten aus lesbar).',
  },
  orbs: {
    label: 'Aspektorben',
    infoTitle: 'Aspektorben',
    infoHint: 'Maximaler Abstand zum exakten Aspekt (in Grad) in der Horoskopzeichnung und den Aspektlisten. Die Aspektlinien der Karte markieren den exakten Winkel und haben keinen Orbis.',
  },
} as const;
