// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/autoFlip.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const autoFlip = {
  suppress: 'Nicht mehr anzeigen',
  ok: 'Verstanden',
  'overlay-frame-held': {
    title: 'Overlay-Bezugsrahmen auf Revolutionsachsen festgehalten',
    body: 'Ein Revolutionshoroskop ist ein eigener Moment mit eigenen Achsen, und die Karte wird jetzt auf diese bezogen gezeichnet statt auf die Radixachsen. Der vorherige Bezugsrahmen ist zurückgestellt, nicht gelöscht – er kehrt zurück, wenn du die Revolution verlässt, oder sofort über das ✕ auf dem Chip.',
  },
  'line-system-held': {
    title: 'Geodätisch ist zurückgestellt',
    body: 'Das geodätische Liniensystem bildet den tropischen Tierkreis auf die Längengrade der Erde ab, daher gibt es keine siderische Fassung davon, die sich zeichnen ließe. Deine Auswahl ist zurückgestellt, nicht gelöscht – stelle den Tierkreis wieder auf „Tropisch“, und sie kehrt zurück.',
  },
  'line-projection': {
    title: 'Diese Linien werden In Mundo gezeichnet',
    body: 'Jedes Programm muss entscheiden, wo ein Himmelskörper „steht“, bevor es dessen Linie zeichnen kann. In Mundo setzt ihn dorthin, wo er am Himmel steht, mitsamt seiner Breite. In Zodiaco drückt diese Breite zuerst auf die Ekliptik herunter.',
  },
  'theme-held': {
    title: 'Dein Design ist zurückgestellt',
    body: 'Das gewählte Design ist gerade nicht verfügbar, deshalb wird die App in dem gezeigt, das du davor verwendet hast. Nichts ist gelöscht: Es kehrt so zurück, wie du es verlassen hast, sobald es wieder verfügbar ist.',
  },
  'theme-edits-held': {
    title: 'Deine eigene Fassung ist zurückgestellt',
    body: 'Deine eigene Fassung dieses Designs ist gerade nicht verfügbar, deshalb wird stattdessen seine Standardfassung gezeigt. Nichts ist gelöscht: Deine kehrt so zurück, wie du sie verlassen hast, sobald sie wieder verfügbar ist.',
  },
  'language-detected': {
    title: 'Jetzt in der Sprache deines Browsers',
    body: 'AstroLina hat jetzt eine Übersetzung in der Sprache, die dein Browser anfordert, und öffnet sich darin. Um wieder Englisch zu verwenden oder eine andere Sprache zu wählen, öffne {route}.',
  },
  'language-held': {
    title: 'Deine gewählte Sprache ist zurückgestellt',
    body: 'Die Sprache, die du gewählt hast, wird auf diesem Gerät übersetzt. Das ist hier gerade nicht möglich, daher wird die App in ihrer üblichen Sprache angezeigt. Deine Auswahl bleibt erhalten und wird nicht gelöscht. Um eine andere Sprache zu wählen, öffne {route}.',
  },
} as const;
