// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/bindingLanguage.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const bindingLanguage = {
  note: 'Als Hilfe für dich übersetzt. Rechtsverbindlich ist nur die englische Fassung.',
  showEnglish: 'Auf Englisch anzeigen',
  showTranslation: 'Übersetzung anzeigen',
  iconLabel: 'Über diese Übersetzung',
} as const;
