// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/captureHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const captureHud = {
  title: 'Aufnahme',
  closeAria: 'Aufnahme schließen',
  closeHint: 'Werkzeug Aufnahme schließen.',
  subject: {
    label: 'Aufnahme',
    map: 'Karte',
    mapHint: 'Die gerahmte Karte exportieren – deine Linien über der Welt, mit dem Horoskop als optionalem Panel daneben.',
    chart: 'Horoskop',
    chartHint: 'Nur das Horoskop exportieren: Horoskopzeichnung oder Positionen füllen den Rahmen, wie in der Seitenleiste – samt Aspekten und Overlay-Ring. Keine Karte, gleiche Bildunterschrift.',
  },
  aspect: {
    label: 'Rahmen',
    square: '1:1',
    squareHint: 'Quadratischer Rahmen (1:1) – ideal für Posts und Profilbilder.',
    portrait: '4:5',
    portraitHint: 'Rahmen im Hochformat (4:5) – das hohe Format für Smartphone-Feeds.',
    landscape: '16:9',
    landscapeHint: 'Rahmen im Querformat (16:9) – breit, für Folien und Titelbilder.',
  },
  transparent: {
    title: 'Transparent (Local Space)',
    hint: 'Ein Schalter für einen sauberen Local-Space-Export: blendet die Linienpfeile aus, beschriftet die Linien wie im übrigen Horoskop (Beschriftungen liegen an den Rahmenkanten, keine Richtungsgrade) und blendet die Grundkarte aus, sodass der Export einen transparenten Hintergrund behält – bereit, um über einen Grundriss oder deinen eigenen Hintergrund gelegt zu werden. Alles kehrt zurück, sobald Aufnahme oder Local Space geschlossen wird.',
    needLs: 'Schalte zuerst Local Space ein (Ansicht ▸ Local Space) – dieser saubere, transparente Export ist auf den Kompass und die Linien von Local Space ausgelegt.',
  },
  lsLabels: {
    name: {
      title: 'Planetenname',
      hint: 'Den Namen jedes Planeten hinter seinem Symbol auf der Local-Space-Beschriftung anzeigen (z. B. „♂ Mars“).',
    },
    degrees: {
      title: 'Grad',
      hint: 'Die Richtung jeder Local-Space-Linie entlang der Linie anzeigen, direkt innerhalb ihrer Beschriftung zur Kompassmitte hin.',
    },
  },
  view: {
    none: 'Keine',
    noneHint: 'Keine Horoskopdetails im Rahmen – nur Karte, Pin, Randbeschriftungen und Bildunterschrift.',
    wheel: 'Zeichnung',
    wheelHint: 'Horoskopzeichnung im Rahmen anzeigen – dieselbe wie in der Seitenleiste. Die Schalter Planeten / Achsen füllen sie; Gewichtung fügt darunter das Raster Element·Modalität an.',
    list: 'Liste',
    listHint: 'Das Horoskop als Liste der Planeten- / Achsenpositionen anzeigen (samt Zählung nach Element·Modalität), dieselben Zeilen wie in der Seitenleiste.',
    phoneTitle: 'Auf Smartphones nicht verfügbar',
    phoneHint: 'Ein Rahmen in Smartphone-Größe ist zu klein, um Horoskopzeichnung oder Liste deutlich neben der Karte zu zeigen, daher bleiben die Details hier aus. Um das Horoskop selbst zu exportieren, Aufnahme auf „Horoskop“ umstellen – die Zeichnung füllt dann den Rahmen und ist in dieser Größe gut lesbar.',
    tooSmallHint: 'Der Rahmen ist zu klein für die Horoskopzeichnung neben der Karte – ihr Rand würde abgeschnitten. Breiteren Rahmen wählen (16:9 hat am meisten Platz), Fenster vergrößern, „Gewichtung“ ausschalten, um der Zeichnung Platz zu geben, oder Aufnahme auf „Horoskop“ umstellen, um sie allein zu exportieren.',
    tooSmallBody: 'In diesem Rahmen passt keine lesbare Horoskopzeichnung neben die Karte, daher sind die Details aus. Eine Aufnahme des Horoskops gibt der Zeichnung den ganzen Rahmen.',
    switchToChart: 'Nur das Horoskop aufnehmen',
    tooSmallCardHint: 'Dieser Rahmen bietet der Horoskopzeichnung nicht den Platz, den ein vollständiges Horoskop braucht – die Aspekte und der Overlay-Ring brauchen mehr Breite, als hier vorhanden ist, und ein breiter, flacher Rahmen lässt einer Zeichnung kaum Höhe. 1:1 oder 4:5 wählen, das Fenster vergrößern, „Gewichtung“ ausschalten, um der Zeichnung ihren Platz zurückzugeben, oder stattdessen die Positionen als „Liste“ aufnehmen.',
    tooSmallCardBody: 'Dieser Rahmen ist zu klein für das vollständige Horoskop, daher werden stattdessen die Positionen gezeigt. Ein höheres Fenster – oder ein Rahmen in 1:1 oder 4:5 – gibt der Horoskopzeichnung den nötigen Platz.',
    clippedBody: 'Einige Details passen nicht in diesen Rahmen und würden im Export abgeschnitten. Versuche einen breiteren Rahmen, ein größeres Fenster oder weniger Gruppen.',
  },
  extras: {
    label: 'Details',
    angles: 'Achsen',
    anglesHint: 'Die Achsen des Horoskops (AS, MC, DS, IC…) im Panel nach den Planeten hinzufügen.',
    balance: 'Gewichtung',
    balanceHint: 'Die Gewichtung nach Element + Modalität hinzufügen – welche Planeten in Feuer/Erde/Luft/Wasser und Kardinal/Fix/Veränderlich fallen.',
  },
  caption: {
    label: 'Bildunterschrift',
    name: 'Name',
    nameHint: 'Horoskopnamen in der Bildunterschrift anzeigen.',
    date: 'Datum',
    dateHint: 'Geburtsdatum in der Bildunterschrift anzeigen.',
    time: 'Uhrzeit',
    timeHint: 'Geburtszeit in der Bildunterschrift anzeigen.',
    location: 'Ort',
    locationHint: 'Ort in der Bildunterschrift anzeigen: den Geburtsort oder deinen Pin, sobald du einen setzt.',
    coordinates: 'Koordinaten',
    coordinatesHint: 'Vollständige Breite und Länge des Ortes in der Bildunterschrift anzeigen: den Geburtsort oder deinen Pin, sobald du einen setzt.',
    calculations: 'Berechnungen',
    calculationsHint: 'Aktive Berechnungssysteme (dieselbe Zeile wie bei Info) in der Bildunterschrift anzeigen, dazu das Zeit-Overlay mit seinem Datum, solange eines gezeichnet ist.',
    discreet: '„Diskreter Modus“ ist an, daher sind Name, Geburtsdatum und Uhrzeit hier und im exportierten Bild ausgeblendet. Drücke P, um sie anzuzeigen.',
  },
  calcOverlay: {
    transits: 'Transite',
    progressed: 'Sek. Progression',
    'tertiary-progressed': 'Tert. Progression',
    'solar-arc': 'Sonnenbogen',
    'primary-directions': 'Primärdirektionen',
    cyclo: 'CCG',
  },
  share: {
    title: 'Teilen',
    hint: 'Das Teilen-Menü deines Geräts öffnen, um das Bild zu speichern oder zu senden (mobil & unterstützte Desktops).',
    sheetTitle: 'AstroLina-Kartografie',
    sheetText: 'AstroLina – webbasierte Astrokartografie für neugierige Köpfe',
  },
  download: {
    title: 'Speichern',
    hint: 'Gerahmte Ansicht als PNG-Datei speichern.',
  },
  copy: {
    title: 'Kopieren',
    hint: 'Gerahmte Ansicht in die Zwischenablage kopieren, bereit zum Einfügen.',
    done: 'Kopiert',
  },
  link: {
    title: 'Link kopieren',
    hint: 'Einen Link kopieren, der dieses Horoskop und diese Ansicht öffnet – die Geburtsdaten stecken im Link, daher nur mit Menschen teilen, die sie sehen dürfen.',
    done: 'Link kopiert',
    warnAria: 'Datenschutzhinweis zum geteilten Link',
    warnBody: 'HINWEIS: Dieser Link enthält die vollständigen Geburtsdaten des Horoskops (Datum, Uhrzeit und Ort).',
    warnSuppress: 'Nicht mehr erinnern',
    warnConfirm: 'Link kopieren',
    warnCancel: 'Abbrechen',
  },
  busy: 'Wird erstellt…',
  failed: 'Export fehlgeschlagen – bitte versuche es erneut.',
  failedReason: {
    'no-frame': 'Die Kartenansicht war nicht bereit. Öffne das Werkzeug Aufnahme erneut und versuche es noch einmal.',
    'no-canvas': 'Dieser Browser hat dem Export keine Zeichenfläche bereitgestellt.',
    'taint-basemap': 'Die Kartenkacheln ließen sich nicht exportieren. Meist liegt das an einem Tracking-Schutz oder Inhaltsblocker – erlaube diese Website und versuche es dann erneut.',
    encode: 'Das Bild war zu groß zum Kodieren. Versuche ein kleineres Rahmenformat.',
    overlay: 'Bildunterschrift und Beschriftungen konnten nicht gezeichnet werden, daher wurde kein Bild erstellt. Lade die App neu und versuche es erneut.',
  },
} as const;
