// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/chartManager.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const chartManager = {
  dialogLabel: 'Horoskope',
  title: 'Meine Horoskope',
  comparisonTitle: 'Synastrie mit {name}',
  comparisonLabel: 'Synastrie',
  searchPlaceholder: 'Namen oder Orte suchen…',
  searchLabel: 'Horoskope durchsuchen',
  clearSearch: 'Suche löschen',
  filter: {
    label: 'Nach Kennzeichen filtern',
    all: 'Alle',
    starred: 'Favorit',
    space: 'Weltraum',
    unknown: 'Unbekannt',
    shared: 'Geteilt',
  },
  folders: {
    new: 'Neuer Ordner',
    newChild: 'Neuer Unterordner',
    rename: 'Ordner umbenennen',
    remove: 'Entfernen',
    moveTo: 'Ablegen in',
    unfiled: 'Ohne Ordner',
    nameLabel: 'Ordnername',
    namePlaceholder: 'Ordnername',
  },
  discreet: {
    hide: '„Diskreter Modus“ einschalten',
    show: '„Diskreter Modus“ ausschalten',
  },
  empty: 'Noch keine gespeicherten Horoskope.',
  noMatches: 'Keine passenden Horoskope.',
  addQuery: '„{name}“ hinzufügen',
  editingHeader: '{name} bearbeiten',
  saveChanges: 'Änderungen speichern',
  addChart: 'Horoskop hinzufügen',
} as const;
