// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/chartWheel.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const chartWheel = {
  resizeLabel: 'Größe der Horoskopzeichnung umschalten',
  shrink: 'Horoskopzeichnung verkleinern',
  enlarge: 'Horoskopzeichnung vergrößern',
  openSidebar: 'Ganze Horoskopzeichnung öffnen',
  openSidebarHint: 'Eine größere Horoskopzeichnung mit Aspekten und Planetentabelle, in der Seitenleiste.',
  openSidebarLabel: 'Horoskop-Seitenleiste anzeigen',
  placeholder: 'Kein Horoskop ausgewählt',
  noChart: 'KEIN HOROSKOP (CCG)',
} as const;
