// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/common.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const common = {
  close: 'Schließen',
  cancel: 'Abbrechen',
  edit: 'Bearbeiten',
  delete: 'Löschen',
  keep: 'Behalten',
  locationFallbackOcean: 'Ozean',
  tzWarning: '⚠ Zeitzone vor 1970 außerhalb von USA/EU: Prüfe die Sommerzeit in einem Atlas',
  timeUnknownBanner: 'Geburtszeit unbekannt',
  provisionalTimeBanner: '⚠ {time} im Test – vorläufig, nicht gespeichert',
  locked: {
    feature: 'Die Funktion {feature} gehört zum Tarif {tier}.',
    featureAnyTier: 'Die Funktion {feature} ist in deinem Tarif nicht enthalten.',
  },
  cardinal: {
    north: 'N',
    south: 'S',
    east: 'O',
    west: 'W',
  },
  hud: {
    dragToMove: 'Zum Bewegen ziehen',
    dockKey: 'Doppelt',
    dockHint: 'zum Andocken · rastet mittig ein',
    recentreHint: 'zum Zentrieren',
    collapse: 'Bereich einklappen',
    expand: 'Bereich ausklappen',
    collapseHint: 'Bedienelemente ein- oder ausblenden.',
    closeNamed: '{name} schließen',
  },
} as const;
