// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/creditsModal.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const creditsModal = {
  title: 'Nachweise & Lizenzen',
  thanks: {
    tip: 'Besonderer Dank',
    hint: 'Nachweise anzeigen',
    title: 'Besonderer Dank',
    leadRole: 'Die Astrologin hinter AstroLina',
    leadBody: 'Diese App ist aus ihrer Praxis entstanden, und sie ist ihr bis heute verpflichtet. Die Methoden, denen sie folgt, die Konventionen, an die sie sich hält, und das Urteil hinter jeder Linie, die sie zeichnet, sind ihre – geduldig erklärt, oft mehr als einmal, bis die Software dem Handwerk entsprach.',
    othersHeading: 'Unser Dank gilt auch',
    body: 'Zwei professionelle Astrologinnen haben diesem Projekt ihre Zeit, ihr Fachwissen und sehr viel Geduld geschenkt – sie haben Fragen beantwortet, Konventionen geprüft und einem frühen Werkzeug geholfen, Fuß zu fassen. Ohne sie wäre es ärmer.',
    role: 'Professionelle Astrologin',
  },
  intro: 'AstroLina basiert auf offenen Daten und Open-Source-Software. Die vollständigen Lizenztexte stehen im Projekt-Repository zur Verfügung.',
  notice: {
    lead: 'Wir sind neu dabei und freuen uns über deine Hilfe.',
    body: 'Die Astronomie ist solide – Swiss Ephemeris, JPL-Daten, gegen den Horizons-Dienst der NASA auf deutlich unter eine Bogensekunde geprüft. Die App drumherum ist Version eins, und sie kann so viel, dass wir vor dem Start nicht jeden Winkel erreichen konnten. Wenn also eine Linie falsch aussieht, eine Zahl seltsam wirkt oder etwas einfach nicht tut, was du möchtest, sag es uns bitte – jede Meldung liest ein Mensch, und wir wollen daraus ein Werkzeug machen, auf das du dich verlassen kannst.',
    report: 'Problem melden.',
  },
  groups: {
    astrolina: 'AstroLina',
    mapsPlaces: 'Karten & Orte',
    astronomy: 'Astronomie',
    typeSoftware: 'Schrift & Software',
  },
  notes: {
    astrolina: '© 2026 AstroLina. Freie Open-Source-Software unter der GNU Affero General Public License v3.0.',
    sourceCode: 'Vollständiger Quellcode, verfügbar gemäß der AGPL. Beiträge willkommen.',
    openstreetmap: 'Grundkartendaten (auch auf der Karte selbst genannt).',
    openfreemap: 'Kostenlose Vektorkacheln, Beschriftungsschriften und Sprites.',
    mapStyles: 'MapTiler Basic, OSM Bright, Dark Matter, Positron und Fiord Color, teilweise angepasst. © MapTiler.com & OpenMapTiles-Mitwirkende; © Mapbox; © CartoDB.',
    geonames: 'Offline-Suche nach Ortsnamen und Städten.',
    photon: 'Online-Suche nach Orten und Adressen; Daten © OpenStreetMap-Mitwirkende.',
    swisseph: 'Planetenpositionen (JPL DE441). © Astrodienst AG, über @swisseph/browser.',
    nasaEclipse: 'Kataloge der Sonnen- und Mondfinsternisse (Daten, Typen, Saros-Reihen). Finsternisvorhersagen von Fred Espenak und Jean Meeus (NASA/GSFC).',
    jplSbdb: 'Bahnklassen hinter den Kennzeichen der Kleinplaneten.',
    noto: 'Astrologische Glyphen. © 2022 The Noto Project Authors.',
    maplibre: 'Interaktive Kartendarstellung.',
    rtlText: 'Kartenbeschriftungen von rechts nach links: arabische Buchstaben verbunden, Arabisch und Hebräisch in Leserichtung. © 2017 Mapbox.',
    icu: 'Der Code für Glyphenformung und bidirektionalen Text im Plugin für Beschriftungen von rechts nach links. © Unicode, Inc.',
    other: 'Dazu weitere MIT-lizenzierte Bibliotheken, die im Projekt-Repository aufgeführt sind.',
  },
  footer: ' · Die Berechnungen der Astrokartografie und die Gestaltung der Oberfläche stammen von AstroLina selbst; die zugrunde liegenden Ephemeriden- und Kartendaten sind oben aufgeführt.',
} as const;
