// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/localSpaceHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const localSpaceHud = {
  title: 'Local Space',
  closeAria: 'Local Space schließen',
  closeHint: 'Local-Space-Ansicht ausschalten.',
  lsOrigin: {
    pin: 'Vom Pin',
    pinHint: 'Local Space am Relokationsort: Die Linien gehen vom aktiven Pin aus (vom Geburtsort, wenn nichts angepinnt ist).',
    birthplace: 'Geburtsort',
    birthplaceHint: 'Die Linien bleiben am Geburtsort verankert, auch wenn ein Pin gesetzt ist.',
    home: 'Wohnort',
    homeHint: 'Die Richtungen von dort ausgehen lassen, wo die Person dieses Horoskops jetzt wohnt – direkt hier festlegen oder ändern. Ohne festgelegten Wohnort gilt der Geburtsort.',
    homeUnset: 'Kein Wohnort für dieses Horoskop festgelegt – die Richtungen gehen vom Geburtsort aus, bis du einen festlegst.',
  },
  hideInbound: {
    title: 'Eingehende Linien',
    hint: 'Die eingehende Fortsetzung jeder Local-Space-Linie – die gestrichelte Hälfte, die zum Gegenpunkt des Himmelskörpers zeigt, gegenüber seiner ausgehenden (durchgezogenen) Richtung. Ausschalten, um nur die ausgehenden Hälften zu behalten.',
  },
  hideDegrees: {
    title: 'Grad',
    hint: 'Die Richtung auf jeder ausgehenden Beschriftung, in Grad und Minuten. Ausgeschaltet zeigen die Beschriftungen nur LS und das Symbol.',
  },
  hideCompass: {
    title: 'Kompass',
    hint: 'Die Kompassrose des lokalen Horizonts, die beim Hineinzoomen am Ursprung eingeblendet wird.',
  },
  flyToOrigin: {
    title: 'Zum Ursprung fliegen',
    hint: 'In den lokalen Horizont eintauchen: die Kamera zum Ursprung fliegen, von dem die Linien ausgehen.',
  },
} as const;
