// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/map.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const map = {
  ctrl: {
    zoomIn: 'Hineinzoomen',
    zoomOut: 'Herauszoomen',
    resetBearing: 'Richtung & Neigung zurücksetzen',
  },
  pin: {
    natal: 'Radix-Geburtsort (zum Entfernen rechtsklicken)',
    custom: 'Angepinnter Ort (zum Entfernen rechtsklicken)',
    home: 'Wohnort – wo dieses Horoskop jetzt zu Hause ist (rechtsklicken, um den Pin zu entfernen)',
  },
  home: {
    tip: 'Wohnort',
    hint: 'Klicken, um das Horoskop hier zu lesen',
  },
  flyToZenith: 'Zum Zenit fliegen: {prefix}{planet}',
  flyToAspectPoint: 'Dorthin fliegen, wo der Grad dieses Aspekts ({planet}, {aspect}) im Zenit steht (erneut klicken, um zurückzukehren)',
  flyToMidpoint: 'Dorthin fliegen, wo die Halbsumme {planetA}/{planetB} im Zenit steht (erneut klicken, um zurückzukehren)',
  aspectNames: {
    sextile: 'Sextil',
    square: 'Quadrat',
    trine: 'Trigon',
  },
  flyToParan: 'Zum Schnittpunkt dieses Parans fliegen (erneut klicken, um zurückzukehren)',
  flyToLocalSpaceOrigin: 'Zum Ursprung des Local Space fliegen (zum Pin)',
  ecliptic: 'Ekliptik',
  polarNote: 'Polarzone: Jenseits des Scheitelpunkts dieser Linie tauschen aufgehende und untergehende Linie die Rollen.',
  eclipse: {
    central: 'Zentrallinie',
    pathEdge: 'Rand des zentralen Pfads',
    isoline: 'Maximale Finsternis: {pct}',
    outerLimit: 'Sichtbarkeitsgrenze – innerhalb dieser Linie überhaupt eine Finsternis',
    horizon: 'Mondauf-/-untergangslinie bei {phase}',
    localMax: 'Hier {pct} der Sonne bedeckt, um {time} (UTC)',
    lunarAllVisible: 'Die ganze Finsternis ist von hier aus sichtbar',
    lunarPartView: 'Ein Teil der Finsternis ist von hier aus sichtbar (Kontakte: {n} von {total})',
  },
  eclipseCard: {
    notVisible: 'Finsternis hier nicht sichtbar',
    utc: 'UTC',
    c1: 'Beginn partiell',
    c2: 'Beginn Totalität',
    c2Annular: 'Beginn Ringphase',
    max: 'Maximum',
    c3: 'Ende Totalität',
    c3Annular: 'Ende Ringphase',
    c4: 'Ende partiell',
    atSunrise: 'bei Sonnenaufgang',
    atSunset: 'bei Sonnenuntergang',
    maxValue: 'Magnitude {mag} · {obsc} bedeckt',
    duration: 'Dauer',
    phase: {
      P1: 'Beginn Halbschatten',
      U1: 'Beginn partiell',
      U2: 'Beginn Totalität',
      max: 'Maximum',
      U3: 'Ende Totalität',
      U4: 'Ende partiell',
      P4: 'Ende Halbschatten',
    },
    belowHorizon: 'Mond unter dem Horizont',
    moonrise: 'Mondaufgang',
    moonset: 'Monduntergang',
  },
  lineCard: {
    distance: '{label} {km} km / {mi} mi',
  },
  zenithTitle: '{planet} im Zenit',
  zenithSub: 'wo {planet} senkrecht über dem Kopf steht',
  nadirTitle: '{planet} im Nadir',
  nadirSub: 'wo {planet} senkrecht unter den Füßen steht',
  geoReadout: {
    place: '{place} GE',
    coords: '{lat} {lng} GE',
    as: 'AS',
    mc: 'MC',
  },
  geoLegend: {
    aria: 'Legende der Zonenschattierung',
    isolate: 'Nur Zonen der Gruppe {group} anzeigen',
    clear: 'Alle Zonen anzeigen',
  },
  zoomOutToWide: 'Auf eine weite Ansicht herauszoomen',
  zoomOut: 'Herauszoomen',
  webgl: {
    unsupportedTitle: 'Diese Karte benötigt WebGL',
    unsupportedBody: 'Dein Browser stellt dieser Seite keinen WebGL-Grafikkontext bereit, daher kann die Karte nicht gezeichnet werden.',
    tipsHeading: 'Ein paar Dinge, die du versuchen kannst:',
    tipAccel: 'Schalte in den Browsereinstellungen die Hardwarebeschleunigung ein und lade die Seite dann neu.',
    tipShield: 'Erlaube WebGL / Canvas für diese Website, wenn du einen Anti-Fingerprinting- oder Datenschutz-Blocker verwendest.',
    tipBrowser: 'Oder öffne AstroLina in einem anderen aktuellen Browser.',
    lostTitle: 'Die Karte hat ihren Grafikkontext verloren',
    lostBody: 'Das kann passieren, wenn das Gerät wenig Grafikspeicher hat. Oft behebt sich das von selbst – wenn nicht, lade die Seite neu.',
    reload: 'Seite neu laden',
  },
} as const;
