// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/missions.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const missions = {
  guideTitle: 'Missionen',
  title: 'Anleitung',
  close: 'Schließen',
  skipTip: 'Diese Anleitung überspringen',
  ok: 'OK, verstanden',
  okLocked: 'Erst alle Missionen abschließen',
  dontShowAgain: 'Nicht mehr anzeigen',
  prevGuide: 'Vorherige Anleitung',
  nextGuide: 'Nächste Anleitung',
  guidePosition: 'Anleitung {current} von {total}',
  gesture: {
    double: 'Doppelt',
    right: 'Rechts',
    hold: 'Halten',
    shift: 'Umschalt',
    drag: 'Ziehen',
    click: 'Klicken',
    tap: 'Tippen',
    doubleTap: 'Doppeltippen',
    longPress: 'Lange drücken',
    touchDrag: 'Berühren & Ziehen',
    twoFinger: 'Zwei-Finger-Ziehen',
    pinch: 'Auf-/Zuziehen',
    snap: 'Einrasten',
  },
  pill: {
    double: 'Doppelt {icon} klicken',
    right: 'Rechts {icon} klicken',
    hold: 'Halten {icon} ziehen',
    shiftDrag: 'Umschalt {icon} ziehen',
    rightDrag: 'Rechts {icon} ziehen',
    tapSnap: 'Tippen {icon} einrasten',
    holdShift: 'Umschalt {icon} gedrückt halten',
  },
  mapBasics: {
    subtitle: 'So setzt du einen {pin} Pin',
    createPin: 'um einen Pin zu setzen',
    removePin: 'um einen Pin zu entfernen',
    placeNatal: 'um den Radix-Pin zu setzen',
  },
  measureBasics: {
    subtitle: 'So nutzt du das Werkzeug {ruler} Messen',
    drawLine: 'und {drag}, um eine Linie zu zeichnen',
    touchDrawLine: 'um eine Linie zu zeichnen',
    shiftSnap: 'beim Messen über einer Linie, um daran einzurasten – die genaue Entfernung zu dieser Linie',
    rightCancel: 'um das Werkzeug abzubrechen',
    touchSnap: 'dann über eine Linie ziehen, um einzurasten',
    touchCancel: 'erneut auf das Werkzeug Messen, um es zu beenden',
  },
  zoomBasics: {
    subtitle: 'So kannst du schnell {zoom} zoomen',
    zoomOut: 'auf die Schaltfläche „Herauszoomen“',
    quickZoom: 'um ein Zoomfenster aufzuziehen',
    perspective: 'um die Perspektive zu ändern (nur in der 3D-Globusprojektion)',
    touchQuickZoom: 'um hinein- oder herauszuzoomen',
  },
} as const;
