// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/placeSearch.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const placeSearch = {
  scopeLabel: 'Ort',
  noMatches: 'Keine Ergebnisse.',
  failed: 'Die Suche konnte nicht ausgeführt werden. Versuche es erneut.',
  scopeAria: 'Suchbereich',
  more: 'Mehr anzeigen',
} as const;
