// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/planets.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const planets = {
  Sun: {
    name: 'Sonne',
    theme: 'Deine Kernidentität, Lebenskraft und wo du strahlst.',
  },
  Moon: {
    name: 'Mond',
    theme: 'Emotionen, Instinkt und was dir ein Gefühl von Zuhause gibt.',
  },
  Mercury: {
    name: 'Merkur',
    theme: 'Der Verstand: wie du denkst, lernst und kommunizierst.',
  },
  Venus: {
    name: 'Venus',
    theme: 'Liebe, Schönheit, Genuss und was du schätzt.',
  },
  Mars: {
    name: 'Mars',
    theme: 'Antrieb, Mut und wie du dich durchsetzt und handelst.',
  },
  Jupiter: {
    name: 'Jupiter',
    theme: 'Wachstum, Glück und wo sich das Leben weitet und großzügig anfühlt.',
  },
  Saturn: {
    name: 'Saturn',
    theme: 'Disziplin, Grenzen und die hart erarbeiteten Lektionen der Reife.',
  },
  Uranus: {
    name: 'Uranus',
    theme: 'Plötzlicher Wandel, Freiheit und dein rebellischer Funke.',
  },
  Neptune: {
    name: 'Neptun',
    theme: 'Träume, Intuition, Spiritualität und schöne Illusion.',
  },
  Pluto: {
    name: 'Pluto',
    theme: 'Macht, Intensität und tiefgreifende Wandlung und Wiedergeburt.',
  },
  NorthNode: {
    name: 'Nordknoten',
    theme: 'Dein Entwicklungsfeld: wohin das Leben dich ruft und wo Zugehörigkeit dich findet.',
  },
  SouthNode: {
    name: 'Südknoten',
    theme: 'Vertrauter Boden: ererbte Gaben, tiefe Wurzeln und was du bereit bist loszulassen.',
  },
  Lilith: {
    name: 'Lilith',
    tipName: 'Lilith (Schwarzer Mond)',
    theme: 'Roher, ungezähmter Instinkt und wo du dich nicht zähmen lässt.',
  },
  Chiron: {
    name: 'Chiron',
    theme: 'Der verwundete Heiler: Heilung durch deine eigene tiefste Verletzung.',
  },
  Ceres: {
    name: 'Ceres',
    theme: 'Fürsorge, Nahrung und die Lebenszyklen von Verlust und Wiederkehr.',
  },
  Pallas: {
    name: 'Pallas',
    theme: 'Strategie, Können und klarsichtiges Lösen von Problemen.',
  },
  Juno: {
    name: 'Juno',
    theme: 'Bindung, Partnerschaft und was du brauchst, damit es sich gleichberechtigt anfühlt.',
  },
  Vesta: {
    name: 'Vesta',
    theme: 'Hingabe, Fokus und die innere Flamme, die dir heilig ist.',
  },
  Fortune: {
    name: 'Glückspunkt',
    theme: 'Leichtigkeit, Gedeihen und wo Körper und weltliches Leben florieren.',
  },
} as const;
