// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/settings.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const settings = {
  sections: {
    appearance: 'Darstellung',
    mapFilters: 'Kartenfilter',
    calculation: 'Berechnung',
    advanced: 'Erweitert',
  },
  headings: {
    theme: 'Design',
    privacy: 'Privatsphäre',
    details: 'Details',
    projection: 'Projektion',
    language: 'Sprache',
    planets: 'Planeten',
    points: 'Punkte',
    minorBodies: 'Kleinkörper',
    angles: 'Achsen',
    lines: 'Linien',
    lineSystem: 'Liniensystem',
    lineProjection: 'Linienprojektion',
    geoGrid: 'Geodätisches Gitter',
    lunarNode: 'Mondknoten',
    houseSystem: 'Häusersystem',
    zodiac: 'Tierkreis',
    aspectOrbs: 'Aspektorben',
    primaryRate: 'Zeitschlüssel (Primärdir.)',
    display: 'Anzeige',
    arc: 'Bogen',
    progAngles: 'Achsen',
    magnitudeSteps: 'Magnitudenstufen',
    fortuneFormula: 'Glückspunkt',
    rulerships: 'Zeichenherrscher',
  },
  details: {
    roadsRivers: 'Straßen/Flüsse',
    roadsRiversHint: 'Zeigt Straßen und Flüsse der Grundkarte. Ausblenden für einen ruhigeren Hintergrund hinter den Astrokartografie-Linien.',
    placeNames: 'Ortsnamen',
    placeNamesHint: 'Zeigt Städte- und Ländernamen der Grundkarte. Das ist unabhängig von den Beschriftungen der ACG-Linien, die in jedem Fall bleiben.',
  },
  shiftTag: 'Umschalt',
  natal: {
    title: 'Radix',
    hint: 'Das zugrunde liegende Geburtshoroskop. Ausgeblendet tritt das Overlay an seine Stelle und übernimmt Linien, Horoskopzeichnung und Anzeigen des Horoskops.',
  },
  languageUnavailable: 'Demnächst verfügbar.',
  machine: {
    section: 'Automatisch übersetzt',
    sectionHint: 'Die Sprachen oben sind in AstroLina enthalten. Die Sprachen unten werden auf diesem Gerät automatisch übersetzt.',
    hint: 'Auf diesem Gerät aus dem Englischen übersetzt, während du die App nutzt. Manche Formulierungen können ungenau sein.',
    downloadHint: 'Auf diesem Gerät aus dem Englischen übersetzt. Beim ersten Mal wird das Übersetzungsmodell auf das Gerät heruntergeladen.',
    partialHint: 'Ein Teil der App ist noch auf Englisch. Erneut auswählen, um das Herunterladen der Übersetzung auf dieses Gerät abzuschließen.',
    heldDownloadHint: 'Deine Auswahl – zurückgestellt, bis die Übersetzung wieder auf dieses Gerät heruntergeladen ist. Zum Herunterladen auswählen.',
    heldHint: 'Dieses Gerät kann gerade nicht in diese Sprache übersetzen. Deine Auswahl bleibt erhalten und kehrt zurück, sobald das möglich ist.',
    cacheHint: 'Angezeigt wird, was dieses Gerät zuvor übersetzt hat. Es kann hier nicht mehr übersetzen, daher bleibt neuer Text auf Englisch.',
    downloading: '{language} wird auf dieses Gerät heruntergeladen… {percent} %',
    translating: 'Wird in {language} übersetzt…',
    failed: '{language} konnte auf diesem Gerät nicht eingerichtet werden.',
    disclosure: 'Auf diesem Gerät maschinell übersetzt. Manche Formulierungen können ungenau sein; was noch nicht übersetzt ist, erscheint auf Englisch.',
  },
  dock: {
    open: 'Einstellungen öffnen',
    close: 'Einstellungen schließen',
  },
  userRate: {
    label: 'Grad pro Jahr',
  },
  parans: {
    title: 'Parans',
    hint: 'Breiten, auf denen zwei Himmelskörper zugleich eckständig sind – einer aufgehend, ein anderer kulminierend usw. Die Parans deines Horoskops bleiben neben einem Overlay sichtbar.',
    blockedCyclo: 'Kein einzelner Himmelsmoment – die Zyklokartografie kombiniert progressive und transitierende Himmelskörper. Schalte „Radix“ ein, um die eigenen Parans des Horoskops zurückzuholen.',
    blockedOverlay: 'Parans stammen aus dem Horoskop, und dieses Overlay steht gerade an seiner Stelle. Schalte „Radix“ ein, um die Parans des Horoskops zurückzuholen.',
  },
  aspectLines: {
    title: 'Aspektlinien',
    hint: 'Linien, wo ein Planet im Sextil (⚹), Quadrat (□) oder Trigon (△) zu MC oder Aszendent steht – jeder Aspekt zweimal, je Seite einmal. Ein Trigon zum AS ist ein Sextil zum DS; für beide Deutungen auf eine Linie zeigen. Konjunktion und Opposition sind die Achsenlinien des Planeten, schon auf der Karte.',
    openHud: 'Anpassen',
    openHudHint: 'Fenster Aspekte öffnen: die Linien der Karte nach Charakter und Achse filtern und alle Aspektorben auf einmal einstellen.',
  },
  midpointLines: {
    title: 'Halbsummenlinien',
    hint: 'Linien, wo die Halbsumme zweier sichtbarer Himmelskörper genau auf einer Achse liegt (z. B. Su/Mo MC). In Mundo nutzt die Halbsumme der Körper selbst (mittlere RA und Deklination), In Zodiaco die klassische Halbsumme in Länge. Den Planetenfilter eingrenzen, damit die Auswahl übersichtlich bleibt.',
    blockedCyclo: 'Eine Halbsumme würde hier einen progressiven und einen transitierenden Himmelskörper zu einem Punkt mitteln – über zwei Epochen hinweg inkohärent.',
  },
  zenithNadir: {
    title: 'Zenit/Nadir',
    hint: 'Markiert, wo jeder Himmelskörper senkrecht oben (Zenit: Kreis auf der MC-Linie) und unten steht (Nadir: Raute auf der IC-Linie). Zum Erkennen darauf zeigen, zum Hinfliegen klicken.',
  },
  aspectOrbs: {
    hint: 'Max. Abstand vom Exakten (Grad) je Aspekt in Horoskopzeichnung und Aspektlisten. „Lichter“ erweitert jeden Orbis bei Sonne oder Mond; „Parallelen“ ist der Deklinationsorbis.',
    setDegrees: 'Grad einstellen',
    orbAria: 'Orbis für den Aspekt {aspect}, in Grad',
    lumLabel: 'Lichter +',
    lumHint: 'Zusätzlicher Orbis in Grad, wann immer Sonne oder Mond beteiligt sind.',
    lumAria: 'Zusätzlicher Orbis bei Beteiligung eines Lichts, in Grad',
    declinationLabel: 'Parallelen',
    declinationAria: 'Orbis für die Aspekte Parallele und Kontraparallele, in Grad Deklination',
  },
  zodiac: {
    tropical: {
      label: 'Tropisch',
      hint: 'Zeichen an den Jahreszeiten verankert (0° Widder = Märzäquinoktium). Der westliche Standard.',
    },
    lahiri: {
      label: 'Siderisch · Lahiri',
      hint: 'Zeichen an den Fixsternen verankert, nach dem Lahiri-Ayanamsa (der vedische Standard, heute ~24° hinter dem tropischen Tierkreis). Ändert Horoskopzeichnung und Anzeigen; die Kartenlinien markieren tierkreisunabhängige Ereignisse und bleiben stehen.',
    },
    'fagan-bradley': {
      label: 'Siderisch · Fagan/Bradley',
      hint: 'Zeichen an den Fixsternen verankert, nach dem Fagan/Bradley-Ayanamsa (der westliche siderische Standard). Ändert Horoskopzeichnung und Anzeigen; die Kartenlinien bleiben stehen.',
    },
  },
  natalLines: {
    title: 'Radixlinien',
    hint: 'Radix-Achsenlinien auf Aszendent, MC, Deszendent und IC – neben einem Overlay auch ihre Parans. Horoskopzeichnung und Anzeigen bleiben; ausgeblendete Linien sind nicht klickbar.',
  },
  starLines: {
    title: 'Fixsterne',
    hint: 'Achsenlinien der klassischen Fixsterne (Regulus, Spica, Algol und Co.): gepunktete Linien, mit kleinen Sternen durchsetzt, in einem gemeinsamen Sternlicht-Farbton. Für zirkumpolare Sterne entfallen die Auf- und Untergangslinien; dort sind Parans die traditionelle Deutung.',
    bright: 'Hauptsterne',
    brightHint: 'Die vier Königssterne und die hellsten Klassiker (18 Sterne).',
    all: 'Komplettes Set',
    allHint: 'Das gesamte mitgelieferte Arbeitsset (40 Sterne). Mit einer vollen Karte rechnen.',
  },
  nightShade: {
    title: 'Nachtseite',
    hint: 'Schattiert die Hälfte der Erde, auf der im angezeigten Moment Nacht ist.',
  },
  discreet: {
    title: 'Diskreter Modus',
    hint: 'Blendet Namen, Geburtsdaten und Geburtsorte überall am Bildschirm aus – auch in der Bildunterschrift einer Aufnahme und im exportierten Bild –, damit du mit jemandem neben dir arbeiten kannst. Karte und Linien bleiben unverändert, und ein eigens erstelltes Dokument zeigt weiterhin die echten Daten.',
  },
  orbZones: {
    title: 'Orbiszonen',
    hint: 'Schattierte Einflusszonen: ein am Boden gemessenes Band um jede planetare Achsenlinie und jeden Paran. Der Einfluss klingt nach außen ab; der Rand ist Konvention, kein Steilabfall.',
    unitAria: 'Entfernungseinheit der Orbiszonen (km oder mi)',
    lineAria: 'Orbiszonenbreite für Linien, je Seite',
    paranLabel: 'Parans',
    paranAria: 'Orbisbreite der Parans, je Seite',
  },
  theme: {
    glass: {
      label: 'Glas',
      hint: 'Mattsilberne Bedienfelder über einer hellen, detailreichen Karte mit cremefarbenem Land und blassblauen Meeren.',
    },
    dark: {
      label: 'Dunkel',
      hint: 'Eine tief schiefergraue Karte unter dunklen Bedienfeldern, für lange Nächte gemacht, auf der jede Linie hervorsticht.',
    },
    vintage: {
      label: 'Erde',
      hint: 'Eine warme Atlas-Optik: sanft blaue Meere und sandfarbenes Land, eingefasst von pergamentbraunen Bedienfeldern.',
    },
    customize: 'Anpassen',
    customizeHint: 'Design-Editor öffnen: Farben, Linienstile und Effekte, von wenigen groben Entscheidungen bis zu jedem einzelnen Wert.',
    customHeld: 'Im Moment nicht verfügbar. Solange erscheint die App in dem Design, das du davor verwendet hast; deine Wahl bleibt erhalten und wird nicht gelöscht.',
    customEditsHeld: 'Deine eigene Version dieses Designs ist im Moment nicht verfügbar, daher wird seine Standardversion angezeigt; deine bleibt erhalten und wird nicht gelöscht.',
    outlineUnavailable: 'Die Umrisskarte zeigt nur Küstenlinien: keine Straßen, Flüsse oder Ortsnamen. Wähle unter „Anpassen“ eine andere Karte, um dies zu nutzen; deine Wahl bleibt erhalten.',
    lockedNote: 'Für dieses Konto noch nicht verfügbar. Wähle es aus, um zu sehen, womit es sich freischalten lässt.',
    keptNote: 'Bleibt dir erhalten. Wechselst du zu einem anderen Design, brauchst du für die Rückkehr zu diesem, was das Abzeichen zeigt.',
  },
  projection: {
    hint: 'Wie die Welt gezeichnet wird – nicht, wo etwas liegt. Beide Ansichten tragen dieselben Koordinaten ein, und jede Entfernung, die die App angibt (die Zeile zur geringsten Entfernung in einer Linienkarte, das Messen per Klicken und Ziehen, die Orbiszonen), ist eine echte, auf der Kugel gemessene Bodenentfernung. Nähe nach Augenmaß zu beurteilen ist aber in keiner Ansicht sicher: „Flach“ dehnt den Maßstab zu den Polen hin, der Globus staucht ihn zu seinem Rand hin – also die Entfernung ablesen, nicht den Zwischenraum.',
    '2d': {
      label: 'Flach',
      hint: 'Klassische Web-Mercator-Karte',
    },
    '3d': {
      label: 'Globus',
      hint: 'Drehbarer 3D-Globus',
    },
  },
  lineSystem: {
    celestial: {
      label: 'Himmelsbezogen',
      hint: 'Standard-Astrokartografie: Achsen nach dem Himmel platziert (Sternzeit)',
    },
    geodetic: {
      label: 'Geodätisch',
      hint: 'Geodätische Zuordnung: der Tierkreis auf die Längengrade der Erde übertragen (Greenwich = 0° Widder, immer tropisch), unabhängig von der Geburtszeit',
    },
  },
  geoGrid: {
    mc: {
      title: 'MC-Meridiane',
      hint: 'Zwölf Meridiane, alle 30° östlich von Greenwich. Auf einer geodätischen Karte beginnt an jedem ein MC-Zeichen; das Zeichen steht oben auf der Karte.',
    },
    asc: {
      title: 'Aszendentenkurven',
      hint: 'Wo jedes Zeichen aufzusteigen beginnt: Jeder Ort auf einer Kurve hat 0° dieses Zeichens als Aszendenten. Ohne gezeichnete Horoskoplinien standardmäßig an; deine Wahl geht vor.',
    },
    zones: {
      title: 'Zonenschattierung',
      hint: 'Füllt die zwölf MC-Zonen: Element als Farbe, Modalität als Tönung (Kardinal am dunkelsten, Veränderlich am hellsten). Die Legende zeigt ein Element oder eine Modalität einzeln.',
    },
    presentation: {
      title: 'Präsentation',
      hint: 'Verstärkt die Zonenschattierung von schwach auf kräftig, um die Zonen jemand anderem zu zeigen.',
    },
  },
  coordSystem: {
    mundo: {
      label: 'In Mundo',
      hint: 'Linien nutzen die eigene Stellung jedes Himmelskörpers am Himmel (RA / Dekl.). Für die Sonne auf der Ekliptik identisch mit In Zodiaco; am weitesten auseinander bei Pluto und Mond.',
    },
    zodiaco: {
      label: 'In Zodiaco',
      hint: 'Himmelskörper werden vor dem Zeichnen der Linien auf die Ekliptik projiziert (eine verbreitete ACG-Voreinstellung).',
    },
  },
  fortuneFormula: {
    hint: 'Der Glückspunkt ist ein berechnetes Los der Vitalität und weltlichen Leichtigkeit – ein Punkt auf der Ekliptik, kein Himmelskörper am Himmel. Daher kann ihn nur ein zodiakaler Bezugsrahmen platzieren: Seine Kartenlinien brauchen die Linienprojektion auf In Zodiaco (oder das geodätische Liniensystem). Wird der Karten-Pin versetzt, wird er in der Horoskopzeichnung für diesen Ort neu berechnet, während die Kartenlinien deinen Radix-Glückspunkt behalten.',
    sect: {
      label: 'Nach Sekte (Tag/Nacht)',
      hint: 'Taggeburten nutzen Aszendent + Mond − Sonne, Nachtgeburten umgekehrt Aszendent + Sonne − Mond. Die traditionelle Konvention.',
    },
    ptolemaic: {
      label: 'Ptolemäisch (fest)',
      hint: 'Aszendent + Mond − Sonne für jedes Horoskop, ob Tag oder Nacht. Die alternative historische Konvention.',
    },
  },
  rulership: {
    hint: 'Welche Herrschertabelle die Würdenliste der Horoskopzeichnung nutzt. „Modern“ ERGÄNZT die drei äußeren, ohne jemanden zu ersetzen: Mars behält Skorpion neben Pluto, und beide stehen im gegenüberliegenden Stier im Exil. „Traditionell“ streicht die Zeilen der äußeren Planeten und ändert sonst nichts.',
    traditional: {
      label: 'Traditionell',
      hint: 'Nur die Tabelle der sieben Planeten – Mars beherrscht Skorpion, Saturn Wassermann, Jupiter Fische. Uranus, Neptun und Pluto beherrschen nichts und haben daher keine Würde.',
    },
    modern: {
      label: 'Modern',
      hint: 'Dieselben sieben, dazu Pluto im Skorpion, Uranus im Wassermann und Neptun in den Fischen. Diese drei Zeichen haben zwei Herrscher, und jede Zeile nennt ihre Epoche.',
    },
  },
  inert: {
    fortuneMundo: 'Ein Los ist ein Punkt auf der Ekliptik ohne Position am Himmel, daher kann In Mundo es nirgends platzieren. Um diese Linie zu sehen, stelle die Projektion auf In Zodiaco (Berechnung).',
    fortuneAdvanced: 'Der Glückspunkt gehört zum erweiterten Modus – schalte diesen ein, um ihn zu nutzen.',
    geodeticSidereal: 'Das geodätische Liniensystem legt den TROPISCHEN Tierkreis auf die Längengrade – also nie siderisch. Stelle „Tropisch“ ein (Erweitert), um es zu nutzen; deine Wahl bleibt erhalten.',
    geodeticHeld: '„Geodätisch“ wird überprüft, während wir kontrollieren, wie es zeichnet – wir stellen es lieber zurück, als eine Karte zu zeichnen, hinter der wir nicht stehen können. Deine Wahl bleibt erhalten und wird nicht gelöscht; schau bald wieder vorbei.',
    skyHeldWhy: 'Auf geodätischen Karten nicht verfügbar, da sie sich nicht mit dem Himmel drehen.',
    skyHeldFix: 'Stelle das Liniensystem unter „Berechnung“ auf „Himmelsbezogen“, um es zu nutzen.',
    skyHeld: 'Auf geodätischen Karten nicht verfügbar, da sie sich nicht mit dem Himmel drehen. Stelle das Liniensystem unter „Berechnung“ auf „Himmelsbezogen“, um es zu nutzen.',
    skyHeldAction: 'Berechnung öffnen',
    skyHeldForNow: 'Auf geodätischen Karten vorerst nicht verfügbar.',
    skyHeldForNowFull: 'Auf geodätischen Karten vorerst nicht verfügbar. Stelle das Liniensystem unter „Berechnung“ auf „Himmelsbezogen“, um es zu nutzen.',
    anglesHeld: 'Auf geodätischen Karten ergeben sich die Achsen eines Ortes aus seinen Koordinaten und bewegen sich daher nicht mit der Zeit.',
    paransHeld: 'Parans werden auf geodätischen Karten nicht angezeigt.',
    paransHeldFull: 'Parans werden auf geodätischen Karten nicht angezeigt. Stelle das Liniensystem unter „Berechnung“ auf „Himmelsbezogen“, um es zu nutzen.',
  },
  nodeType: {
    true: {
      label: 'Wahrer Mondknoten',
      hint: 'Der wahre (oskulierende) Mondknoten folgt der momentanen Mondbahn; pendelt ±~1,5° um den mittleren und kann kurz direktläufig werden (Voreinstellung).',
    },
    mean: {
      label: 'Mittlerer Mondknoten',
      hint: 'Der geglättete Langzeitmittelwert; läuft immer gleichmäßig rückläufig.',
    },
  },
  houseSystem: {
    placidus: {
      label: 'Placidus',
      hint: 'Zeitliche Teilung der Halbbögen (der verbreitete moderne Standard)',
    },
    koch: {
      label: 'Koch',
      hint: 'Halbbogen auf der Geburtsbreite (GOH)',
    },
    regiomontanus: {
      label: 'Regiomontanus',
      hint: 'Gleiche Teilung des Himmelsäquators',
    },
    campanus: {
      label: 'Campanus',
      hint: 'Gleiche Teilung des Ersten Vertikals',
    },
    porphyry: {
      label: 'Porphyrios',
      hint: 'Jeder Quadrant in ekliptikaler Länge gedrittelt',
    },
    alcabitus: {
      label: 'Alcabitius',
      hint: 'Antike Halbbogenteilung auf den Tag- / Nachtbögen',
    },
    meridian: {
      label: 'Meridian',
      hint: 'Gleiche 30°-Bögen des Äquators ab dem MC, über Stundenkreise projiziert; die 1. Hausspitze ist ein Ostpunkt, nicht der Aszendent. In jeder Breite wohldefiniert.',
    },
    morinus: {
      label: 'Morinus',
      hint: 'Gleiche Äquatorbögen, über Kreise durch die Ekliptikpole projiziert; nutzt weder Aszendent noch MC und übersteht daher selbst polare Breiten problemlos.',
    },
    whole: {
      label: 'Ganzzeichen',
      hint: 'Jedes Haus ist ein ganzes Zeichen, ab dem aufsteigenden Zeichen',
    },
    equal: {
      label: 'Äqual',
      hint: '30°-Häuser, ab dem Aszendenten gemessen',
    },
  },
  primaryRate: {
    ptolemy: {
      label: 'Ptolemäus (1°/Jahr)',
      hint: 'Ein Jahr pro Grad.',
    },
    naibod: {
      label: 'Naibod (59′08″/Jahr)',
      hint: '0,985647° pro Jahr, die mittlere Bewegung der Sonne.',
    },
    cardan: {
      label: 'Cardan (59′12″/Jahr)',
      hint: '0,986667° pro Jahr.',
    },
    'kepler-ra': {
      label: 'Tägliche Sonnenbewegung (RA)',
      hint: 'Keplers Schlüssel – die tägliche Bewegung der Radixsonne in Rektaszension × Jahre.',
    },
    'solar-long': {
      label: 'Tägliche Sonnenbewegung (Länge)',
      hint: 'Tägliche Bewegung der Radixsonne in ekliptikaler Länge × Jahre.',
    },
    'placidus-ra': {
      label: 'Wahrer Sonnenbogen (RA)',
      hint: 'Nutzt als Zeitschlüssel die tatsächliche Strecke der progressiven Sonne bis zu diesem Alter statt eines festen Jahresbogens. Da die Sonne übers Jahr verschieden schnell läuft, wächst der Bogen ungleichmäßig – der Schlüssel liegt daher je nach Geburtsjahreszeit etwas vor oder hinter den festen Bögen.',
    },
    user: {
      label: 'Eigener Zeitschlüssel',
      hint: 'Unten eigene Grad pro Jahr eingeben.',
    },
    control: {
      tip: 'Der Zeitschlüssel der Primärdirektionen',
      hint: 'Primärdirektionen bilden die tägliche Drehung nach: Die Achsen des Horoskops werden weitergedreht, während die Himmelskörper ihre Radixpositionen am Himmel behalten. Der Zeitschlüssel gibt an, wie viel Bogen pro Lebensjahr hinzukommt. Die Schulen unterscheiden sich, und die Unterschiede sind real: Im Laufe eines Lebens liegen Ptolemäus und Naibod mehr als ein Jahr auseinander.',
    },
  },
  positioning: {
    'relative-to-natal': {
      label: 'Radixachsen',
      short: 'Radix',
      tip: 'Die eigenen Achsen des Geburtshoroskops',
      hint: 'Hält den Radix-Bezugsrahmen fest, sodass nur die eigene sekundäre Bewegung der Planeten die Linien bewegt. Die tägliche Drehung entfällt. Beantwortet: Wo auf der Erde träfe dieser Transit auf Aszendent, MC, Deszendent oder IC? Die Linien wandern über Wochen und Monate, im Tempo jedes Planeten.',
      returnHintSolar: 'Zeichnet die Planeten der Revolution bezogen auf die Radixachsen. Die Revolutionssonne steht wieder auf dem Grad der Radixsonne, und die Sonne hat keine ekliptikale Breite, daher fallen ihre Linien in beiden Projektionen genau auf die Sonnenlinien der Radix – jedes Jahr an denselben Ort.',
      returnHintLunar: 'Zeichnet die Planeten der Revolution bezogen auf die Radixachsen. Der Revolutionsmond steht wieder auf der Länge des Radixmondes, daher fallen seine Linien In Zodiaco auf die Mondlinien der Radix; In Mundo landen sie nah daran, aber nicht genau, weil sich die Breite des Mondes seit der Geburt verändert hat.',
    },
    'transit-moment': {
      label: 'Transitachsen',
      short: 'Transit',
      returnLabel: 'Revolutionsachsen',
      returnShort: 'Revolution',
      tip: 'Die Achsen des Moments selbst',
      returnTip: 'Die eigenen Achsen des Revolutionshoroskops',
      hint: 'Liest den Himmel im eigenen Bezugsrahmen des Moments; die Linien tragen die primäre Bewegung – alle wandern 15° pro Stunde, einmal am Tag rundum. Jede Linie markiert, wo ihr Himmelskörper in diesem Moment wirklich eckständig ist. Keine Radix beteiligt. Gelesen wird ein Augenblick, keine Jahreszeit.',
      returnHint: 'Ein Revolutionshoroskop ist ein eigener Moment mit eigenen Achsen. Die Karte wird bezogen auf die Achsen der Revolution gezeichnet statt auf die der Radix.',
    },
  },
  arcMethod: {
    'sa-long': {
      label: 'Sonnenbogen – in Länge',
      angles: 'Rückt die Achsen um die Strecke vor, die die progressive Sonne bis zum eigenen Zeitpunkt dieses Overlays zurückgelegt hat, gemessen entlang der Ekliptik.',
      bodies: 'Rückt jeden Himmelskörper um die Strecke vor, die die progressive Sonne dieses Horoskops tatsächlich zurückgelegt hat, gemessen entlang der Ekliptik. Die klassische Methode.',
    },
    'sa-ra': {
      label: 'Sonnenbogen – in Rektaszension',
      angles: 'Rückt die Achsen um die Strecke vor, die die progressive Sonne bis zum eigenen Zeitpunkt dieses Overlays zurückgelegt hat, gemessen entlang des Äquators.',
      bodies: 'Rückt jeden Himmelskörper um die Strecke vor, die die progressive Sonne dieses Horoskops tatsächlich zurückgelegt hat, gemessen entlang des Äquators.',
    },
    'naibod-long': {
      label: 'Naibod, mittlere Rate – in Länge',
      angles: 'Rückt die Achsen mit der mittleren Rate der Sonne über das eigene Intervall dieses Overlays vor, gemessen entlang der Ekliptik.',
      bodies: 'Rückt jeden Himmelskörper mit der durchschnittlichen jährlichen Bewegung der Sonne vor, gemessen entlang der Ekliptik.',
    },
    'naibod-ra': {
      label: 'Naibod, mittlere Rate – in Rektaszension',
      angles: 'Rückt die Achsen mit der mittleren Rate der Sonne über das eigene Intervall dieses Overlays vor, gemessen entlang des Äquators.',
      bodies: 'Rückt jeden Himmelskörper mit der durchschnittlichen jährlichen Bewegung der Sonne vor, gemessen entlang des Äquators.',
    },
    headerAngles: 'Wie weit die Achsen vorrücken',
    headerBodies: 'Wie weit die Himmelskörper vorrücken',
  },
  progAngles: {
    natal: {
      label: 'Radixachsen',
      short: 'Radix',
      tip: 'Die eigenen Achsen des Geburtshoroskops',
      hint: 'Die progressiven Planeten werden bezogen auf die Radixachsen gelesen. Der Bezugsrahmen des Geburtshoroskops bleibt fest, sodass sich nur die Planeten bewegen.',
    },
    progressed: {
      label: 'Progressionsachsen',
      short: 'Progression',
      tip: 'Die eigenen Achsen des progressiven Horoskops',
      hint: 'Das progressive Horoskop hat einen eigenen Moment – einen Tag nach der Geburt je Lebensjahr – also eigene Achsen. Die Karte folgt ihnen statt denen der Radix.',
      hintTertiary: 'Das tertiäre Horoskop hat einen eigenen Moment – einen Tag nach der Geburt je tropischen Monat (27,32 Tage) – also eigene Achsen. Die Karte folgt ihnen, nicht denen der Radix.',
    },
    idle: {
      tip: 'Nicht wirksam',
      hint: 'Die Achsen bleiben auf der Radix, daher wird kein Bogen auf sie angewendet. Die Wahl einer Berechnung hier stellt die Karte auch auf „Progressionsachsen“ um.',
    },
  },
  eclipses: {
    kind: {
      total: 'Total',
      annular: 'Ringförmig',
      hybrid: 'Hybrid',
      partial: 'Partiell',
      penumbral: 'Halbschatten',
    },
    body: {
      solar: 'Solar',
      lunar: 'Lunar',
    },
    details: {
      maximum: 'Maximum',
      maximumValue: '{date} · {time} (UTC)',
      type: 'Typ',
      central: 'zentral',
      nonCentral: 'nicht zentral',
      magnitude: 'Magnitude',
      gamma: 'Gamma',
      saros: 'Saros-Reihe',
      lunation: 'Lunation',
      sunPosition: 'Finsternisgrad',
      sunPositionTip: 'Der Tierkreisgrad der Finsternis – Sonne und Mond treffen sich hier im Zeichen {sign}.',
      moonPositionTip: 'Der Tierkreisgrad des verfinsterten Mondes im Zeichen {sign} – er steht der Sonne gegenüber.',
      hemisphere: 'Hemisphäre',
      north: 'Nördlich',
      south: 'Südlich',
      duration: 'Max. Dauer',
      width: 'Pfadbreite',
      widthValue: '{n} km',
      umbralMag: 'Kernschatten-Magnitude',
      penumbralMag: 'Halbschatten-Magnitude',
      penumbralDur: 'Halbschattenphase',
      partialDur: 'Partielle Phase',
      totalDur: 'Totale Phase',
    },
    contacts: {
      heading: 'Radixkontakte',
      none: 'Keine Kontakte innerhalb von 3° – diese Finsternis zieht still am Horoskop vorbei.',
      aspect: {
        conjunction: 'Konjunktion',
        square: 'Quadrat',
        opposition: 'Opposition',
      },
      asc: 'Aszendent',
      mc: 'Himmelsmitte',
    },
    otherLines: {
      title: 'Übrige Linien',
      hint: 'Leert die Karte per Klick bis auf die Finsternis, damit der Pfad allein steht – solange aus, übersteuert es die anderen Linienschalter. Horoskopzeichnung und Anzeigen bleiben.',
    },
    chartLines: {
      title: 'Finsternishoroskop',
      hint: 'Das Horoskop zum Maximum der Finsternis – der Himmel in genau diesem Augenblick –, als zweiter Ring neben der Radix in die Horoskopzeichnung eingefügt.',
    },
    isoStep: {
      '10': {
        label: '10 %',
        hint: 'Neun Isolinien – ein dichtes Referenzraster.',
      },
      '20': {
        label: '20 %',
        hint: 'Vier Isolinien – ein ausgewogener Mittelweg.',
      },
      '25': {
        label: '25 %',
        hint: 'Drei Isolinien in Viertelschritten (die klassische Konvention für Finsterniskarten).',
      },
    },
  },
  lineType: {
    MC: {
      hint: 'Himmelsmitte (Beruf, Öffentlichkeit)',
    },
    IC: {
      hint: 'Imum Coeli (Zuhause, Wurzeln)',
    },
    ASC: {
      hint: 'Aszendent (Selbst, Identität)',
    },
    DSC: {
      hint: 'Deszendent (Beziehungen)',
    },
    VX: {
      hint: 'Vertex (schicksalhafte Begegnungen); fügt auch Vx zur Horoskopzeichnung hinzu',
    },
    AVX: {
      hint: 'Antivertex (das östliche Ende der Achse); fügt auch Avx zur Horoskopzeichnung hinzu',
    },
  },
} as const;
