// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/synastryHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const synastryHud = {
  title: 'Synastrie',
  chooseComparison: 'Vergleichshoroskop wählen',
  choosePrompt: 'Horoskop zum Vergleichen wählen',
  barToggle: {
    show: 'Synastrie-Optionen anzeigen',
    hide: 'Synastrie-Optionen ausblenden',
  },
  method: {
    label: 'Typ',
    davison: {
      label: 'Davison',
      hint: 'Zeitlicher und räumlicher Mittelpunkt der beiden Horoskope, als echtes Horoskop berechnet.',
    },
    composite: {
      label: 'Composit-Halbsummen',
      hint: 'Jeder Planet und jede Achse auf der Halbsumme der beiden Horoskope, jeder Planet mit echter Breite und Deklination. Der Bezugsrahmen der Karte folgt der Composit-Himmelsmitte.',
    },
  },
  generate: {
    label: 'Erstellen',
    hint: 'Horoskop erstellen, aktivieren und das Vergleichshoroskop aus der Synastrie entfernen.',
    needPartner: 'Wähle zuerst oben ein Vergleichshoroskop.',
    compositeParent: 'Ein Composit-Horoskop lässt sich nicht erneut kombinieren; wähle zwei normale Horoskope.',
  },
} as const;
