// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/timeline.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const timeline = {
  nubMode: {
    transits: 'Transite',
    progressed: 'Sek. Progression',
    'tertiary-progressed': 'Tert. Progression',
    'solar-arc': 'Sonnenbogen',
    'primary-directions': 'Primär',
    cyclo: 'CCG',
  },
  nubFallback: 'Overlay',
  barToggle: {
    show: 'Zeitleiste einblenden',
    hide: 'Zeitleiste ausblenden',
    hint: 'Datumsregler + Wiedergabesteuerung. Die Lasche bleibt in jedem Fall.',
  },
  drawer: {
    show: 'Anzeigeschalter einblenden',
    hide: 'Anzeigeschalter ausblenden',
  },
  cyclo: {
    label: 'Mischung',
    spName: 'Progressive persönliche Planeten',
    spTip: 'Sp – sekundär progressiv',
    spHint: 'Sonne, Mond, Merkur, Venus und Mars stehen sekundär progressiv: Bei einem Tag pro Jahr bleiben sie neben den äußeren Himmelskörpern lesbar. Ihre Linien tragen das Kennzeichen Sp.',
    trName: 'Transitierende äußere Himmelskörper',
    trTip: 'Tr – transitierend',
    trHint: 'Alles ab Jupiter nach außen – dazu die Mondknoten, Lilith, Chiron und die Asteroiden – steht an seiner tatsächlichen Transitposition. Ihre Linien tragen das Kennzeichen Tr.',
  },
  positioning: {
    groupAria: 'Overlay-Bezugsrahmen',
    lockedNoTime: 'Geburtszeit unbekannt – es gibt keinen Radix-Bezugsrahmen, der sich halten ließe, daher kann die Karte nur den Himmel des Moments zeigen.',
    heldForReturn: 'Zurückgestellt, solange die Karte eine Revolution zeigt – ein Revolutionshoroskop ist nur in seinem eigenen Bezugsrahmen es selbst. Mit dieser Wahl endet die Zurückstellung, und die Karte kehrt in diesen Bezugsrahmen zurück.',
  },
  units: {
    minute: 'Minute',
    hour: 'Stunde',
    day: 'Tag',
    week: 'Woche',
    month: 'Monat',
    year: 'Jahr',
  },
  unitsLower: {
    minute: 'Minute',
    hour: 'Stunde',
    day: 'Tag',
    week: 'Woche',
    month: 'Monat',
    year: 'Jahr',
  },
  minorLabel: {
    minute: '1 min',
    hour: '10 min',
    day: '6 Stunden',
    week: '1 Tag',
    month: '5 Tage',
    year: '1 Monat',
  },
  stepWords: {
    minute: '{n, plural, one {Minute} other {Minuten}}',
    hour: '{n, plural, one {Stunde} other {Stunden}}',
    day: '{n, plural, one {Tag} other {Tage}}',
    week: '{n, plural, one {Woche} other {Wochen}}',
    month: '{n, plural, one {Monat} other {Monate}}',
    year: '{n, plural, one {Jahr} other {Jahre}}',
  },
  stepSymbol: {
    minute: '{n, plural, one {min} other {min}}',
    hour: '{n, plural, one {h} other {h}}',
    day: '{n, plural, one {T} other {T}}',
    month: '{n, plural, one {Mon.} other {Mon.}}',
  },
  transport: {
    stepBack: '{count} {unit} zurück',
    stepForward: '{count} {unit} vorwärts',
    stepBackAria: 'Schritt zurück',
    stepForwardAria: 'Schritt vorwärts',
    play: 'Abspielen',
    pause: 'Pausieren',
    stepAmountIn: {
      minute: 'Schrittweite, in Minuten',
      hour: 'Schrittweite, in Stunden',
      day: 'Schrittweite, in Tagen',
      month: 'Schrittweite, in Monaten',
    },
    stepAmountInAria: {
      minute: 'Schrittweite in Minuten',
      hour: 'Schrittweite in Stunden',
      day: 'Schrittweite in Tagen',
      month: 'Schrittweite in Monaten',
    },
  },
  ruler: {
    aria: 'Datum durchlaufen',
  },
  now: {
    label: 'Jetzt',
    tip: 'Auf den aktuellen Moment setzen',
  },
  returns: {
    label: 'Revolutionen',
    reframes: 'Übernimmt für die Karte vorübergehend den eigenen Bezugsrahmen des Revolutionsmoments. Im Radix-Bezugsrahmen ist der wiederkehrende Himmelskörper an den Grad seiner Geburtsstellung gebunden, sodass sich seine Linien von einer Revolution zur nächsten nie bewegen würden. Dein Bezugsrahmen ist zurückgestellt, nicht gelöscht, und kehrt zurück, wenn du die Revolution verlässt.',
    chip: {
      solar: 'Solarhoroskop',
      lunar: 'Lunarhoroskop',
      tip: 'Die Karte zeigt eine Revolution',
      hint: 'Solange die Karte eine Revolution zeigt, wird der Overlay-Bezugsrahmen vorübergehend übernommen, denn ein Revolutionshoroskop hat eigene Achsen. Der vorherige Bezugsrahmen bleibt darunter zurückgestellt, auch beim Wechsel per Pfeil zwischen Revolutionen, und kehrt beim Verlassen zurück.',
      clear: 'Revolution verlassen',
      clearHint: 'Bringt den Overlay-Bezugsrahmen dorthin zurück, wo er war. Das Datum bleibt, wo es ist.',
      clearAria: 'Revolution verlassen und Overlay-Bezugsrahmen wiederherstellen',
    },
    solar: {
      name: 'Solar',
      chartName: 'Solarhoroskop',
      snap: 'Nächstgelegenes Solarhoroskop',
      snapAria: 'Zum nächstgelegenen Solarhoroskop springen',
      prev: 'Vorheriges Solarhoroskop',
      prevAria: 'Vorheriges Solarhoroskop',
      next: 'Nächstes Solarhoroskop',
      nextAria: 'Nächstes Solarhoroskop',
    },
    lunar: {
      name: 'Lunar',
      chartName: 'Lunarhoroskop',
      snap: 'Nächstgelegenes Lunarhoroskop',
      snapAria: 'Zum nächstgelegenen Lunarhoroskop springen',
      prev: 'Vorheriges Lunarhoroskop',
      prevAria: 'Vorheriges Lunarhoroskop',
      next: 'Nächstes Lunarhoroskop',
      nextAria: 'Nächstes Lunarhoroskop',
    },
  },
  scale: {
    label: 'Maßstab',
  },
  rate: {
    label: 'Zeitschlüssel',
  },
  dateField: {
    tipChartZone: 'Transit-/Progressionsmoment, in der Zeitzone des Horoskops',
    tipChartZonePlace: 'Transit-/Progressionsmoment, nach Ortszeit {place} – Geburtsort des Horoskops, nicht unbedingt dein Aufenthaltsort',
    tipUtc: 'Transit-/Progressionsmoment, in UTC',
  },
  datePicker: {
    open: 'Datum & Uhrzeit bearbeiten',
    title: 'Datum & Uhrzeit einstellen',
    scrollKey: 'Scrollen',
    scrollHint: 'zum Erhöhen oder Verringern',
    apply: 'Übernehmen',
    yearRange: 'Diese Auswahl reicht von {min} bis {max} – ein Jahr außerhalb springt auf das nächstgelegene Ende.',
  },
  labelFull: {
    transits: 'Transite · {datetime} (UTC)',
    progressed: 'Sek. Progression · Alter {years}',
    'tertiary-progressed': 'Tert. Progression · Alter {years}',
    'solar-arc': 'Sonnenbogen · {deg}°',
    'primary-directions': 'Primärdirektionen · {deg}°',
    cyclo: 'Zyklo·karto·grafie · {datetime} (UTC)',
    synastry: 'Synastrie · {partner}',
    eclipses: 'Finsternis · {datetime} (UTC)',
  },
  measure: {
    progressedAge: 'Alter {years}',
  },
} as const;
