// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/topNav.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const topNav = {
  overlay: {
    menuLabel: 'Overlay',
    none: {
      label: 'Keines',
      hint: 'Nur die Radix, ohne angewandte Zeittechnik.',
    },
    blocked: {
      composite: 'Ein Composit ist ein Halbsummenhoroskop, kein Moment – es gibt keinen Geburtsaugenblick, den diese Technik fortschreiben könnte. Wechsle zu einem Horoskop einer einzelnen Person, um sie zu nutzen.',
      'no-time': 'Die Geburtszeit dieses Horoskops ist unbekannt, daher gibt es keinen exakten Radixmoment zum Fortschreiben – eine Technik, die darauf aufbaut, würde ihn stillschweigend erfinden. Ergänze eine Geburtszeit, um dies zu nutzen.',
      davison: 'Dieses Horoskop ist bereits ein Horoskop für zwei Personen, es gibt also niemanden mehr hinzuzufügen. Wechsle zu einem Horoskop einer einzelnen Person, um eine Synastrie zu erstellen.',
    },
    modes: {
      transits: {
        label: 'Transite',
        desc: 'Wo die Planeten gerade stehen, über deiner Radix.',
      },
      progressed: {
        label: 'Sek. Progression',
        tipTitle: 'Sekundärprogressionen',
        desc: 'Sekundärprogressionen: eine symbolische Entfaltung nach dem Prinzip ein Tag für ein Jahr.',
      },
      'tertiary-progressed': {
        label: 'Tert. Progression',
        tipTitle: 'Tertiärprogressionen',
        desc: 'Tertiärprogressionen: ein Tag für einen tropischen Monat (27,32 Tage), ein feinerer Zeiger fürs Timing.',
      },
      'solar-arc': {
        label: 'Sonnenbogen',
        desc: 'Jeder Punkt, vorgerückt um den Bogen der Sonne von einem Grad pro Jahr.',
      },
      'primary-directions': {
        label: 'Primärdirektionen',
        desc: 'Eine antike Timing-Methode, angetrieben von der Drehung des Himmels.',
      },
      cyclo: {
        label: 'Zyklokartografie',
        tipTitle: 'Zyklokartografie (CCG)',
        desc: 'Jim Lewis’ Hybrid: sekundärprogressive persönliche Planeten mit den transitierenden Planeten ab Jupiter, auf einer Karte.',
      },
      synastry: {
        label: 'Synastrie',
        desc: 'Das Horoskop einer anderen Person über deinem, für Beziehungen.',
      },
      eclipses: {
        label: 'Finsternisse',
        desc: 'Finsternispfade und Isolinien der Magnitude bei Sonnenfinsternissen, dazu wo eine Mondfinsternis sichtbar ist – auf der ganzen Karte.',
      },
    },
  },
  status: {
    natal: 'RADIX',
    hover: 'CURSOR',
    pinned: 'ANGEPINNT',
    'natal-pinned': 'RADIX-PIN',
  },
  sidebarToggle: {
    showAria: 'Horoskop-Seitenleiste anzeigen',
    hideAria: 'Horoskop-Seitenleiste ausblenden',
    showTip: 'Horoskop in der Seitenleiste anzeigen',
    hideTip: 'Seitenleiste ausblenden',
  },
  pin: {
    centerTip: 'Karte auf den Pin zentrieren',
    pinNatalTip: 'Pin auf den Radixort setzen',
    controlsTip: 'Steuerung des Karten-Pins',
  },
  tools: {
    menuLabel: 'Werkzeuge',
    measure: 'Messen der Entfernung',
    measureItem: 'Messen',
    measureHint: 'Auf der Karte klicken und ziehen, um die Großkreisentfernung zu messen',
    toolbarHint: 'Auf der Karte {click} und {drag}, um zu messen{rightExit}',
    measureKm: '{n} km',
    measureMi: '{n} mi',
    snap: 'Einrasten',
    snapTip: 'Endpunkt an Horoskoplinien einrasten (oder Umschalt gedrückt halten)',
    slideItem: 'Verschieben',
    slideHint: 'Die Welt unter den festen Radixlinien verschieben – lässt die Zeit vorlaufen, um zu zeigen, wie sich Parans im Tagesverlauf aufbauen. Funktioniert in Flach- und Globusansicht.',
    slideUnavailable: 'Verschieben braucht die gezeichneten Radixlinien. Nicht verfügbar, solange „Radixlinien“ aus ist (Erweitert ▸ Linien, Umschalt+N), „Übrige Linien“ sie ausgeblendet hat oder ein Overlay an die Stelle des Horoskops tritt.',
    slideToolbarHint: '{pan}, um die Welt unter den festen Linien zu verschieben',
    slideNudgeBack1h: 'Eine Stunde zurück',
    slideNudgeBack4m: 'Vier Minuten zurück (≈ 1° Drehung)',
    slideNudgeFwd4m: 'Vier Minuten vor (≈ 1° Drehung)',
    slideNudgeFwd1h: 'Eine Stunde vor',
    slideReset: 'Zum Radixhimmel zurückkehren',
    slidePrevEvent: 'Zum vorigen Ereignis am aktiven Punkt springen: Aufgang, Kulmination, Untergang',
    slideNextEvent: 'Zum nächsten Ereignis am aktiven Punkt springen: Aufgang, Kulmination, Untergang',
    slideElapsedTip: 'Vom Horoskopmoment aus verschobene Zeit',
    slideClockTip: 'Uhrzeit und Datum am Geburtsort, in der Zeitzone des Horoskops',
    slideAngleTip: 'Drehung um den Pol',
    captureItem: 'Aufnahme',
    captureHint: 'Die Karte einrahmen und als PNG exportieren – Seitenverhältnis wählen, Inhalte festlegen, dann herunterladen oder kopieren.',
    captureToolbarHint: '{pan} und {zoom}, um das Bild im Rahmen zu gestalten{escExit}',
    hintKey: {
      click: 'Klicken',
      tap: 'Tippen',
      doubleClick: 'Doppelt {icon} klicken',
      doubleTap: 'Doppelt {icon} tippen',
      drag: 'Ziehen',
      pan: 'Bewegen',
      zoom: 'Zoomen',
      esc: 'Esc',
      rightClick: 'Rechts {icon} klicken',
      toExit: 'zum Beenden',
    },
  },
  view: {
    menuLabel: 'Ansicht',
    coordinates: 'Koordinaten',
    coordinatesHint: 'Eine Live-Anzeige von Ort, Koordinaten und Achsen des Relokationshoroskops für den aktiven Punkt.',
    minimap: 'Minikarte',
    minimapHint: 'Die Horoskopzeichnung der Radix, klein in der Ecke, während du die Karte erkundest.',
    settings: 'Einstellungen',
    settingsHint: 'Designs, Häusersysteme, Tierkreis und wie Horoskop und Karte gezeichnet werden.',
    teleport: 'Teleport',
    teleportHint: 'Einen beliebigen Ort suchen und mit der Karte direkt dorthin fliegen.',
    skyTimes: 'Himmelszeiten',
    skyTimesHint: 'Die täglichen Zeiten von Aufgang, Kulmination und Untergang am aktiven Punkt, im Band am unteren Rand.',
    localSpace: 'Local Space',
    localSpaceHint: 'Richtungslinien vom Ursprung des Horoskops zu jedem Planeten – dein Local-Space-Kompass.',
    info: 'Info',
    infoHint: 'Ein Chip in der Ecke, der die aktiven Systeme des Horoskops zusammenfasst – Linien-Bezugsrahmen, Häuser und Tierkreis.',
    guides: 'Anleitungen',
    guidesHint: 'Die Einführungsanleitungen erneut ansehen – als Glossar der Bedienelemente der Karte.',
  },
} as const;
