// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Deutsch for ../en/wheel.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../de.lock.json). Keys, order and layout are rewritten on every run.
export const wheel = {
  house: '{number, selectordinal, other {#.}} Haus',
  signMeanings: {
    aries: 'Feuer · Kardinal · Initiative',
    taurus: 'Erde · Fix · Stabilität',
    gemini: 'Luft · Veränderlich · Neugier',
    cancer: 'Wasser · Kardinal · Fürsorge',
    leo: 'Feuer · Fix · Selbstausdruck',
    virgo: 'Erde · Veränderlich · Präzision',
    libra: 'Luft · Kardinal · Ausgleich',
    scorpio: 'Wasser · Fix · Intensität',
    sagittarius: 'Feuer · Veränderlich · Abenteuer',
    capricorn: 'Erde · Kardinal · Ehrgeiz',
    aquarius: 'Luft · Fix · Innovation',
    pisces: 'Wasser · Veränderlich · Fantasie',
  },
  houseMeanings: {
    h1: 'Selbst · Identität · erster Eindruck',
    h2: 'Geld · Besitz · Selbstwert',
    h3: 'Kommunikation · Geschwister · Lernen',
    h4: 'Zuhause · Familie · Wurzeln',
    h5: 'Kreativität · Romantik · Kinder',
    h6: 'Arbeit · Gesundheit · Alltag',
    h7: 'Partnerschaft · Ehe · das „Gegenüber“',
    h8: 'Intimität · gemeinsame Ressourcen · Wiedergeburt',
    h9: 'Reisen · Philosophie · höhere Bildung',
    h10: 'Beruf · Ansehen · öffentliches Leben',
    h11: 'Freunde · Gemeinschaft · Hoffnungen',
    h12: 'Alleinsein · das Verborgene · Spiritualität',
  },
  tip: {
    longitude: 'Länge {lon}',
    latitude: 'Breite {lat}',
    minorCluster: '{n, plural, one {# Kleinkörper} other {# Kleinkörper}}',
    minorLine: '{name} {lon}',
    minorMore: 'Weitere: +{n}',
    overlayMinor: '{name} · {chart}',
    overlayMinorCluster: '{chart}: {n, plural, one {# Kleinkörper} other {# Kleinkörper}}',
    minorLineOverlay: '{name} {lon} · {chart}',
    fortuneGeodetic: 'Aus dem geodätischen Aszendenten',
    fortuneGeodeticDay: 'Aus dem geodätischen Aszendenten, als Taggeburt. Bei einer Nachtgeburt würde er sich am Aszendenten spiegeln',
    fortuneGeodeticNight: 'Aus dem geodätischen Aszendenten, als Nachtgeburt. Bei einer Taggeburt würde er sich am Aszendenten spiegeln',
    rangeNote: 'Geburtszeit unbekannt: irgendwo in dieser Spanne am Tag der Geburt',
  },
  planetMeanings: {
    Sun: 'Identität · Vitalität · Ego',
    Moon: 'Gefühle · Instinkt · Bedürfnisse',
    Mercury: 'Verstand · Kommunikation',
    Venus: 'Liebe · Schönheit · Werte',
    Mars: 'Antrieb · Energie · Handeln',
    Jupiter: 'Wachstum · Glück · Expansion',
    Saturn: 'Disziplin · Struktur · Grenzen',
    Uranus: 'Wandel · Freiheit · Einsicht',
    Neptune: 'Träume · Intuition · Spiritualität',
    Pluto: 'Macht · Transformation',
    NorthNode: 'Weg der Seele · Wachstum',
    SouthNode: 'Vergangenheit · angeborene Gaben',
    Lilith: 'Schatten · roher Instinkt',
    Chiron: 'Der verwundete Heiler',
    Ceres: 'Fürsorge · Zyklen',
    Pallas: 'Weisheit · Strategie',
    Juno: 'Verbindlichkeit · Partnerschaft',
    Vesta: 'Fokus · Hingabe',
    Fortune: 'Glück · Vitalität · Leichtigkeit',
  },
  angles: {
    As: {
      title: 'Aszendent',
      sub: 'Aufsteigendes Zeichen, das Selbst & der erste Eindruck',
    },
    Ds: {
      title: 'Deszendent',
      sub: 'Beziehungen & das „Gegenüber“',
    },
    Mc: {
      title: 'Himmelsmitte (Medium Coeli)',
      sub: 'Beruf, Ansehen & öffentliches Leben',
    },
    Ic: {
      title: 'Imum Coeli',
      sub: 'Zuhause, Wurzeln & Privatleben',
    },
    Vx: {
      title: 'Vertex',
      sub: 'Schicksalhafte Begegnungen & Wendepunkte; der Westpunkt des Ersten Vertikals',
    },
    Avx: {
      title: 'Antivertex',
      sub: 'Das östliche Ende der Vertex-Achse, gegenüber dem Vertex',
    },
  },
  motion: {
    retrograde: 'Rückläufig',
    stationary: 'Stationär',
  },
} as const;
