// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/aspectLinesHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const aspectLinesHud = {
  title: 'Аспекты',
  closeAria: 'Закрыть «Аспекты»',
  closeHint: 'Закрыть это окно. Линии останутся включены — выключите их в разделе Настройки ▸ Расширенные ▸ Линии.',
  filters: {
    label: 'Фильтры',
  },
  harmonious: {
    title: 'Гармоничные',
    hint: 'Линии секстилей и тринов. Одно семейство по геометрии: каждая линия читается как секстиль от одного конца своей оси и как трин от другого.',
  },
  challenging: {
    title: 'Напряжённые',
    hint: 'Линии квадратов — квадрат к одному концу оси является квадратом и к другому, поэтому это семейство стоит особняком.',
  },
  mcAxis: {
    title: 'Ось Середины неба',
    hint: 'Линии аспектов к MC (каждую можно читать и от IC).',
  },
  ascAxis: {
    title: 'Ось горизонта',
    hint: 'Линии аспектов к Асценденту (каждую можно читать и от Десцендента).',
  },
  orbs: {
    label: 'Орбисы аспектов',
    infoTitle: 'Орбисы аспектов',
    infoHint: 'Максимальное отклонение от точного аспекта (в градусах) в круге карты и списках аспектов. Линии аспектов на карте мира отмечают точный угол и орбиса не имеют.',
  },
} as const;
