// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/chartWheel.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const chartWheel = {
  resizeLabel: 'Изменить размер круга',
  shrink: 'Уменьшить круг',
  enlarge: 'Увеличить круг',
  openSidebar: 'Открыть полный круг карты',
  openSidebarHint: 'Крупный круг карты с аспектами и таблицей планет — в боковой панели.',
  openSidebarLabel: 'Показать боковую панель карты',
  placeholder: 'Карта не выбрана',
  noChart: 'НЕТ КАРТЫ (CCG)',
} as const;
