// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/chartManager.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const chartManager = {
  dialogLabel: 'Карты',
  title: 'Мои карты',
  comparisonTitle: 'Синастрия: {name}',
  comparisonLabel: 'Синастрия',
  searchPlaceholder: 'Поиск по имени или месту…',
  searchLabel: 'Поиск карт',
  clearSearch: 'Очистить поиск',
  filter: {
    label: 'Фильтр по тегу',
    all: 'Все',
    starred: 'Избранное',
    space: 'Космос',
    unknown: 'Неизвестно',
    shared: 'По ссылке',
  },
  folders: {
    new: 'Новая папка',
    newChild: 'Новая вложенная папка',
    rename: 'Переименовать папку',
    remove: 'Удалить',
    moveTo: 'Переместить в',
    unfiled: 'Без папки',
    nameLabel: 'Название папки',
    namePlaceholder: 'Название папки',
  },
  discreet: {
    hide: 'Включить «Режим приватности»',
    show: 'Выключить «Режим приватности»',
  },
  empty: 'Сохранённых карт пока нет.',
  noMatches: 'Нет подходящих карт.',
  addQuery: 'Добавить «{name}»',
  editingHeader: 'Правка: {name}',
  saveChanges: 'Сохранить изменения',
  addChart: 'Добавить карту',
} as const;
