// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/common.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const common = {
  close: 'Закрыть',
  cancel: 'Отмена',
  edit: 'Изменить',
  delete: 'Удалить',
  keep: 'Оставить',
  locationFallbackOcean: 'Океан',
  tzWarning: '⚠ Часовой пояс до 1970 года вне США/ЕС: сверьте летнее время по атласу',
  timeUnknownBanner: 'Время рождения неизвестно',
  provisionalTimeBanner: '⚠ Пробуется {time} — предварительно, не сохранено',
  locked: {
    feature: '{feature} — функция тарифа {tier}.',
    featureAnyTier: '{feature} не входит в ваш тариф.',
  },
  cardinal: {
    north: 'С',
    south: 'Ю',
    east: 'В',
    west: 'З',
  },
  hud: {
    dragToMove: 'Перетащите для перемещения',
    dockKey: 'Двойной',
    dockHint: 'для закрепления · встаёт по центру',
    recentreHint: 'для центрирования',
    collapse: 'Свернуть панель',
    expand: 'Развернуть панель',
    collapseHint: 'Показать или скрыть элементы управления.',
    closeNamed: 'Закрыть: {name}',
  },
} as const;
