// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/creditsModal.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const creditsModal = {
  title: 'Авторство и лицензии',
  thanks: {
    tip: 'Особая благодарность',
    hint: 'Посмотреть благодарности',
    title: 'Особая благодарность',
    leadRole: 'Астролог, стоящий за AstroLina',
    leadBody: 'Это приложение начиналось как её практика и по-прежнему ей подчиняется. Методы, которым оно следует, правила, которых придерживается, и суждение за каждой линией, которую оно рисует, — её. Она объясняла их терпеливо, нередко не один раз, пока программа не сравнялась с ремеслом.',
    othersHeading: 'Благодарим также',
    body: 'Два профессиональных астролога отдали этому проекту своё время, свои знания и немало терпения: отвечали на вопросы, проверяли правила и помогали молодому инструменту встать на ноги. Без них он был бы куда скромнее.',
    role: 'Профессиональный астролог',
  },
  intro: 'В основе AstroLina — открытые данные и программное обеспечение с открытым исходным кодом. Полные тексты лицензий доступны в репозитории проекта.',
  notice: {
    lead: 'Мы только начинаем и будем рады вашей помощи.',
    body: 'Астрономическая основа надёжна: Swiss Ephemeris, данные JPL, сверка с сервисом NASA Horizons с расхождением намного меньше угловой секунды. Приложение вокруг неё — первая версия, и оно умеет так много, что до запуска мы не могли проверить каждый уголок. Поэтому, если линия выглядит неверной, число — странным или что-то просто не делает того, о чём вы просили, пожалуйста, сообщите нам: каждое сообщение читает человек, и мы намерены сделать этот инструмент таким, на который можно положиться.',
    report: 'Сообщить о проблеме.',
  },
  groups: {
    astrolina: 'AstroLina',
    mapsPlaces: 'Карты и места',
    astronomy: 'Астрономия',
    typeSoftware: 'Шрифты и программы',
  },
  notes: {
    astrolina: '© 2026 AstroLina. Свободное программное обеспечение с открытым исходным кодом по лицензии GNU Affero General Public License v3.0.',
    sourceCode: 'Полный исходный код, доступный в соответствии с AGPL. Будем рады вашему вкладу.',
    openstreetmap: 'Данные базовой карты (указаны также на самой карте).',
    openfreemap: 'Бесплатные векторные тайлы, шрифты подписей и спрайты.',
    mapStyles: 'MapTiler Basic, OSM Bright, Dark Matter, Positron и Fiord Color, некоторые — в адаптированном виде. © MapTiler.com и участники OpenMapTiles; © Mapbox; © CartoDB.',
    geonames: 'Офлайн-поиск по названиям мест и поиск городов.',
    photon: 'Онлайн-поиск мест и адресов; данные © участники OpenStreetMap.',
    swisseph: 'Положения планет (JPL DE441). © Astrodienst AG, через @swisseph/browser.',
    nasaEclipse: 'Каталоги солнечных и лунных затмений (даты, типы, саросы). Прогнозы затмений: Fred Espenak и Jean Meeus (NASA/GSFC).',
    jplSbdb: 'Орбитальные классы, на которых основаны теги малых планет.',
    noto: 'Астрологические символы. © 2022 The Noto Project Authors.',
    maplibre: 'Интерактивная отрисовка карты.',
    rtlText: 'Подписи на карте для письма справа налево: соединение арабских букв, арабский и иврит в порядке чтения. © 2017 Mapbox.',
    icu: 'Код формирования глифов и двунаправленного текста в плагине подписей справа налево. © Unicode, Inc.',
    other: 'А также другие библиотеки под лицензией MIT, перечисленные в репозитории проекта.',
  },
  footer: ' · Астрокартографические расчёты и дизайн интерфейса — собственные разработки AstroLina; эфемериды и картографические данные, на которых они основаны, указаны выше.',
} as const;
