// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/eclipseHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const eclipseHud = {
  title: 'Затмения',
  choose: 'Выбрать затмение',
  prev: 'Предыдущее затмение',
  next: 'Следующее затмение',
  locate: 'Перелететь к затмению',
  all: 'Все',
  searchPlaceholder: 'Поиск по году, типу или саросу…',
  noMatches: 'Подходящих затмений нет.',
  saros: 'Сарос {n}',
  barToggle: {
    show: 'Показать детали затмения',
    hide: 'Скрыть детали затмения',
  },
} as const;
