// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/localSpaceHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const localSpaceHud = {
  title: 'Локальное пространство',
  closeAria: 'Закрыть «Локальное пространство»',
  closeHint: 'Выключить вид локального пространства.',
  lsOrigin: {
    pin: 'От метки',
    pinHint: 'Локальное пространство релокации: линии расходятся от активной метки (от места рождения, если ничего не отмечено).',
    birthplace: 'Место рождения',
    birthplaceHint: 'Линии остаются привязаны к месту рождения, даже когда поставлена метка.',
    home: 'Дом',
    homeHint: 'Проводить азимуты от места, где сейчас живёт человек этой карты, — укажите или измените его прямо здесь. Пока место жительства не указано, берётся место рождения.',
    homeUnset: 'Для этой карты не указано место жительства — азимуты расходятся от места рождения, пока вы его не укажете.',
  },
  hideInbound: {
    title: 'Входящие линии',
    hint: 'Входящее продолжение каждой линии локального пространства — пунктирная половина, направленная к антиподу тела, напротив его исходящего (сплошного) азимута. Выключите, чтобы оставить только исходящие половины.',
  },
  hideDegrees: {
    title: 'Градусы',
    hint: 'Азимут на ярлыке каждой исходящей линии, в градусах и минутах. Если выключить, на ярлыках останутся только LS и символ.',
  },
  hideCompass: {
    title: 'Компас',
    hint: 'Компасный круг местного горизонта, который проявляется в исходной точке, когда вы приближаете карту.',
  },
  flyToOrigin: {
    title: 'К исходной точке',
    hint: 'Опуститься к местному горизонту: перенести камеру к исходной точке, от которой расходятся линии.',
  },
} as const;
