// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/map.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const map = {
  ctrl: {
    zoomIn: 'Приблизить',
    zoomOut: 'Отдалить',
    resetBearing: 'Сбросить поворот и наклон',
  },
  pin: {
    natal: 'Натальное место рождения (правый клик — удалить)',
    custom: 'Отмеченное место (правый клик — удалить)',
    home: 'Дом — место, где сейчас живёт эта карта (правый клик — удалить метку)',
  },
  home: {
    tip: 'Дом',
    hint: 'Нажмите, чтобы прочитать карту для этого места',
  },
  flyToZenith: 'Перелететь к зениту: {prefix}{planet}',
  flyToAspectPoint: 'Перелететь в точку, где в зените градус аспекта ({aspect}) планеты {planet} (нажмите ещё раз, чтобы вернуться)',
  flyToMidpoint: 'Перелететь в точку, где в зените полусумма {planetA}/{planetB} (нажмите ещё раз, чтобы вернуться)',
  aspectNames: {
    sextile: 'секстиль',
    square: 'квадрат',
    trine: 'трин',
  },
  flyToParan: 'Перелететь к точке пересечения этого парана (нажмите ещё раз, чтобы вернуться)',
  flyToLocalSpaceOrigin: 'Перелететь к исходной точке локального пространства (к метке)',
  ecliptic: 'Эклиптика',
  polarNote: 'Полярная зона: за вершиной этой линии восход и заход меняются местами.',
  eclipse: {
    central: 'Центральная линия',
    pathEdge: 'Граница центральной полосы',
    isoline: 'Максимум затмения: {pct}',
    outerLimit: 'Граница видимости — внутри этой линии затмение видно хоть частично',
    horizon: 'Линия восхода/захода Луны в {phase}',
    localMax: 'Солнце здесь закрыто на {pct} в {time} (UTC)',
    lunarAllVisible: 'Отсюда видно всё затмение',
    lunarPartView: 'Отсюда видна часть затмения (контактов: {n} из {total})',
  },
  eclipseCard: {
    notVisible: 'Отсюда затмение не видно',
    utc: 'UTC',
    c1: 'Начало частной фазы',
    c2: 'Начало полной фазы',
    c2Annular: 'Начало кольца',
    max: 'Максимум',
    c3: 'Конец полной фазы',
    c3Annular: 'Конец кольца',
    c4: 'Конец частной фазы',
    atSunrise: 'на восходе',
    atSunset: 'на закате',
    maxValue: 'Величина {mag} · покрытие {obsc}',
    duration: 'Длительность',
    phase: {
      P1: 'Начало полутеневой фазы',
      U1: 'Начало частной фазы',
      U2: 'Начало полной фазы',
      max: 'Максимум',
      U3: 'Конец полной фазы',
      U4: 'Конец частной фазы',
      P4: 'Конец полутеневой фазы',
    },
    belowHorizon: 'Луна под горизонтом',
    moonrise: 'Восход Луны',
    moonset: 'Заход Луны',
  },
  lineCard: {
    distance: '{label} {km} км (в милях: {mi})',
  },
  zenithTitle: 'Зенит: {planet}',
  zenithSub: 'где {planet} находится прямо над головой',
  nadirTitle: 'Надир: {planet}',
  nadirSub: 'где {planet} находится прямо под ногами',
  geoReadout: {
    place: '{place} GE',
    coords: '{lat} {lng} GE',
    as: 'AS',
    mc: 'MC',
  },
  geoLegend: {
    aria: 'Легенда заливки зон',
    isolate: 'Показать только зоны: {group}',
    clear: 'Показать все зоны',
  },
  zoomOutToWide: 'Отдалить до общего вида',
  zoomOut: 'Отдалить',
  webgl: {
    unsupportedTitle: 'Для этой карты нужен WebGL',
    unsupportedBody: 'Ваш браузер не предоставляет этой странице графический контекст WebGL, поэтому карту нельзя отрисовать.',
    tipsHeading: 'Что можно попробовать:',
    tipAccel: 'Включите аппаратное ускорение в настройках браузера, затем обновите страницу.',
    tipShield: 'Разрешите WebGL / canvas для этого сайта, если у вас включена защита от фингерпринтинга или защита приватности.',
    tipBrowser: 'Или откройте AstroLina в другом современном браузере.',
    lostTitle: 'Карта потеряла графический контекст',
    lostBody: 'Такое бывает, когда на устройстве мало графической памяти. Часто всё восстанавливается само — если нет, обновите страницу.',
    reload: 'Обновить страницу',
  },
} as const;
