// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/missions.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const missions = {
  guideTitle: 'Задания',
  title: 'Руководство',
  close: 'Закрыть',
  skipTip: 'Пропустить это руководство',
  ok: 'Понятно',
  okLocked: 'Выполните все задания, чтобы продолжить',
  dontShowAgain: 'Больше не показывать',
  prevGuide: 'Предыдущее руководство',
  nextGuide: 'Следующее руководство',
  guidePosition: 'Руководство {current} из {total}',
  gesture: {
    double: 'Двойной',
    right: 'Правый',
    hold: 'Удержание',
    shift: 'Shift',
    drag: 'Перетаскивание',
    click: 'Клик',
    tap: 'Касание',
    doubleTap: 'Двойное касание',
    longPress: 'Долгое нажатие',
    touchDrag: 'Касание и перетаскивание',
    twoFinger: 'Перетаскивание двумя пальцами',
    pinch: 'Щипок',
    snap: 'Привязка',
  },
  pill: {
    double: 'Двойной {icon} клик',
    right: 'Правый {icon} клик',
    hold: 'Удержание {icon} и перетаскивание',
    shiftDrag: 'Shift {icon} перетаскивание',
    rightDrag: 'Перетаскивание {icon} правой кнопкой',
    tapSnap: 'Касание {icon} Привязка',
    holdShift: 'Удержание {icon} Shift',
  },
  mapBasics: {
    subtitle: 'Как поставить {pin} метку',
    createPin: '— поставить метку',
    removePin: '— удалить метку',
    placeNatal: '— поставить натальную метку',
  },
  measureBasics: {
    subtitle: 'Как пользоваться {ruler} инструментом измерения',
    drawLine: 'и {drag} — провести линию',
    touchDrawLine: '— провести линию',
    shiftSnap: 'над линией во время измерения — привязаться к ней: точное расстояние до этой линии',
    rightCancel: '— отключить инструмент',
    touchSnap: 'затем перетащите над линией для привязки',
    touchCancel: 'инструмента измерения ещё раз — выйти',
  },
  zoomBasics: {
    subtitle: 'Как быстро {zoom} масштабировать',
    zoomOut: 'по кнопке «Отдалить»',
    quickZoom: '— выделить область для приближения',
    perspective: '— изменить перспективу (только в 3D-проекции глобуса)',
    touchQuickZoom: '— приблизить или отдалить',
  },
} as const;
