// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/planets.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const planets = {
  Sun: {
    name: 'Солнце',
    theme: 'Суть личности, жизненная сила и то, в чём человек сияет.',
  },
  Moon: {
    name: 'Луна',
    theme: 'Эмоции, инстинкт и то, что дарит ощущение дома.',
  },
  Mercury: {
    name: 'Меркурий',
    theme: 'Ум: как человек думает, учится и общается.',
  },
  Venus: {
    name: 'Венера',
    theme: 'Любовь, красота, удовольствие и то, что человек ценит.',
  },
  Mars: {
    name: 'Марс',
    theme: 'Напор, смелость и то, как человек заявляет о себе и действует.',
  },
  Jupiter: {
    name: 'Юпитер',
    theme: 'Рост, удача и то, где жизнь расширяется и кажется щедрой.',
  },
  Saturn: {
    name: 'Сатурн',
    theme: 'Дисциплина, границы и нелегко давшиеся уроки зрелости.',
  },
  Uranus: {
    name: 'Уран',
    theme: 'Внезапные перемены, свобода и искра бунтарства.',
  },
  Neptune: {
    name: 'Нептун',
    theme: 'Мечты, интуиция, духовность и прекрасная иллюзия.',
  },
  Pluto: {
    name: 'Плутон',
    theme: 'Власть, интенсивность и глубокая трансформация и перерождение.',
  },
  NorthNode: {
    name: 'Сев. узел',
    theme: 'Точка роста: где жизнь зовёт вперёд и где приходит чувство принадлежности.',
  },
  SouthNode: {
    name: 'Юж. узел',
    theme: 'Знакомая почва: унаследованные дары, глубокие корни и то, с чем человек готов расстаться.',
  },
  Lilith: {
    name: 'Лилит',
    tipName: 'Чёрная Луна Лилит',
    theme: 'Дикий, неукрощённый инстинкт и то, где человек не даёт себя укротить.',
  },
  Chiron: {
    name: 'Хирон',
    theme: 'Раненый целитель: исцеление через собственную глубочайшую боль.',
  },
  Ceres: {
    name: 'Церера',
    theme: 'Забота, питание и жизненные циклы утраты и возвращения.',
  },
  Pallas: {
    name: 'Паллада',
    theme: 'Стратегия, мастерство и трезвое решение задач.',
  },
  Juno: {
    name: 'Юнона',
    theme: 'Обязательства, партнёрство и то, что нужно, чтобы ощущать его равным.',
  },
  Vesta: {
    name: 'Веста',
    theme: 'Преданность, сосредоточенность и внутренний огонь, который человек хранит как святыню.',
  },
  Fortune: {
    name: 'Фортуна',
    theme: 'Лёгкость, процветание и то, где благоденствуют тело и мирская жизнь.',
  },
} as const;
