// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/synastryHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const synastryHud = {
  title: 'Синастрия',
  chooseComparison: 'Выбрать карту для сравнения',
  choosePrompt: 'Выберите карту для сравнения',
  barToggle: {
    show: 'Показать параметры синастрии',
    hide: 'Скрыть параметры синастрии',
  },
  method: {
    label: 'Тип',
    davison: {
      label: 'Дэвисон',
      hint: 'Середина двух карт по времени и месту, построенная как настоящая карта.',
    },
    composite: {
      label: 'Комп. по полусуммам',
      hint: 'Каждая планета и каждый угол — в полусумме двух карт, причём у каждой планеты настоящие широта и склонение. Система отсчёта карты мира следует за Серединой неба композита.',
    },
  },
  generate: {
    label: 'Создать',
    hint: 'Построить карту, сделать её активной и сбросить партнёра по синастрии.',
    needPartner: 'Сначала выберите партнёра выше.',
    compositeParent: 'Композитную карту нельзя объединить ещё раз; выберите две обычные карты.',
  },
} as const;
