// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/timeline.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const timeline = {
  nubMode: {
    transits: 'Транзиты',
    progressed: 'Втор. прогрессии',
    'tertiary-progressed': 'Трет. прогрессии',
    'solar-arc': 'Солнечная дуга',
    'primary-directions': 'Перв. дирекции',
    cyclo: 'CCG',
  },
  nubFallback: 'Наложение',
  barToggle: {
    show: 'Показать шкалу времени',
    hide: 'Скрыть шкалу времени',
    hint: 'Ползунок даты и кнопки воспроизведения. Язычок остаётся в любом случае.',
  },
  drawer: {
    show: 'Показать переключатели',
    hide: 'Скрыть переключатели',
  },
  cyclo: {
    label: 'Сочетание',
    spName: 'Прогрессивные личные планеты',
    spTip: 'Sp — вторичные прогрессии',
    spHint: 'Солнце, Луна, Меркурий, Венера и Марс показаны в положениях вторичных прогрессий — темп «день за год» позволяет читать их рядом с внешними телами. Их линии помечены тегом Sp.',
    trName: 'Транзитные внешние тела',
    trTip: 'Tr — транзиты',
    trHint: 'Всё начиная с Юпитера и дальше — а также узлы, Лилит, Хирон и астероиды — показано в реальных транзитных положениях. Их линии помечены тегом Tr.',
  },
  positioning: {
    groupAria: 'Система отсчёта наложения',
    lockedNoTime: 'Время рождения неизвестно — нет натальной системы отсчёта, которую можно было бы удерживать, поэтому карта может показывать только небо момента.',
    heldForReturn: 'На паузе, пока карта мира показывает возвращение — карта возвращения остаётся собой только в собственной системе отсчёта. Этот выбор снимает паузу и возвращает карту мира в эту систему отсчёта.',
  },
  units: {
    minute: 'Минута',
    hour: 'Час',
    day: 'День',
    week: 'Неделя',
    month: 'Месяц',
    year: 'Год',
  },
  unitsLower: {
    minute: 'минута',
    hour: 'час',
    day: 'день',
    week: 'неделя',
    month: 'месяц',
    year: 'год',
  },
  minorLabel: {
    minute: '1 мин',
    hour: '10 мин',
    day: '6 часов',
    week: '1 день',
    month: '5 дней',
    year: '1 месяц',
  },
  stepWords: {
    minute: '{n, plural, one {минута} few {минуты} many {минут} other {минуты}}',
    hour: '{n, plural, one {час} few {часа} many {часов} other {часа}}',
    day: '{n, plural, one {день} few {дня} many {дней} other {дня}}',
    week: '{n, plural, one {неделя} few {недели} many {недель} other {недели}}',
    month: '{n, plural, one {месяц} few {месяца} many {месяцев} other {месяца}}',
    year: '{n, plural, one {год} few {года} many {лет} other {года}}',
  },
  stepSymbol: {
    minute: '{n, plural, other {мин}}',
    hour: '{n, plural, other {ч}}',
    day: '{n, plural, other {д}}',
    month: '{n, plural, other {мес}}',
  },
  transport: {
    stepBack: 'Шаг назад: {count} {unit}',
    stepForward: 'Шаг вперёд: {count} {unit}',
    stepBackAria: 'Шаг назад',
    stepForwardAria: 'Шаг вперёд',
    play: 'Пуск',
    pause: 'Пауза',
    stepAmountIn: {
      minute: 'Размер шага, в минутах',
      hour: 'Размер шага, в часах',
      day: 'Размер шага, в днях',
      month: 'Размер шага, в месяцах',
    },
    stepAmountInAria: {
      minute: 'Размер шага в минутах',
      hour: 'Размер шага в часах',
      day: 'Размер шага в днях',
      month: 'Размер шага в месяцах',
    },
  },
  ruler: {
    aria: 'Перемотка даты',
  },
  now: {
    label: 'Сейчас',
    tip: 'Установить текущий момент',
  },
  returns: {
    label: 'Возвращения',
    reframes: 'Заимствовать для карты мира систему отсчёта собственного момента возвращения. В натальной системе отсчёта возвращающееся тело закреплено на своём натальном градусе, поэтому его линии никогда не сдвигались бы от одного возвращения к следующему. Ваша система отсчёта поставлена на паузу, а не сброшена, и вернётся, когда вы выйдете из возвращения.',
    chip: {
      solar: 'Соляр',
      lunar: 'Лунар',
      tip: 'Карта показывает возвращение',
      hint: 'Пока карта мира показывает возвращение, система отсчёта наложения заимствована, поскольку углы карты возвращения — её собственные. Прежняя система отсчёта стоит на паузе и вернётся при выходе. Переход между возвращениями стрелками сохраняет паузу.',
      clear: 'Выйти из возвращения',
      clearHint: 'Вернуть прежнюю систему отсчёта наложения. Дата не меняется.',
      clearAria: 'Выйти из возвращения и восстановить систему отсчёта наложения',
    },
    solar: {
      name: 'Соляр',
      chartName: 'Соляр',
      snap: 'Ближайший соляр',
      snapAria: 'Перейти к ближайшему соляру',
      prev: 'Предыдущий соляр',
      prevAria: 'Предыдущий соляр',
      next: 'Следующий соляр',
      nextAria: 'Следующий соляр',
    },
    lunar: {
      name: 'Лунар',
      chartName: 'Лунар',
      snap: 'Ближайший лунар',
      snapAria: 'Перейти к ближайшему лунару',
      prev: 'Предыдущий лунар',
      prevAria: 'Предыдущий лунар',
      next: 'Следующий лунар',
      nextAria: 'Следующий лунар',
    },
  },
  scale: {
    label: 'Масштаб',
  },
  rate: {
    label: 'Ключ',
  },
  dateField: {
    tipChartZone: 'Момент транзитов / прогрессий в часовом поясе карты',
    tipChartZonePlace: 'Момент транзитов / прогрессий по времени места {place} — места рождения карты, где вас может и не быть',
    tipUtc: 'Момент транзитов / прогрессий по UTC',
  },
  datePicker: {
    open: 'Изменить дату и время',
    title: 'Задать дату и время',
    scrollKey: 'Прокрутка',
    scrollHint: 'для увеличения или уменьшения',
    apply: 'Применить',
    yearRange: 'Здесь можно выбрать годы с {min} по {max} — год вне этого диапазона заменяется ближайшим крайним годом.',
  },
  labelFull: {
    transits: 'Транзиты · {datetime} (UTC)',
    progressed: 'Втор. прогрессии · возраст {years}',
    'tertiary-progressed': 'Трет. прогрессии · возраст {years}',
    'solar-arc': 'Солнечная дуга · {deg}°',
    'primary-directions': 'Первичные дирекции · {deg}°',
    cyclo: 'Циклокартография · {datetime} (UTC)',
    synastry: 'Синастрия · {partner}',
    eclipses: 'Затмение · {datetime} (UTC)',
  },
  measure: {
    progressedAge: 'Возраст {years}',
  },
} as const;
