// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Русский for ../en/wheel.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../ru.lock.json). Keys, order and layout are rewritten on every run.
export const wheel = {
  house: '{number, selectordinal, other {#-й}} дом',
  signMeanings: {
    aries: 'Огонь · Кардинальный · инициатива',
    taurus: 'Земля · Фиксированный · стабильность',
    gemini: 'Воздух · Мутабельный · любознательность',
    cancer: 'Вода · Кардинальный · забота',
    leo: 'Огонь · Фиксированный · самовыражение',
    virgo: 'Земля · Мутабельный · точность',
    libra: 'Воздух · Кардинальный · баланс',
    scorpio: 'Вода · Фиксированный · интенсивность',
    sagittarius: 'Огонь · Мутабельный · приключения',
    capricorn: 'Земля · Кардинальный · амбиции',
    aquarius: 'Воздух · Фиксированный · новаторство',
    pisces: 'Вода · Мутабельный · воображение',
  },
  houseMeanings: {
    h1: 'Личность · идентичность · первые впечатления',
    h2: 'Деньги · имущество · самооценка',
    h3: 'Общение · братья и сёстры · учёба',
    h4: 'Дом · семья · корни',
    h5: 'Творчество · романтика · дети',
    h6: 'Работа · здоровье · повседневные дела',
    h7: 'Партнёрство · брак · «другой»',
    h8: 'Близость · общие ресурсы · перерождение',
    h9: 'Путешествия · философия · высшее образование',
    h10: 'Карьера · репутация · общественная жизнь',
    h11: 'Друзья · сообщество · надежды',
    h12: 'Уединение · незримое · духовность',
  },
  tip: {
    longitude: 'Долгота {lon}',
    latitude: 'Широта {lat}',
    minorCluster: '{n, plural, one {# малое тело} few {# малых тела} many {# малых тел} other {# малого тела}}',
    minorLine: '{name} {lon}',
    minorMore: 'ещё {n}',
    overlayMinor: '{name} · {chart}',
    overlayMinorCluster: '{chart}: {n, plural, one {# малое тело} few {# малых тела} many {# малых тел} other {# малого тела}}',
    minorLineOverlay: '{name} {lon} · {chart}',
    fortuneGeodetic: 'От геодезического Асцендента',
    fortuneGeodeticDay: 'От геодезического Асцендента, как для дневного рождения. При ночном рождении Фортуна отразилась бы относительно Асцендента',
    fortuneGeodeticNight: 'От геодезического Асцендента, как для ночного рождения. При дневном рождении Фортуна отразилась бы относительно Асцендента',
    rangeNote: 'Время рождения неизвестно: где угодно в этом диапазоне на дату рождения',
  },
  planetMeanings: {
    Sun: 'Личность · жизненная сила · эго',
    Moon: 'Эмоции · инстинкт · потребности',
    Mercury: 'Ум · общение',
    Venus: 'Любовь · красота · ценности',
    Mars: 'Напор · энергия · действие',
    Jupiter: 'Рост · удача · расширение',
    Saturn: 'Дисциплина · структура · границы',
    Uranus: 'Перемены · свобода · озарение',
    Neptune: 'Мечты · интуиция · дух',
    Pluto: 'Власть · трансформация',
    NorthNode: 'Путь души · рост',
    SouthNode: 'Прошлое · врождённые дары',
    Lilith: 'Тень · первобытный инстинкт',
    Chiron: 'Раненый целитель',
    Ceres: 'Забота · циклы',
    Pallas: 'Мудрость · стратегия',
    Juno: 'Верность · партнёрство',
    Vesta: 'Фокус · преданность',
    Fortune: 'Фортуна · жизненная сила · лёгкость',
  },
  angles: {
    As: {
      title: 'Асцендент',
      sub: 'Восходящий знак, личность и первое впечатление',
    },
    Ds: {
      title: 'Десцендент',
      sub: 'Отношения и «другой»',
    },
    Mc: {
      title: 'Середина неба (Medium Coeli)',
      sub: 'Карьера, репутация и общественная жизнь',
    },
    Ic: {
      title: 'Глубина неба',
      sub: 'Дом, корни и частная жизнь',
    },
    Vx: {
      title: 'Вертекс',
      sub: 'Судьбоносные встречи и поворотные моменты; западная точка первого вертикала',
    },
    Avx: {
      title: 'Антивертекс',
      sub: 'Восточный конец оси Вертекса, напротив Вертекса',
    },
  },
  motion: {
    retrograde: 'Ретроградность',
    stationary: 'Стационарность',
  },
} as const;
