// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/aspectLinesHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const aspectLinesHud = {
  title: 'Aspectos',
  closeAria: 'Fechar Aspectos',
  closeHint: 'Fechar esta janela. As linhas continuam ativas — desative-as em Configurações ▸ Avançado ▸ Linhas.',
  filters: {
    label: 'Filtros',
  },
  harmonious: {
    title: 'Harmônicos',
    hint: 'Linhas de sextil e de trígono. Uma só família pela geometria: cada linha se lê como sextil a partir de uma ponta do seu eixo e como trígono a partir da outra.',
  },
  challenging: {
    title: 'Desafiadores',
    hint: 'Linhas de quadratura — uma quadratura a uma ponta de um eixo é uma quadratura à outra, por isso esta família fica à parte.',
  },
  mcAxis: {
    title: 'Eixo do Meio do Céu',
    hint: 'Linhas que aspectam o MC (cada uma também pode ser lida a partir do IC).',
  },
  ascAxis: {
    title: 'Eixo do horizonte',
    hint: 'Linhas que aspectam o Ascendente (cada uma também pode ser lida a partir do Descendente).',
  },
  orbs: {
    label: 'Orbes de aspecto',
    infoTitle: 'Orbes de aspecto',
    infoHint: 'Distância máxima do exato (em graus) na roda do mapa e nas listas de aspectos. As linhas de aspecto do mapa-múndi marcam o ângulo exato e não usam orbe.',
  },
} as const;
