// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/autoFlip.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const autoFlip = {
  suppress: 'Não mostrar novamente',
  ok: 'Entendi',
  'overlay-frame-held': {
    title: 'Referencial da sobreposição mantido em Ângulos da revolução',
    body: 'Um mapa de revolução é um momento próprio, com ângulos próprios, e o mapa-múndi agora é desenhado em relação a eles, e não aos natais. O referencial anterior fica em espera, não é apagado — ele volta ao sair da revolução, ou imediatamente pelo ✕ do botão.',
  },
  'line-system-held': {
    title: 'O Geodésico está em espera',
    body: 'O sistema de linhas Geodésico mapeia o zodíaco tropical sobre as longitudes da Terra, então não existe uma versão sideral dele para desenhar. Sua escolha fica em espera, não é apagada — volte o zodíaco para Tropical e ela retorna.',
  },
  'line-projection': {
    title: 'Estas linhas são desenhadas In Mundo',
    body: 'Todo programa precisa decidir onde um corpo “está” antes de poder desenhar a linha dele. In Mundo o coloca onde ele está no céu, com latitude e tudo. In Zodiaco primeiro achata essa latitude sobre a eclíptica.',
  },
  'theme-held': {
    title: 'Seu tema está em espera',
    body: 'O tema que você escolheu não está disponível no momento, então o app é exibido no que você usava antes dele. Nada é apagado: ele volta como você o deixou assim que estiver disponível de novo.',
  },
  'theme-edits-held': {
    title: 'Sua própria versão está em espera',
    body: 'Sua própria versão deste tema não está disponível no momento, então a versão padrão dele é exibida no lugar. Nada é apagado: a sua volta como você a deixou assim que estiver disponível de novo.',
  },
  'language-detected': {
    title: 'Agora no idioma do seu navegador',
    body: 'A AstroLina agora tem uma tradução no idioma que o seu navegador pede, e abre nele. Para voltar ao inglês, ou escolher outro idioma, acesse {route}.',
  },
  'language-held': {
    title: 'Seu idioma escolhido está em espera',
    body: 'O idioma que você escolheu é traduzido neste dispositivo, o que não é possível aqui no momento, então o app é exibido no idioma de sempre. Sua escolha é mantida, não é apagada. Para escolher outro idioma, acesse {route}.',
  },
} as const;
