// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/bindingLanguage.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const bindingLanguage = {
  note: 'Traduzido para sua conveniência. Somente a versão em inglês é juridicamente vinculante.',
  showEnglish: 'Mostrar em inglês',
  showTranslation: 'Mostrar a tradução',
  iconLabel: 'Sobre esta tradução',
} as const;
