// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/captureHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const captureHud = {
  title: 'Captura',
  closeAria: 'Fechar Captura',
  closeHint: 'Fechar a ferramenta Captura.',
  subject: {
    label: 'Captura',
    map: 'Mapa',
    mapHint: 'Exportar o mapa-múndi enquadrado — suas linhas sobre o mundo, com o mapa astral como painel opcional ao lado delas.',
    chart: 'Roda',
    chartHint: 'Exportar só o mapa astral: a roda (ou as posições) preenche o enquadramento, desenhada como na barra lateral — aspectos, anel da sobreposição e tudo. Sem mapa-múndi, mesma legenda.',
  },
  aspect: {
    label: 'Enquadramento',
    square: '1:1',
    squareHint: 'Enquadramento quadrado (1:1) — ideal para publicações e avatares.',
    portrait: '4:5',
    portraitHint: 'Enquadramento retrato (4:5) — o formato alto para feeds no celular.',
    landscape: '16:9',
    landscapeHint: 'Enquadramento paisagem (16:9) — largo, para slides e cabeçalhos.',
  },
  transparent: {
    title: 'Transparente (Espaço local)',
    hint: 'Um único botão para uma exportação limpa do espaço local: oculta as setas das linhas, rotula as linhas como o resto do mapa astral (os rótulos ficam junto às bordas do enquadramento, sem graus de rumo) e apaga o mapa-base para que a exportação mantenha o fundo transparente — pronta para sobrepor a uma planta baixa ou ao seu próprio fundo. Tudo volta quando a Captura ou o Espaço local é fechado.',
    needLs: 'Ative primeiro o Espaço local (Exibir ▸ Espaço local) — esta exportação limpa e transparente é feita em torno da bússola e das linhas do espaço local.',
  },
  lsLabels: {
    name: {
      title: 'Nome no rótulo',
      hint: 'Imprimir o nome de cada planeta depois do glifo no rótulo do espaço local (ex.: “♂ Marte”).',
    },
    degrees: {
      title: 'Graus',
      hint: 'Imprimir o rumo de cada linha do espaço local ao longo da linha, logo para dentro do rótulo, em direção ao centro da bússola.',
    },
  },
  view: {
    none: 'Nenhum',
    noneHint: 'Sem detalhes do mapa astral no enquadramento — só o mapa-múndi, o alfinete, os rótulos das bordas e a legenda.',
    wheel: 'Roda',
    wheelHint: 'Mostrar o mapa astral como roda no enquadramento — a mesma da barra lateral. Os botões Planetas / Ângulos a preenchem; Balanço acrescenta abaixo a grade elemento·modalidade.',
    list: 'Lista',
    listHint: 'Mostrar o mapa astral como lista de posições de planetas / ângulos (e a contagem elemento·modalidade), as mesmas linhas da barra lateral.',
    phoneTitle: 'Indisponível no celular',
    phoneHint: 'Um enquadramento do tamanho de um celular é pequeno demais para mostrar a roda ou a lista ao lado do mapa-múndi com clareza, por isso os detalhes ficam desativados aqui. Para exportar o próprio mapa astral, mude a Captura para Roda — a roda então ocupa o enquadramento e fica legível neste tamanho.',
    tooSmallHint: 'Este enquadramento é pequeno demais para mostrar a roda ao lado do mapa — ela sairia com a borda cortada. Escolha um enquadramento mais largo (16:9 tem mais espaço), aumente a janela, desative Balanço para devolver o espaço à roda ou mude a Captura para Roda para exportar só a roda.',
    tooSmallBody: 'Este enquadramento não comporta uma roda legível ao lado do mapa-múndi, por isso os detalhes estão desativados. Uma captura do mapa astral dá à roda o enquadramento inteiro.',
    switchToChart: 'Capturar só a roda do mapa',
    tooSmallCardHint: 'Este enquadramento não dá à roda o espaço que um mapa astral completo exige — os aspectos e o anel da sobreposição pedem mais largura do que há aqui, e um enquadramento largo e baixo deixa a roda quase sem altura. Escolha 1:1 ou 4:5, aumente a janela, desative Balanço para devolver o espaço à roda ou capture as posições como Lista.',
    tooSmallCardBody: 'Este enquadramento é pequeno demais para desenhar o mapa astral completo, por isso as posições são mostradas no lugar dele. Uma janela mais alta — ou um enquadramento 1:1 ou 4:5 — dá à roda o espaço de que ela precisa.',
    clippedBody: 'Alguns detalhes não cabem neste enquadramento e seriam cortados na exportação. Tente um enquadramento mais largo, uma janela maior ou menos grupos.',
  },
  extras: {
    label: 'Detalhes',
    angles: 'Ângulos',
    anglesHint: 'Adicionar os ângulos do mapa astral (AS, MC, DS, IC…) ao painel, depois dos planetas.',
    balance: 'Balanço',
    balanceHint: 'Adicionar o balanço de elementos + modalidades — quais planetas caem em Fogo/Terra/Ar/Água e Cardinal/Fixo/Mutável.',
  },
  caption: {
    label: 'Legenda',
    name: 'Nome',
    nameHint: 'Mostrar o nome do mapa no rodapé da legenda.',
    date: 'Data',
    dateHint: 'Mostrar a data de nascimento no rodapé da legenda.',
    time: 'Hora',
    timeHint: 'Mostrar a hora de nascimento no rodapé da legenda.',
    location: 'Local',
    locationHint: 'Mostrar o local no rodapé da legenda: o local de nascimento ou seu alfinete, quando você colocar um.',
    coordinates: 'Coordenadas',
    coordinatesHint: 'Mostrar a latitude e a longitude completas do local na legenda: o local de nascimento ou seu alfinete, quando você colocar um.',
    calculations: 'Cálculos',
    calculationsHint: 'Mostrar os sistemas de cálculo ativos (a mesma linha da Barra de informações) no rodapé da legenda e, enquanto houver uma desenhada, a sobreposição temporal com sua data.',
    discreet: 'O Modo discreto está ativado, por isso o nome, a data de nascimento e a hora ficam em branco aqui e na imagem exportada. Pressione P para mostrá-los.',
  },
  calcOverlay: {
    transits: 'Trânsitos',
    progressed: 'Prog. secundária',
    'tertiary-progressed': 'Prog. terciária',
    'solar-arc': 'Arco solar',
    'primary-directions': 'Direções primárias',
    cyclo: 'CCG',
  },
  share: {
    title: 'Compartilhar',
    hint: 'Abrir o menu de compartilhamento do seu dispositivo para salvar ou enviar a imagem (celular e computadores compatíveis).',
    sheetTitle: 'AstroLina Cartografia',
    sheetText: 'AstroLina — astrocartografia na web para mentes curiosas',
  },
  download: {
    title: 'Baixar',
    hint: 'Salvar a visualização enquadrada como arquivo PNG.',
  },
  copy: {
    title: 'Copiar',
    hint: 'Copiar a visualização enquadrada para a área de transferência, pronta para colar.',
    done: 'Copiado',
  },
  link: {
    title: 'Copiar link',
    hint: 'Copiar um link que abre este mapa e esta visualização — os dados de nascimento vão no link, então só o compartilhe com pessoas que possam vê-los.',
    done: 'Link copiado',
    warnAria: 'Aviso de privacidade do link',
    warnBody: 'NOTA: este link contém os dados de nascimento completos do mapa (data, hora e local).',
    warnSuppress: 'Não me lembrar novamente',
    warnConfirm: 'Copiar link',
    warnCancel: 'Cancelar',
  },
  busy: 'Renderizando…',
  failed: 'A exportação falhou — por favor, tente novamente.',
  failedReason: {
    'no-frame': 'A visualização do mapa não estava pronta. Reabra a Captura e tente mais uma vez.',
    'no-canvas': 'Este navegador não forneceu uma superfície de desenho para a exportação.',
    'taint-basemap': 'Os blocos do mapa se recusaram a ser exportados. A causa costuma ser a prevenção de rastreamento ou um bloqueador de conteúdo — permita este site e tente novamente.',
    encode: 'A imagem era grande demais para ser codificada. Tente uma proporção de enquadramento menor.',
    overlay: 'Não foi possível desenhar a legenda e os rótulos, por isso nenhuma imagem foi gerada. Recarregue o app e tente novamente.',
  },
} as const;
