// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/chartWheel.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const chartWheel = {
  resizeLabel: 'Alternar tamanho da roda',
  shrink: 'Reduzir roda',
  enlarge: 'Ampliar roda',
  openSidebar: 'Abrir a roda completa',
  openSidebarHint: 'Uma roda maior, com aspectos e a tabela de planetas, no painel lateral.',
  openSidebarLabel: 'Mostrar a barra lateral do mapa',
  placeholder: 'Nenhum mapa selecionado',
  noChart: 'SEM MAPA (CCG)',
} as const;
