// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/chartManager.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const chartManager = {
  dialogLabel: 'Mapas',
  title: 'Meus mapas',
  comparisonTitle: 'Sinastria com {name}',
  comparisonLabel: 'Sinastria',
  searchPlaceholder: 'Pesquisar nomes ou locais…',
  searchLabel: 'Pesquisar mapas',
  clearSearch: 'Limpar pesquisa',
  filter: {
    label: 'Filtrar por etiqueta',
    all: 'Todos',
    starred: 'Estrela',
    space: 'Espaço',
    unknown: 'Sem hora',
    shared: 'Compartilhado',
  },
  folders: {
    new: 'Nova pasta',
    newChild: 'Nova subpasta',
    rename: 'Renomear pasta',
    remove: 'Remover',
    moveTo: 'Mover para',
    unfiled: 'Sem pasta',
    nameLabel: 'Nome da pasta',
    namePlaceholder: 'Nome da pasta',
  },
  discreet: {
    hide: 'Ativar o Modo discreto',
    show: 'Desativar o Modo discreto',
  },
  empty: 'Nenhum mapa salvo ainda.',
  noMatches: 'Nenhum mapa encontrado.',
  addQuery: 'Adicionar “{name}”',
  editingHeader: 'Editando {name}',
  saveChanges: 'Salvar alterações',
  addChart: 'Adicionar mapa',
} as const;
