// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/chartSwitcher.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const chartSwitcher = {
  noChart: 'Nenhum mapa selecionado',
  tip: 'Trocar, editar ou adicionar um mapa',
  tabHint: '{key} troca para o seu mapa anterior — pressione mais vezes para percorrer os cinco recentes.',
  empty: 'Nenhum mapa salvo ainda.',
  searchAdd: 'Pesquisar + adicionar nome',
} as const;
