// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/common.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const common = {
  close: 'Fechar',
  cancel: 'Cancelar',
  edit: 'Editar',
  delete: 'Excluir',
  keep: 'Manter',
  locationFallbackOcean: 'Oceano',
  tzWarning: '⚠ Fuso anterior a 1970 fora dos EUA/UE: confira o horário de verão num atlas',
  timeUnknownBanner: 'Hora de nascimento desconhecida',
  provisionalTimeBanner: '⚠ Testando {time} — provisório, não salvo',
  locked: {
    feature: '{feature} é um recurso do plano {tier}.',
    featureAnyTier: '{feature} não faz parte do seu plano.',
  },
  cardinal: {
    north: 'N',
    south: 'S',
    east: 'L',
    west: 'O',
  },
  hud: {
    dragToMove: 'Arraste para mover',
    dockKey: 'Duplo',
    dockHint: 'para acoplar · encaixa no centro',
    recentreHint: 'para centralizar de novo',
    collapse: 'Recolher painel',
    expand: 'Expandir painel',
    collapseHint: 'Mostrar ou ocultar os controles.',
    closeNamed: 'Fechar {name}',
  },
} as const;
