// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/creditsModal.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const creditsModal = {
  title: 'Créditos e licenças',
  thanks: {
    tip: 'Agradecimentos especiais',
    hint: 'Ver créditos',
    title: 'Agradecimentos especiais',
    leadRole: 'A astróloga por trás da AstroLina',
    leadBody: 'Este aplicativo começou como a prática dela, e ainda presta contas a ela. Os métodos que ele segue, as convenções que mantém e o critério por trás de cada linha que desenha são dela — explicados com paciência, e muitas vezes mais de uma vez, até que o software estivesse à altura do ofício.',
    othersHeading: 'Agradecemos também a',
    body: 'Duas astrólogas profissionais dedicaram seu tempo, seu conhecimento e uma boa dose de paciência a este projeto — respondendo a perguntas, conferindo convenções e ajudando uma ferramenta ainda nova a se firmar. Sem elas, ele seria algo menor.',
    role: 'Astróloga profissional',
  },
  intro: 'A AstroLina é construída sobre dados abertos e software de código aberto. Os textos completos das licenças estão disponíveis no repositório do projeto.',
  notice: {
    lead: 'Somos novos nisso, e sua ajuda é bem-vinda.',
    body: 'A astronomia é sólida — Swiss Ephemeris e dados do JPL, auditados em relação ao serviço Horizons da NASA com precisão de bem menos de um segundo de arco. O aplicativo em volta dela está na versão um, e faz tanta coisa que não teríamos como chegar a todos os cantos antes do lançamento. Então, se uma linha parecer errada, um número parecer estranho ou algo simplesmente não fizer o que você pediu, por favor nos avise — cada relato é lido por uma pessoa, e queremos fazer desta uma ferramenta em que você possa confiar.',
    report: 'Relatar um problema.',
  },
  groups: {
    astrolina: 'AstroLina',
    mapsPlaces: 'Mapas e locais',
    astronomy: 'Astronomia',
    typeSoftware: 'Tipografia e software',
  },
  notes: {
    astrolina: '© 2026 AstroLina. Software livre e de código aberto sob a GNU Affero General Public License v3.0.',
    sourceCode: 'Código-fonte completo, disponível conforme a AGPL. Contribuições são bem-vindas.',
    openstreetmap: 'Dados do mapa-base (também creditados no próprio mapa).',
    openfreemap: 'Tiles vetoriais, fontes de rótulos e sprites gratuitos.',
    mapStyles: 'MapTiler Basic, OSM Bright, Dark Matter, Positron e Fiord Color, alguns adaptados. © MapTiler.com e colaboradores do OpenMapTiles; © Mapbox; © CartoDB.',
    geonames: 'Pesquisa offline por nome de local e busca de cidades.',
    photon: 'Pesquisa online por local e endereço; dados © colaboradores do OpenStreetMap.',
    swisseph: 'Posições planetárias (JPL DE441). © Astrodienst AG, via @swisseph/browser.',
    nasaEclipse: 'Catálogos de eclipses solares e lunares (datas, tipos, série de Saros). Previsões de eclipses por Fred Espenak e Jean Meeus (NASA/GSFC).',
    jplSbdb: 'Classes orbitais por trás das etiquetas de planetas menores.',
    noto: 'Glifos astrológicos. © 2022 The Noto Project Authors.',
    maplibre: 'Renderização interativa de mapas.',
    rtlText: 'Rótulos de mapa da direita para a esquerda: letras árabes ligadas, árabe e hebraico na ordem de leitura. © 2017 Mapbox.',
    icu: 'O código de modelagem de glifos e de texto bidirecional dentro do plugin de rótulos da direita para a esquerda. © Unicode, Inc.',
    other: 'Além de outras bibliotecas sob licença MIT listadas no repositório do projeto.',
  },
  footer: ' · Os cálculos de astrocartografia e o design da interface são da própria AstroLina; as efemérides e os dados de mapa subjacentes estão creditados acima.',
} as const;
