// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/eclipseHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const eclipseHud = {
  title: 'Eclipses',
  choose: 'Escolher um eclipse',
  prev: 'Eclipse anterior',
  next: 'Próximo eclipse',
  locate: 'Voar até este eclipse',
  all: 'Todos',
  searchPlaceholder: 'Pesquisar ano, tipo ou Saros…',
  noMatches: 'Nenhum eclipse corresponde.',
  saros: 'Saros {n}',
  barToggle: {
    show: 'Mostrar detalhes do eclipse',
    hide: 'Ocultar detalhes do eclipse',
  },
} as const;
