// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/localSpaceHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const localSpaceHud = {
  title: 'Espaço local',
  closeAria: 'Fechar Espaço local',
  closeHint: 'Desativar a visualização do espaço local.',
  lsOrigin: {
    pin: 'Do alfinete',
    pinHint: 'Espaço local relocado: as linhas partem do alfinete ativo (o local de nascimento, quando não há alfinete).',
    birthplace: 'Local de nascimento',
    birthplaceHint: 'As linhas ficam ancoradas no local de nascimento mesmo com um alfinete no mapa.',
    home: 'Residência',
    homeHint: 'Irradiar os rumos de onde a pessoa deste mapa mora agora — defina ou altere a residência aqui mesmo. Usa o local de nascimento enquanto nenhuma residência estiver definida.',
    homeUnset: 'Nenhuma residência definida para este mapa — os rumos partem do local de nascimento até que você defina uma.',
  },
  hideInbound: {
    title: 'Linhas de entrada',
    hint: 'A continuação de entrada de cada linha do espaço local — a metade tracejada que aponta para o antípoda do corpo, oposta ao rumo de saída (contínuo). Desative para manter só as metades de saída.',
  },
  hideDegrees: {
    title: 'Graus',
    hint: 'O rumo em cada rótulo de saída, em graus e minutos. Desativado, deixa nos rótulos só LS e o glifo.',
  },
  hideCompass: {
    title: 'Bússola',
    hint: 'A roda da bússola do horizonte local, que surge na origem quando você aproxima o zoom.',
  },
  flyToOrigin: {
    title: 'Voar até a origem',
    hint: 'Descer ao horizonte local: levar a câmera até a origem de onde partem as linhas.',
  },
} as const;
