// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/map.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const map = {
  ctrl: {
    zoomIn: 'Aumentar zoom',
    zoomOut: 'Diminuir zoom',
    resetBearing: 'Redefinir rotação e inclinação',
  },
  pin: {
    natal: 'Local de nascimento natal (clique com o botão direito para remover)',
    custom: 'Local com alfinete (clique com o botão direito para remover)',
    home: 'Residência — onde a pessoa deste mapa mora agora (clique com o botão direito para remover o alfinete)',
  },
  home: {
    tip: 'Residência',
    hint: 'Clique para ler o mapa aqui',
  },
  flyToZenith: 'Voar até o zênite: {prefix}{planet}',
  flyToAspectPoint: 'Voar até onde o grau de {aspect} de {planet} fica a pino (clique de novo para voltar)',
  flyToMidpoint: 'Voar até onde o ponto médio {planetA}/{planetB} fica a pino (clique de novo para voltar)',
  aspectNames: {
    sextile: 'sextil',
    square: 'quadratura',
    trine: 'trígono',
  },
  flyToParan: 'Voar até a interseção deste paran (clique de novo para voltar)',
  flyToLocalSpaceOrigin: 'Voar até a origem do espaço local (o alfinete)',
  ecliptic: 'Eclíptica',
  polarNote: 'Zona polar: além da crista desta linha, o nascer e o ocaso trocam de lugar.',
  eclipse: {
    central: 'Linha central',
    pathEdge: 'Borda da trajetória central',
    isoline: 'Eclipse máximo de {pct}',
    outerLimit: 'Limite de visibilidade — dentro desta linha há algum eclipse',
    horizon: 'Linha de nascer/ocaso da Lua em {phase}',
    localMax: '{pct} do Sol coberto aqui — {time} (UTC)',
    lunarAllVisible: 'O eclipse inteiro é visível daqui',
    lunarPartView: 'Parte do eclipse é visível daqui ({n} de {total} contatos)',
  },
  eclipseCard: {
    notVisible: 'Eclipse não visível daqui',
    utc: 'UTC',
    c1: 'Início da fase parcial',
    c2: 'Início da totalidade',
    c2Annular: 'Início do anel',
    max: 'Máximo',
    c3: 'Fim da totalidade',
    c3Annular: 'Fim do anel',
    c4: 'Fim da fase parcial',
    atSunrise: 'ao nascer do sol',
    atSunset: 'ao pôr do sol',
    maxValue: 'Magnitude {mag} · {obsc} de cobertura',
    duration: 'Duração',
    phase: {
      P1: 'Início da fase penumbral',
      U1: 'Início da fase parcial',
      U2: 'Início da totalidade',
      max: 'Máximo',
      U3: 'Fim da totalidade',
      U4: 'Fim da fase parcial',
      P4: 'Fim da fase penumbral',
    },
    belowHorizon: 'Lua abaixo do horizonte',
    moonrise: 'Nascer da Lua',
    moonset: 'Ocaso da Lua',
  },
  lineCard: {
    distance: '{label} {km} km / {mi} mi',
  },
  zenithTitle: 'Zênite de {planet}',
  zenithSub: 'onde {planet} fica exatamente a pino',
  nadirTitle: 'Nadir de {planet}',
  nadirSub: 'onde {planet} fica exatamente sob os pés',
  geoReadout: {
    place: '{place} GE',
    coords: '{lat} {lng} GE',
    as: 'AS',
    mc: 'MC',
  },
  geoLegend: {
    aria: 'Legenda do sombreamento das zonas',
    isolate: 'Mostrar só as zonas de {group}',
    clear: 'Mostrar todas as zonas',
  },
  zoomOutToWide: 'Afastar até uma visão ampla',
  zoomOut: 'Diminuir zoom',
  webgl: {
    unsupportedTitle: 'Este mapa precisa de WebGL',
    unsupportedBody: 'Seu navegador não está fornecendo a esta página um contexto gráfico WebGL, então o mapa não pode ser desenhado.',
    tipsHeading: 'Algumas coisas que você pode tentar:',
    tipAccel: 'Ative a aceleração de hardware nas configurações do navegador e depois recarregue.',
    tipShield: 'Permita WebGL / canvas para este site se você usa uma proteção contra fingerprinting ou de privacidade.',
    tipBrowser: 'Ou abra a AstroLina em outro navegador atualizado.',
    lostTitle: 'O mapa perdeu seu contexto gráfico',
    lostBody: 'Isso pode acontecer quando o dispositivo está com pouca memória gráfica. Muitas vezes o mapa se recupera sozinho — se não se recuperar, recarregue a página.',
    reload: 'Recarregar a página',
  },
} as const;
