// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/missions.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const missions = {
  guideTitle: 'Missões',
  title: 'Guia',
  close: 'Dispensar',
  skipTip: 'Pular este guia',
  ok: 'OK, entendi',
  okLocked: 'Conclua todas as missões para continuar',
  dontShowAgain: 'Não mostrar novamente',
  prevGuide: 'Guia anterior',
  nextGuide: 'Próximo guia',
  guidePosition: 'Guia {current} de {total}',
  gesture: {
    double: 'Duplo',
    right: 'Botão direito',
    hold: 'Segure',
    shift: 'Shift',
    drag: 'Arraste',
    click: 'Clique',
    tap: 'Toque',
    doubleTap: 'Toque duas vezes',
    longPress: 'Toque e segure',
    touchDrag: 'Toque e arraste',
    twoFinger: 'Arraste com 2 dedos',
    pinch: 'Pince',
    snap: 'Encaixar',
  },
  pill: {
    double: 'Clique {icon} duas vezes',
    right: 'Clique {icon} com o botão direito',
    hold: 'Segure {icon} e arraste',
    shiftDrag: 'Arraste {icon} com Shift',
    rightDrag: 'Arraste {icon} com o botão direito',
    tapSnap: 'Toque {icon} em Encaixar',
    holdShift: 'Segure {icon} Shift',
  },
  mapBasics: {
    subtitle: 'Como colocar um alfinete {pin}',
    createPin: 'para colocar um alfinete',
    removePin: 'para remover um alfinete',
    placeNatal: 'para soltar o alfinete natal',
  },
  measureBasics: {
    subtitle: 'Como usar a ferramenta {ruler} Medir',
    drawLine: 'e {drag} para desenhar uma linha',
    touchDrawLine: 'para desenhar uma linha',
    shiftSnap: 'sobre uma linha enquanto mede para encaixar nela — a distância exata até essa linha',
    rightCancel: 'para cancelar a ferramenta',
    touchSnap: 'e depois arraste sobre uma linha para encaixar',
    touchCancel: 'na ferramenta Medir de novo para sair',
  },
  zoomBasics: {
    subtitle: 'Como dar {zoom} zoom rapidamente',
    zoomOut: 'no botão “Diminuir zoom”',
    quickZoom: 'para criar uma janela de zoom',
    perspective: 'para mudar a perspectiva (somente na visualização em projeção de globo 3D)',
    touchQuickZoom: 'para aumentar ou diminuir o zoom',
  },
} as const;
