// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/planets.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const planets = {
  Sun: {
    name: 'Sol',
    theme: 'Sua identidade essencial, sua vitalidade e onde você brilha.',
  },
  Moon: {
    name: 'Lua',
    theme: 'Emoções, instinto e o que traz a sensação de lar.',
  },
  Mercury: {
    name: 'Mercúrio',
    theme: 'A mente: como você pensa, aprende e se comunica.',
  },
  Venus: {
    name: 'Vênus',
    theme: 'Amor, beleza, prazer e aquilo que você valoriza.',
  },
  Mars: {
    name: 'Marte',
    theme: 'Impulso, coragem e como você se afirma e age.',
  },
  Jupiter: {
    name: 'Júpiter',
    theme: 'Crescimento, sorte e onde a vida se expande e se mostra generosa.',
  },
  Saturn: {
    name: 'Saturno',
    theme: 'Disciplina, limites e as lições da maturidade, conquistadas a duras penas.',
  },
  Uranus: {
    name: 'Urano',
    theme: 'Mudança súbita, liberdade e sua centelha de rebeldia.',
  },
  Neptune: {
    name: 'Netuno',
    theme: 'Sonhos, intuição, espiritualidade e a bela ilusão.',
  },
  Pluto: {
    name: 'Plutão',
    theme: 'Poder, intensidade, transformação profunda e renascimento.',
  },
  NorthNode: {
    name: 'Nodo N',
    theme: 'Sua fronteira de crescimento: onde a vida chama você para a frente e onde o pertencimento encontra você.',
  },
  SouthNode: {
    name: 'Nodo S',
    theme: 'Terreno conhecido: dons herdados, raízes profundas e o que você já pode deixar ir.',
  },
  Lilith: {
    name: 'Lilith',
    tipName: 'Lua Negra Lilith',
    theme: 'Instinto cru e indomado, e onde você não se deixa domar.',
  },
  Chiron: {
    name: 'Quíron',
    theme: 'O curador ferido: a cura através da sua própria dor mais profunda.',
  },
  Ceres: {
    name: 'Ceres',
    theme: 'Cuidado, nutrição e os ciclos de perda e retorno da vida.',
  },
  Pallas: {
    name: 'Palas',
    theme: 'Estratégia, habilidade e resolução lúcida de problemas.',
  },
  Juno: {
    name: 'Juno',
    theme: 'Compromisso, parceria e aquilo de que você precisa para sentir que há igualdade.',
  },
  Vesta: {
    name: 'Vesta',
    theme: 'Devoção, foco e a chama interior que você mantém sagrada.',
  },
  Fortune: {
    name: 'Fortuna',
    theme: 'Bem-estar, florescimento e onde o corpo e a vida material prosperam.',
  },
} as const;
