// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/settings.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const settings = {
  sections: {
    appearance: 'Aparência',
    mapFilters: 'Filtros do mapa',
    calculation: 'Cálculo',
    advanced: 'Avançado',
  },
  headings: {
    theme: 'Tema',
    privacy: 'Privacidade',
    details: 'Detalhes',
    projection: 'Projeção',
    language: 'Idioma',
    planets: 'Planetas',
    points: 'Pontos',
    minorBodies: 'Corpos menores',
    angles: 'Ângulos',
    lines: 'Linhas',
    lineSystem: 'Sistema de linhas',
    lineProjection: 'Projeção das linhas',
    geoGrid: 'Grade geodésica',
    lunarNode: 'Nodo lunar',
    houseSystem: 'Sistema de casas',
    zodiac: 'Zodíaco',
    aspectOrbs: 'Orbes de aspecto',
    primaryRate: 'Chave das dir. primárias',
    display: 'Exibição',
    arc: 'Arco',
    progAngles: 'Ângulos',
    magnitudeSteps: 'Passos de magnitude',
    fortuneFormula: 'Parte da Fortuna',
    rulerships: 'Regências',
  },
  details: {
    roadsRivers: 'Estradas/Rios',
    roadsRiversHint: 'Mostra o traçado de estradas e rios do mapa-base. Oculte-o para deixar o fundo mais limpo atrás das linhas de astrocartografia.',
    placeNames: 'Nomes de locais',
    placeNamesHint: 'Mostra os nomes de cidades e países do mapa-base. Isso é independente dos rótulos das linhas de ACG, que ficam visíveis de qualquer forma.',
  },
  shiftTag: 'Shift',
  natal: {
    title: 'Mapa natal',
    hint: 'O mapa natal subjacente. Oculte-o e a sobreposição toma o seu lugar — assumindo as linhas, a roda e os dados do mapa.',
  },
  languageUnavailable: 'Em breve.',
  machine: {
    section: 'Tradução automática',
    sectionHint: 'Os idiomas acima vêm com a AstroLina. Os idiomas abaixo serão traduzidos automaticamente neste dispositivo.',
    hint: 'Traduzido do inglês neste dispositivo, à medida que você usa o app. Alguns trechos podem ficar imprecisos.',
    downloadHint: 'Traduzido do inglês neste dispositivo. Na primeira vez, o modelo de tradução é baixado para o dispositivo.',
    partialHint: 'Parte do app ainda está em inglês. Escolha o idioma de novo para terminar de baixar a tradução para este dispositivo.',
    heldDownloadHint: 'Sua escolha, em espera até que a tradução seja baixada de novo para este dispositivo. Escolha o idioma para baixá-la.',
    heldHint: 'Este dispositivo não consegue traduzir para este idioma no momento. Sua escolha é mantida e volta quando isso for possível.',
    cacheHint: 'Exibido a partir do que este dispositivo traduziu antes. Aqui ele não consegue mais traduzir, então o texto novo fica em inglês.',
    downloading: 'Baixando {language} para este dispositivo… {percent}%',
    translating: 'Traduzindo para {language}…',
    failed: 'Não foi possível configurar {language} neste dispositivo.',
    disclosure: 'Traduzido automaticamente neste dispositivo. Alguns trechos podem ficar imprecisos; o que ainda não foi traduzido aparece em inglês.',
  },
  dock: {
    open: 'Abrir configurações',
    close: 'Fechar configurações',
  },
  userRate: {
    label: 'Graus por ano',
  },
  parans: {
    title: 'Parans',
    hint: 'Latitudes onde dois corpos estão angulares ao mesmo tempo, um nascendo enquanto outro culmina, e assim por diante. Os parans do seu mapa seguem ativos ao lado de uma sobreposição.',
    blockedCyclo: 'Não há um único momento do céu — a Ciclocartografia lê corpos progredidos e em trânsito juntos. Mostre o Mapa natal para trazer de volta os parans do próprio mapa.',
    blockedOverlay: 'Os parans são lidos do mapa, e esta sobreposição está no lugar dele. Mostre o Mapa natal para trazer de volta os parans do mapa.',
  },
  aspectLines: {
    title: 'Linhas de aspecto',
    hint: 'Linhas onde um planeta faz sextil (⚹), quadratura (□) ou trígono (△) ao MC ou Ascendente — cada aspecto duas vezes, uma por lado. Um trígono ao AS também é sextil ao DS; passe o cursor sobre uma linha para ver as duas leituras. Conjunções e oposições são as linhas de ângulo do planeta, já no mapa.',
    openHud: 'Personalizar',
    openHudHint: 'Abrir a janela Aspectos: filtrar as linhas do mapa por qualidade e eixo e definir todos os orbes de aspecto de uma vez.',
  },
  midpointLines: {
    title: 'Linhas de ponto médio',
    hint: 'Linhas onde o ponto médio de dois corpos visíveis cai exatamente sobre um ângulo (ex.: Su/Mo MC). In Mundo usa o ponto médio corporal (AR e declinação médias); In Zodiaco, o ponto médio clássico em longitude. Restrinja o filtro de planetas para manter o conjunto legível.',
    blockedCyclo: 'Aqui, um ponto médio faria a média de um corpo progredido e de um em trânsito em um só ponto — incoerente entre duas épocas.',
  },
  zenithNadir: {
    title: 'Zênites/Nadires',
    hint: 'Marca onde cada corpo está a pino (zênite — um círculo na linha do MC) e sob os pés (nadir — um losango na linha do IC). Passe o cursor para identificar e clique para ir até lá.',
  },
  aspectOrbs: {
    hint: 'Distância máxima do exato (graus) por aspecto, na roda e nas listas de aspectos. Luminares amplia cada orbe quando o Sol ou a Lua participam; Paralelos é o orbe de declinação.',
    setDegrees: 'Definir graus',
    orbAria: 'Orbe dos aspectos de {aspect}, em graus',
    lumLabel: 'Luminares +',
    lumHint: 'Graus extras de orbe sempre que o Sol ou a Lua estiverem envolvidos.',
    lumAria: 'Orbe extra quando há um luminar envolvido, em graus',
    declinationLabel: 'Paralelos',
    declinationAria: 'Orbe dos aspectos de paralelo e contraparalelo, em graus de declinação',
  },
  zodiac: {
    tropical: {
      label: 'Tropical',
      hint: 'Signos ancorados nas estações (0° de Áries = o equinócio de março). O padrão ocidental.',
    },
    lahiri: {
      label: 'Sideral · Lahiri',
      hint: 'Signos ancorados nas estrelas fixas, pelo ayanamsa Lahiri (o padrão védico, hoje ~24° atrás do tropical). Muda a roda e os dados; as linhas do mapa marcam eventos independentes do zodíaco e não se movem.',
    },
    'fagan-bradley': {
      label: 'Sideral · Fagan/Bradley',
      hint: 'Signos ancorados nas estrelas fixas, pelo ayanamsa Fagan/Bradley (o padrão sideral ocidental). Muda a roda e os dados; as linhas do mapa não se movem.',
    },
  },
  natalLines: {
    title: 'Linhas natais',
    hint: 'As linhas de ângulo do mapa natal no Ascendente, MC, Descendente e IC — e, ao lado de uma sobreposição, seus parans. A roda e os dados ficam; linhas ocultas não são clicáveis.',
  },
  starLines: {
    title: 'Estrelas fixas',
    hint: 'Linhas de ângulo das estrelas fixas clássicas (Regulus, Spica, Algol e companhia): linhas pontilhadas entremeadas de pequenas estrelas, num mesmo tom de luz estelar. As linhas de nascer/ocaso são omitidas para estrelas circumpolares; ali, os parans são a leitura tradicional.',
    bright: 'Estrelas principais',
    brightHint: 'As quatro estrelas reais e as clássicas mais brilhantes (18 estrelas).',
    all: 'Conjunto completo',
    allHint: 'Todo o conjunto de trabalho incluído (40 estrelas). Espere um mapa carregado.',
  },
  nightShade: {
    title: 'Sombra noturna',
    hint: 'Sombreia a metade da Terra que está de noite no momento exibido.',
  },
  discreet: {
    title: 'Modo discreto',
    hint: 'Oculta nomes, datas e locais de nascimento em toda a tela — inclusive na legenda de uma captura e na imagem que ela exporta — para você trabalhar com alguém ao seu lado. O mapa e suas linhas não mudam, e um documento que você se dispõe a produzir ainda traz os dados reais.',
  },
  orbZones: {
    title: 'Zonas de orbe',
    hint: 'Zonas de influência sombreadas: faixa medida no solo em volta das linhas de ângulo dos planetas e dos parans. A influência cai com a distância; a borda é convenção, não abismo.',
    unitAria: 'Unidade de distância da zona de orbe (km ou mi)',
    lineAria: 'Largura da zona de orbe das linhas, de cada lado',
    paranLabel: 'Parans',
    paranAria: 'Largura do orbe dos parans, de cada lado',
  },
  theme: {
    glass: {
      label: 'Vidro',
      hint: 'Painéis prateados foscos sobre um mapa claro e detalhado, de terras cor de creme e mares azul-claros.',
    },
    dark: {
      label: 'Escuro',
      hint: 'Um mapa cinza-ardósia profundo sob painéis escuros, feito para a madrugada, onde cada linha se destaca.',
    },
    vintage: {
      label: 'Terra',
      hint: 'Um visual quente de atlas: mares de azul suave e terras cor de areia, emoldurados por painéis marrom-pergaminho.',
    },
    customize: 'Personalizar',
    customizeHint: 'Abrir o editor de temas: cores, estilos de linha e efeitos, de algumas escolhas amplas até cada valor individual.',
    customHeld: 'Não está disponível agora. Enquanto isso, o app é exibido com o tema que você usava antes deste; sua escolha é mantida, não apagada.',
    customEditsHeld: 'Sua própria versão deste tema não está disponível agora, então a versão padrão é exibida; a sua é mantida, não apagada.',
    outlineUnavailable: 'O mapa Contorno tem só litorais: não tem estradas, rios nem nomes de locais. Escolha outro Mapa em Personalizar para usar isto; sua escolha é mantida.',
    lockedNote: 'Ainda não liberado para esta conta. Pressione para ver o que o desbloqueia.',
    keptNote: 'Continua sendo seu. Se você mudar para outro tema, voltar a este exige o que o selo indica.',
  },
  projection: {
    hint: 'Como o mundo é desenhado — não onde as coisas estão. As duas vistas marcam as mesmas coordenadas, e toda distância que o app informa (o campo de distância mínima no cartão de uma linha, a medição por clicar e arrastar, as zonas de orbe) é uma distância real no solo, medida sobre a esfera. Mas nenhuma das vistas é segura para julgar a proximidade a olho: a vista Plana estica a escala rumo aos polos e o globo a comprime rumo à borda, então leia a distância, e não o espaço na tela.',
    '2d': {
      label: 'Plana',
      hint: 'Mapa Web-Mercator clássico',
    },
    '3d': {
      label: 'Globo',
      hint: 'Globo 3D giratório',
    },
  },
  lineSystem: {
    celestial: {
      label: 'Celeste',
      hint: 'Astrocartografia padrão: ângulos situados pelo céu (tempo sideral)',
    },
    geodetic: {
      label: 'Geodésico',
      hint: 'Mapeamento geodésico: o zodíaco projetado sobre as longitudes da Terra (Greenwich = 0° de Áries, sempre tropical), independente da hora de nascimento',
    },
  },
  geoGrid: {
    mc: {
      title: 'Meridianos do MC',
      hint: 'Doze meridianos, a cada 30° a leste de Greenwich. Num mapa geodésico, cada um marca onde começa um signo do MC; o signo aparece no topo do mapa.',
    },
    asc: {
      title: 'Curvas do Ascendente',
      hint: 'Onde cada signo começa a nascer: todo local sobre uma curva tem 0° desse signo como Ascendente. Ativas por padrão enquanto não há linhas do mapa; sua escolha prevalece.',
    },
    zones: {
      title: 'Zonas sombreadas',
      hint: 'Preenche as doze zonas do MC: elemento como cor, modalidade como tom (Cardinal mais escuro, Mutável mais claro). A legenda no mapa mostra um elemento ou modalidade isolado.',
    },
    presentation: {
      title: 'Apresentação',
      hint: 'Intensifica o sombreamento das zonas de suave para forte, para mostrar as zonas a outra pessoa.',
    },
  },
  coordSystem: {
    mundo: {
      label: 'In Mundo',
      hint: 'As linhas usam a própria posição de cada corpo no céu (AR / dec). Idêntico ao In Zodiaco para o Sol, que fica na eclíptica; a maior diferença é em Plutão e na Lua.',
    },
    zodiaco: {
      label: 'In Zodiaco',
      hint: 'Os corpos são projetados na eclíptica antes de traçar as linhas (um padrão comum em ACG).',
    },
  },
  fortuneFormula: {
    hint: 'A Parte da Fortuna é uma Parte calculada de vitalidade e bem-estar material — um ponto na eclíptica, não um corpo no céu, então só um referencial zodiacal pode situá-la: suas linhas no mapa-múndi exigem a Projeção das linhas em In Zodiaco (ou o sistema de linhas Geodésico). Relocar o alfinete do mapa-múndi a recalcula na roda do mapa natal para esse local, enquanto as linhas no mapa-múndi mantêm sua Fortuna natal.',
    sect: {
      label: 'Por seita (diurna/noturna)',
      hint: 'Nascimentos de dia usam Ascendente + Lua − Sol; os de noite invertem para Ascendente + Sol − Lua. A convenção tradicional.',
    },
    ptolemaic: {
      label: 'Ptolomaica (fixa)',
      hint: 'Ascendente + Lua − Sol para todo mapa, de dia ou de noite. A convenção histórica alternativa.',
    },
  },
  rulership: {
    hint: 'A tabela de regências da dignidade essencial na roda do mapa. Moderna ACRESCENTA os três exteriores sem substituir ninguém: Marte mantém Escorpião ao lado de Plutão, e ambos estão em exílio em Touro, oposto a ele. Tradicional tira da tabela só as entradas dos planetas exteriores; nada mais muda.',
    traditional: {
      label: 'Tradicional',
      hint: 'Só a tabela dos sete planetas — Marte rege Escorpião; Saturno, Aquário; Júpiter, Peixes. Urano, Netuno e Plutão não regem nada, então não têm dignidade.',
    },
    modern: {
      label: 'Moderna',
      hint: 'Os mesmos sete, mais Plutão em Escorpião, Urano em Aquário e Netuno em Peixes. Esses três signos têm dois regentes, e cada entrada indica sua época.',
    },
  },
  inert: {
    fortuneMundo: 'Uma Parte é um ponto na eclíptica sem posição no céu, então o In Mundo não tem um local onde situá-la. Para ver esta linha, defina a projeção como In Zodiaco (Cálculo).',
    fortuneAdvanced: 'A Parte da Fortuna é uma leitura avançada — ative o Avançado para usá-la.',
    geodeticSidereal: 'O sistema de linhas Geodésico projeta o zodíaco TROPICAL sobre as longitudes da Terra, então não tem versão sideral. Defina o zodíaco como Tropical (Avançado) para usá-lo; sua escolha é mantida.',
    geodeticHeld: 'O Geodésico está em revisão enquanto verificamos como ele é desenhado — preferimos mantê-lo em espera a desenhar um mapa pelo qual não podemos responder. Sua escolha é mantida, não apagada; volte em breve.',
    skyHeldWhy: 'Indisponível em mapas geodésicos, que não giram com o céu.',
    skyHeldFix: 'Mude o sistema de linhas para Celeste, em Cálculo, para usá-lo.',
    skyHeld: 'Indisponível em mapas geodésicos, que não giram com o céu. Mude o sistema de linhas para Celeste, em Cálculo, para usá-lo.',
    skyHeldAction: 'Abrir Cálculo',
    skyHeldForNow: 'Indisponível em mapas geodésicos por enquanto.',
    skyHeldForNowFull: 'Indisponível em mapas geodésicos por enquanto. Mude o sistema de linhas para Celeste, em Cálculo, para usá-lo.',
    anglesHeld: 'Em mapas geodésicos, os ângulos de um local vêm das suas coordenadas, então não se movem com o tempo.',
    paransHeld: 'Os parans não são mostrados em mapas geodésicos.',
    paransHeldFull: 'Os parans não são mostrados em mapas geodésicos. Mude o sistema de linhas para Celeste, em Cálculo, para usá-lo.',
  },
  nodeType: {
    true: {
      label: 'Nodo verdadeiro',
      hint: 'O nodo verdadeiro (osculador) segue a órbita instantânea da Lua; oscila ±~1,5° em torno do médio e pode ficar direto por breves períodos (o padrão).',
    },
    mean: {
      label: 'Nodo médio',
      hint: 'A média suavizada de longo prazo; está sempre retrógrado, num ritmo constante.',
    },
  },
  houseSystem: {
    placidus: {
      label: 'Placidus',
      hint: 'Divisão temporal por semiarco (o padrão moderno comum)',
    },
    koch: {
      label: 'Koch',
      hint: 'Semiarco na latitude de nascimento (GOH)',
    },
    regiomontanus: {
      label: 'Regiomontanus',
      hint: 'Divisões iguais do equador celeste',
    },
    campanus: {
      label: 'Campanus',
      hint: 'Divisões iguais do primeiro vertical',
    },
    porphyry: {
      label: 'Porphyry',
      hint: 'Cada quadrante dividido em três em longitude eclíptica',
    },
    alcabitus: {
      label: 'Alcabitus',
      hint: 'Semiarco antigo sobre os arcos diurno / noturno',
    },
    meridian: {
      label: 'Meridiano',
      hint: 'Arcos iguais de 30° do equador a partir do MC, projetados por círculos horários; a 1ª cúspide é um Ponto Leste, não o Ascendente. Bem definido em qualquer latitude.',
    },
    morinus: {
      label: 'Morinus',
      hint: 'Arcos iguais do equador projetados por círculos que passam pelos polos da eclíptica; não usa Ascendente nem MC, então funciona sem problemas até em latitudes polares.',
    },
    whole: {
      label: 'Signos inteiros',
      hint: 'Cada casa é um signo inteiro, a partir do signo ascendente',
    },
    equal: {
      label: 'Casas iguais',
      hint: 'Casas de 30° medidas a partir do Ascendente',
    },
  },
  primaryRate: {
    ptolemy: {
      label: 'Ptolomeu (1°/ano)',
      hint: 'Um ano por grau.',
    },
    naibod: {
      label: 'Naibod (59′08″/ano)',
      hint: '0,985647° por ano, o movimento médio do Sol.',
    },
    cardan: {
      label: 'Cardano (59′12″/ano)',
      hint: '0,986667° por ano.',
    },
    'kepler-ra': {
      label: 'Movimento diário do Sol (AR)',
      hint: 'Chave de Kepler — o movimento diário do Sol natal em ascensão reta × anos.',
    },
    'solar-long': {
      label: 'Movimento diário do Sol (longitude)',
      hint: 'Movimento diário do Sol natal em longitude eclíptica × anos.',
    },
    'placidus-ra': {
      label: 'Arco solar verdadeiro (AR)',
      hint: 'Usa como chave a distância real que o Sol progredido percorreu até esta idade, em vez de um ritmo anual fixo. Como a velocidade do Sol varia durante o ano, o arco se acumula desigualmente — então esta chave fica um pouco à frente ou atrás das opções de ritmo fixo, conforme a estação do nascimento.',
    },
    user: {
      label: 'Chave do usuário',
      hint: 'Insira abaixo seus próprios graus por ano.',
    },
    control: {
      tip: 'A chave de tempo das direções primárias',
      hint: 'As direções primárias modelam a rotação diária: os ângulos do mapa avançam enquanto os corpos mantêm suas posições natais no céu. A chave é a medida do tempo — quanto arco se acumula por ano de vida. As escolas divergem, e a diferença é real: ao longo de uma vida, Ptolomeu e Naibod se afastam em mais de um ano.',
    },
  },
  positioning: {
    'relative-to-natal': {
      label: 'Ângulos natais',
      short: 'Natal',
      tip: 'Os ângulos do próprio mapa natal',
      hint: 'Mantém o referencial natal parado: só o movimento secundário dos próprios planetas move as linhas. A rotação diurna é removida. Responde: em que lugar da Terra este trânsito estaria caindo no Ascendente, MC, Descendente ou IC? As linhas derivam em semanas e meses, no ritmo de cada planeta.',
      returnHintSolar: 'Desenha os planetas da revolução em relação aos ângulos natais. O Sol da revolução volta ao seu grau natal, e o Sol não tem latitude eclíptica, então suas linhas caem exatamente sobre as linhas do Sol natal em qualquer projeção — o mesmo local todo ano.',
      returnHintLunar: 'Desenha os planetas da revolução em relação aos ângulos natais. A Lua da revolução volta à sua longitude natal, então, In Zodiaco, suas linhas caem sobre as linhas da Lua natal; In Mundo, ficam próximas, mas não exatas, porque a latitude da Lua mudou desde o nascimento.',
    },
    'transit-moment': {
      label: 'Ângulos de trânsito',
      short: 'Trânsito',
      returnLabel: 'Ângulos da revolução',
      returnShort: 'Revolução',
      tip: 'Os ângulos do próprio momento',
      returnTip: 'Os ângulos do próprio mapa da revolução',
      hint: 'Lê o céu no próprio referencial do momento, e as linhas têm movimento primário — todo o conjunto percorre 15° por hora e completa a volta uma vez por dia. A linha de cada corpo marca onde ele é de fato angular nesse instante. Não envolve mapa natal. Leia num instante, não ao longo de uma estação.',
      returnHint: 'Um mapa de revolução é um momento próprio, com seus próprios ângulos. O mapa-múndi é desenhado em relação aos ângulos da revolução, e não aos natais.',
    },
  },
  arcMethod: {
    'sa-long': {
      label: 'Arco solar — em longitude',
      angles: 'Avança os ângulos pela distância que o Sol progredido percorreu até o instante próprio desta sobreposição, medida ao longo da eclíptica.',
      bodies: 'Avança cada corpo pela distância que o Sol progredido deste mapa realmente percorreu, medida ao longo da eclíptica. O método clássico.',
    },
    'sa-ra': {
      label: 'Arco solar — em ascensão reta',
      angles: 'Avança os ângulos pela distância que o Sol progredido percorreu até o instante próprio desta sobreposição, medida ao longo do equador.',
      bodies: 'Avança cada corpo pela distância que o Sol progredido deste mapa realmente percorreu, medida ao longo do equador.',
    },
    'naibod-long': {
      label: 'Naibod, ritmo médio — em longitude',
      angles: 'Avança os ângulos no ritmo médio do Sol, medido ao longo da eclíptica, durante o intervalo próprio desta sobreposição.',
      bodies: 'Avança cada corpo no movimento anual médio do Sol, medido ao longo da eclíptica.',
    },
    'naibod-ra': {
      label: 'Naibod, ritmo médio — em ascensão reta',
      angles: 'Avança os ângulos no ritmo médio do Sol, medido ao longo do equador, durante o intervalo próprio desta sobreposição.',
      bodies: 'Avança cada corpo no movimento anual médio do Sol, medido ao longo do equador.',
    },
    headerAngles: 'Quanto os ângulos avançam',
    headerBodies: 'Quanto os corpos avançam',
  },
  progAngles: {
    natal: {
      label: 'Ângulos natais',
      short: 'Natal',
      tip: 'Os ângulos do próprio mapa natal',
      hint: 'Os planetas progredidos são lidos em relação aos ângulos natais. O referencial do mapa natal fica parado, então só os planetas se movem.',
    },
    progressed: {
      label: 'Ângulos progredidos',
      short: 'Progredido',
      tip: 'Os ângulos do próprio mapa progredido',
      hint: 'O mapa progredido tem um momento próprio — um dia após o nascimento para cada ano de vida —, então tem ângulos próprios. O mapa-múndi usa esses ângulos, e não os natais.',
      hintTertiary: 'O mapa terciário tem um momento próprio — um dia após o nascimento para cada mês trópico (27,32 dias) —, então tem ângulos próprios. O mapa-múndi usa esses ângulos, não os natais.',
    },
    idle: {
      tip: 'Sem efeito',
      hint: 'Os ângulos são mantidos no mapa natal, então nenhum arco é aplicado a eles. Escolher um cálculo aqui também muda o mapa-múndi para Ângulos progredidos.',
    },
  },
  eclipses: {
    kind: {
      total: 'Total',
      annular: 'Anular',
      hybrid: 'Híbrido',
      partial: 'Parcial',
      penumbral: 'Penumbral',
    },
    body: {
      solar: 'Solar',
      lunar: 'Lunar',
    },
    details: {
      maximum: 'Máximo',
      maximumValue: '{date} · {time} (UTC)',
      type: 'Tipo',
      central: 'central',
      nonCentral: 'não central',
      magnitude: 'Magnitude',
      gamma: 'Gama',
      saros: 'Série de Saros',
      lunation: 'Lunação',
      sunPosition: 'Grau do eclipse',
      sunPositionTip: 'O grau do eclipse no zodíaco — o Sol e a Lua se encontram aqui, em {sign}.',
      moonPositionTip: 'O grau da Lua eclipsada no zodíaco, em {sign} — ela fica em oposição ao Sol.',
      hemisphere: 'Hemisfério',
      north: 'Norte',
      south: 'Sul',
      duration: 'Duração máx.',
      width: 'Largura da faixa',
      widthValue: '{n} km',
      umbralMag: 'Magnitude umbral',
      penumbralMag: 'Magnitude penumbral',
      penumbralDur: 'Fase penumbral',
      partialDur: 'Fase parcial',
      totalDur: 'Fase total',
    },
    contacts: {
      heading: 'Contatos natais',
      none: 'Nenhum contato dentro de 3° — este eclipse passa pelo mapa em silêncio.',
      aspect: {
        conjunction: 'em conjunção',
        square: 'em quadratura',
        opposition: 'em oposição',
      },
      asc: 'Ascendente',
      mc: 'Meio do Céu',
    },
    otherLines: {
      title: 'Outras linhas',
      hint: 'Tudo no mapa-múndi menos o eclipse, apagado num clique para ler só a trajetória — se desativado, prevalece sobre os outros botões de linhas. A roda do mapa astral e os dados ficam.',
    },
    chartLines: {
      title: 'Mapa do eclipse',
      hint: 'O mapa do máximo do eclipse — o céu fixado naquele instante — adicionado à roda do mapa como um segundo anel ao lado do mapa natal.',
    },
    isoStep: {
      '10': {
        label: '10%',
        hint: 'Nove curvas — uma grade de referência densa.',
      },
      '20': {
        label: '20%',
        hint: 'Quatro curvas — um meio-termo equilibrado.',
      },
      '25': {
        label: '25%',
        hint: 'Três curvas em passos de um quarto (a convenção clássica dos mapas de eclipse).',
      },
    },
  },
  lineType: {
    MC: {
      hint: 'Meio do Céu (carreira, vida pública)',
    },
    IC: {
      hint: 'Fundo do Céu (lar, raízes)',
    },
    ASC: {
      hint: 'Ascendente (eu, identidade)',
    },
    DSC: {
      hint: 'Descendente (relacionamentos)',
    },
    VX: {
      hint: 'Vértex (encontros do destino); também adiciona o Vx à roda do mapa',
    },
    AVX: {
      hint: 'Antivértex (a extremidade leste do eixo); também adiciona o Avx à roda',
    },
  },
} as const;
