// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/synastryHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const synastryHud = {
  title: 'Sinastria',
  chooseComparison: 'Escolher mapa de comparação',
  choosePrompt: 'Escolha um mapa para comparar',
  barToggle: {
    show: 'Mostrar opções de sinastria',
    hide: 'Ocultar opções de sinastria',
  },
  method: {
    label: 'Tipo',
    davison: {
      label: 'Davison',
      hint: 'Ponto médio no tempo e no local dos dois mapas, calculado como um mapa real.',
    },
    composite: {
      label: 'Pontos médios comp.',
      hint: 'Cada planeta e ângulo no ponto médio dos dois mapas astrais, cada planeta com latitude e declinação reais. O referencial do mapa-múndi segue o Meio do Céu composto.',
    },
  },
  generate: {
    label: 'Gerar',
    hint: 'Criar o mapa, torná-lo ativo e limpar o mapa de comparação da sinastria.',
    needPartner: 'Escolha primeiro um mapa de comparação acima.',
    compositeParent: 'Um mapa composto não pode ser combinado de novo; escolha dois mapas comuns.',
  },
} as const;
