// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/timeline.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const timeline = {
  nubMode: {
    transits: 'Trânsitos',
    progressed: 'Prog. secundária',
    'tertiary-progressed': 'Prog. terciária',
    'solar-arc': 'Arco solar',
    'primary-directions': 'Primárias',
    cyclo: 'CCG',
  },
  nubFallback: 'Sobreposição',
  barToggle: {
    show: 'Mostrar a barra da linha do tempo',
    hide: 'Ocultar a barra da linha do tempo',
    hint: 'A régua de datas + os controles de reprodução. A alça continua visível de qualquer forma.',
  },
  drawer: {
    show: 'Mostrar opções de exibição',
    hide: 'Ocultar opções de exibição',
  },
  cyclo: {
    label: 'Combinação',
    spName: 'Planetas pessoais progredidos',
    spTip: 'Sp — progredido (progressão secundária)',
    spHint: 'Sol, Lua, Mercúrio, Vênus e Marte são lidos nas posições progredidas secundárias — o ritmo de um dia por ano os mantém legíveis junto aos exteriores. Suas linhas têm a etiqueta Sp.',
    trName: 'Corpos exteriores em trânsito',
    trTip: 'Tr — em trânsito',
    trHint: 'Tudo de Júpiter para fora — mais os nodos, Lilith, Quíron e os asteroides — é lido na sua posição real em trânsito. Suas linhas têm a etiqueta Tr.',
  },
  positioning: {
    groupAria: 'Referencial da sobreposição',
    lockedNoTime: 'Hora de nascimento desconhecida — não há referencial natal a manter, então o mapa só pode mostrar o céu do momento.',
    heldForReturn: 'Em espera enquanto o mapa-múndi está em uma revolução — um mapa de revolução só é ele mesmo no próprio referencial. Escolher esta opção encerra a espera e devolve o mapa-múndi a esse referencial.',
  },
  units: {
    minute: 'Minuto',
    hour: 'Hora',
    day: 'Dia',
    week: 'Semana',
    month: 'Mês',
    year: 'Ano',
  },
  unitsLower: {
    minute: 'minuto',
    hour: 'hora',
    day: 'dia',
    week: 'semana',
    month: 'mês',
    year: 'ano',
  },
  minorLabel: {
    minute: '1 min',
    hour: '10 min',
    day: '6 horas',
    week: '1 dia',
    month: '5 dias',
    year: '1 mês',
  },
  stepWords: {
    minute: '{n, plural, =1 {minuto} other {minutos}}',
    hour: '{n, plural, =1 {hora} other {horas}}',
    day: '{n, plural, =1 {dia} other {dias}}',
    week: '{n, plural, =1 {semana} other {semanas}}',
    month: '{n, plural, =1 {mês} other {meses}}',
    year: '{n, plural, =1 {ano} other {anos}}',
  },
  stepSymbol: {
    minute: '{n, plural, other {min}}',
    hour: '{n, plural, other {h}}',
    day: '{n, plural, other {d}}',
    month: '{n, plural, =1 {mês} other {meses}}',
  },
  transport: {
    stepBack: 'Retroceder {count} {unit}',
    stepForward: 'Avançar {count} {unit}',
    stepBackAria: 'Retroceder',
    stepForwardAria: 'Avançar',
    play: 'Reproduzir',
    pause: 'Pausar',
    stepAmountIn: {
      minute: 'Tamanho do passo, em minutos',
      hour: 'Tamanho do passo, em horas',
      day: 'Tamanho do passo, em dias',
      month: 'Tamanho do passo, em meses',
    },
    stepAmountInAria: {
      minute: 'Tamanho do passo em minutos',
      hour: 'Tamanho do passo em horas',
      day: 'Tamanho do passo em dias',
      month: 'Tamanho do passo em meses',
    },
  },
  ruler: {
    aria: 'Percorrer a data',
  },
  now: {
    label: 'Agora',
    tip: 'Ir para o momento atual',
  },
  returns: {
    label: 'Revoluções',
    reframes: 'Toma emprestado o referencial do mapa para o próprio momento da revolução. No referencial natal, o corpo que retorna fica preso ao seu grau natal, então suas linhas nunca se moveriam de uma revolução para a seguinte. Seu referencial fica em espera, não é apagado, e volta quando você sai da revolução.',
    chip: {
      solar: 'Revolução solar',
      lunar: 'Revolução lunar',
      tip: 'O mapa está em uma revolução',
      hint: 'O referencial da sobreposição é tomado emprestado enquanto o mapa-múndi está em uma revolução, pois um mapa de revolução tem os próprios ângulos. O referencial anterior fica em espera por baixo e volta quando você sai. Passar de uma revolução a outra com as setas mantém a espera.',
      clear: 'Sair da revolução',
      clearHint: 'Devolve o referencial da sobreposição ao que era antes. A data fica onde está.',
      clearAria: 'Sair da revolução e restaurar o referencial da sobreposição',
    },
    solar: {
      name: 'Solar',
      chartName: 'Revolução solar',
      snap: 'Revolução solar mais próxima',
      snapAria: 'Ir para a revolução solar mais próxima',
      prev: 'Revolução solar anterior',
      prevAria: 'Revolução solar anterior',
      next: 'Próxima revolução solar',
      nextAria: 'Próxima revolução solar',
    },
    lunar: {
      name: 'Lunar',
      chartName: 'Revolução lunar',
      snap: 'Revolução lunar mais próxima',
      snapAria: 'Ir para a revolução lunar mais próxima',
      prev: 'Revolução lunar anterior',
      prevAria: 'Revolução lunar anterior',
      next: 'Próxima revolução lunar',
      nextAria: 'Próxima revolução lunar',
    },
  },
  scale: {
    label: 'Escala',
  },
  rate: {
    label: 'Chave',
  },
  dateField: {
    tipChartZone: 'Momento de trânsito / progredido, no fuso horário do mapa',
    tipChartZonePlace: 'Momento de trânsito / progredido, no horário de {place} — o local de nascimento do mapa, que pode não ser onde você está',
    tipUtc: 'Momento de trânsito / progredido, em UTC',
  },
  datePicker: {
    open: 'Editar data e hora',
    title: 'Definir data e hora',
    scrollKey: 'Role',
    scrollHint: 'para aumentar ou diminuir',
    apply: 'Definir',
    yearRange: 'Este seletor vai de {min} a {max} — um ano fora desse intervalo é ajustado ao extremo mais próximo.',
  },
  labelFull: {
    transits: 'Trânsitos · {datetime} (UTC)',
    progressed: 'Prog. secundária · idade {years}',
    'tertiary-progressed': 'Prog. terciária · idade {years}',
    'solar-arc': 'Arco solar · {deg}°',
    'primary-directions': 'Direções primárias · {deg}°',
    cyclo: 'Ciclo·carto·grafia · {datetime} (UTC)',
    synastry: 'Sinastria · {partner}',
    eclipses: 'Eclipse · {datetime} (UTC)',
  },
  measure: {
    progressedAge: 'Idade {years}',
  },
} as const;
