// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/topNav.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const topNav = {
  overlay: {
    menuLabel: 'Sobreposição',
    none: {
      label: 'Nenhuma',
      hint: 'Só o mapa natal, sem nenhuma técnica de tempo aplicada.',
    },
    blocked: {
      composite: 'Um mapa composto é um mapa de pontos médios, não um momento — não há instante de nascimento para esta técnica avançar. Mude para um mapa de uma só pessoa para usá-la.',
      'no-time': 'A hora de nascimento deste mapa é desconhecida, então não há um momento natal exato para avançar — uma técnica baseada nele estaria inventando esse momento em silêncio. Adicione uma hora de nascimento para usá-la.',
      davison: 'Este mapa já é um mapa de duas pessoas, então não há mais ninguém para adicionar. Mude para um mapa de uma só pessoa para montar uma sinastria.',
    },
    modes: {
      transits: {
        label: 'Trânsitos',
        desc: 'Onde os planetas estão agora, sobre o seu mapa natal.',
      },
      progressed: {
        label: 'Prog. secundária',
        tipTitle: 'Progressões secundárias',
        desc: 'Progressões secundárias: um desdobramento simbólico de um dia para cada ano.',
      },
      'tertiary-progressed': {
        label: 'Prog. terciária',
        tipTitle: 'Progressões terciárias',
        desc: 'Progressões terciárias: um dia para cada mês trópico (27,32 dias), um ponteiro mais preciso para a cronologia.',
      },
      'solar-arc': {
        label: 'Arco solar',
        desc: 'Cada ponto avançado pelo arco do Sol de um grau por ano.',
      },
      'primary-directions': {
        label: 'Direções primárias',
        desc: 'Um antigo método de previsão movido pela rotação do céu.',
      },
      cyclo: {
        label: 'Ciclocartografia',
        tipTitle: 'Ciclocartografia (CCG)',
        desc: 'O híbrido de Jim Lewis: planetas pessoais em progressão secundária com os trânsitos de Júpiter em diante, num só mapa.',
      },
      synastry: {
        label: 'Sinastria',
        desc: 'O mapa de outra pessoa sobreposto ao seu, para relacionamentos.',
      },
      eclipses: {
        label: 'Eclipses',
        desc: 'Trajetórias de eclipses solares e curvas de magnitude, além de onde um eclipse lunar é visível, em todo o mapa.',
      },
    },
  },
  status: {
    natal: 'NATAL',
    hover: 'CURSOR',
    pinned: 'FIXADO',
    'natal-pinned': 'ALFINETE NATAL',
  },
  sidebarToggle: {
    showAria: 'Mostrar a barra lateral do mapa',
    hideAria: 'Ocultar a barra lateral do mapa',
    showTip: 'Mostrar o mapa da barra lateral',
    hideTip: 'Ocultar a barra lateral',
  },
  pin: {
    centerTip: 'Centralizar o mapa no alfinete',
    pinNatalTip: 'Pôr o alfinete no local natal',
    controlsTip: 'Controles do alfinete do mapa',
  },
  tools: {
    menuLabel: 'Ferramentas',
    measure: 'Medir distância',
    measureItem: 'Medir',
    measureHint: 'Clique e arraste no mapa para medir a distância de círculo máximo',
    toolbarHint: '{click} e {drag} no mapa para medir{rightExit}',
    measureKm: '{n} km',
    measureMi: '{n} mi',
    snap: 'Encaixar',
    snapTip: 'Encaixar a extremidade nas linhas do mapa (ou segure Shift)',
    slideItem: 'Deslizar',
    slideHint: 'Deslizar o mundo sob as linhas natais fixas — avança o tempo para mostrar como os parans se formam ao longo do dia. Funciona na vista plana ou no globo.',
    slideUnavailable: 'O Deslizar precisa das linhas natais desenhadas. Fica indisponível enquanto a opção Linhas natais estiver desativada (Avançado ▸ Linhas, Shift+N), se Outras linhas as tiver apagado ou se uma sobreposição estiver no lugar do mapa.',
    slideToolbarHint: '{pan} para deslizar o mundo sob as linhas fixas',
    slideNudgeBack1h: 'Voltar uma hora',
    slideNudgeBack4m: 'Voltar quatro minutos (≈ 1° de giro)',
    slideNudgeFwd4m: 'Avançar quatro minutos (≈ 1° de giro)',
    slideNudgeFwd1h: 'Avançar uma hora',
    slideReset: 'Voltar ao céu natal',
    slidePrevEvent: 'Ir para o nascer, a culminação ou o ocaso anterior no ponto ativo',
    slideNextEvent: 'Ir para o próximo nascer, culminação ou ocaso no ponto ativo',
    slideElapsedTip: 'Tempo deslizado desde o momento do mapa',
    slideClockTip: 'Hora do relógio e data no local de nascimento, no fuso do mapa',
    slideAngleTip: 'Rotação em torno do polo',
    captureItem: 'Captura',
    captureHint: 'Enquadrar o mapa e exportá-lo como PNG — defina a proporção de aspecto, escolha o que incluir e depois baixe ou copie.',
    captureToolbarHint: '{pan} e {zoom} para compor dentro do enquadramento{escExit}',
    hintKey: {
      click: 'Clique',
      tap: 'Toque',
      doubleClick: 'Clique {icon} duas vezes',
      doubleTap: 'Toque {icon} duas vezes',
      drag: 'Arraste',
      pan: 'Mova o mapa',
      zoom: 'Ajuste o zoom',
      esc: 'Esc',
      rightClick: 'Clique {icon} com o botão direito',
      toExit: 'para sair',
    },
  },
  view: {
    menuLabel: 'Exibir',
    coordinates: 'Coordenadas',
    coordinatesHint: 'Dados ao vivo do local, das coordenadas e dos ângulos do mapa relocado no ponto ativo.',
    minimap: 'Minimapa',
    minimapHint: 'A roda do mapa natal, pequena no canto enquanto você explora o mapa-múndi.',
    settings: 'Configurações',
    settingsHint: 'Temas, sistemas de casas, zodíaco e como o mapa astral e o mapa-múndi são desenhados.',
    teleport: 'Teletransporte',
    teleportHint: 'Pesquisar qualquer local e voar com o mapa direto até ele.',
    skyTimes: 'Horários do céu',
    skyTimesHint: 'Os horários diários de nascer, culminação e ocaso no ponto ativo, na faixa inferior.',
    localSpace: 'Espaço local',
    localSpaceHint: 'Linhas de direção da origem do mapa até cada planeta — sua bússola do espaço local.',
    info: 'Info',
    infoHint: 'Um indicador no canto que resume os sistemas ativos do mapa — referencial das linhas, casas e zodíaco.',
    guides: 'Guias',
    guidesHint: 'Rever os guias de introdução como um glossário dos controles do mapa.',
  },
} as const;
