// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Português (Brasil) for ../en/wheel.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../pt.lock.json). Keys, order and layout are rewritten on every run.
export const wheel = {
  house: 'Casa {number, selectordinal, other {#}}',
  signMeanings: {
    aries: 'Fogo · Cardinal · iniciativa',
    taurus: 'Terra · Fixo · estabilidade',
    gemini: 'Ar · Mutável · curiosidade',
    cancer: 'Água · Cardinal · acolhimento',
    leo: 'Fogo · Fixo · autoexpressão',
    virgo: 'Terra · Mutável · precisão',
    libra: 'Ar · Cardinal · equilíbrio',
    scorpio: 'Água · Fixo · intensidade',
    sagittarius: 'Fogo · Mutável · aventura',
    capricorn: 'Terra · Cardinal · ambição',
    aquarius: 'Ar · Fixo · inovação',
    pisces: 'Água · Mutável · imaginação',
  },
  houseMeanings: {
    h1: 'Eu · identidade · primeiras impressões',
    h2: 'Dinheiro · bens · autoestima',
    h3: 'Comunicação · irmãos · aprendizado',
    h4: 'Lar · família · raízes',
    h5: 'Criatividade · romance · filhos',
    h6: 'Trabalho · saúde · rotina diária',
    h7: 'Parceria · casamento · o “outro”',
    h8: 'Intimidade · recursos compartilhados · renascimento',
    h9: 'Viagens · filosofia · estudos superiores',
    h10: 'Carreira · reputação · vida pública',
    h11: 'Amigos · comunidade · esperanças',
    h12: 'Solidão · o invisível · espiritualidade',
  },
  tip: {
    longitude: 'Longitude {lon}',
    latitude: 'Latitude {lat}',
    minorCluster: '{n, plural, one {# corpo menor} many {# de corpos menores} other {# corpos menores}}',
    minorLine: '{name} {lon}',
    minorMore: 'mais {n}',
    overlayMinor: '{name} · {chart}',
    overlayMinorCluster: '{chart}: {n, plural, one {# corpo menor} many {# de corpos menores} other {# corpos menores}}',
    minorLineOverlay: '{name} {lon} · {chart}',
    fortuneGeodetic: 'A partir do Ascendente geodésico',
    fortuneGeodeticDay: 'A partir do Ascendente geodésico, como nascimento de dia. Com nascimento à noite, seria espelhada em relação ao Ascendente',
    fortuneGeodeticNight: 'A partir do Ascendente geodésico, como nascimento à noite. Com nascimento de dia, seria espelhada em relação ao Ascendente',
    rangeNote: 'Hora de nascimento desconhecida: em qualquer ponto deste intervalo na data de nascimento',
  },
  planetMeanings: {
    Sun: 'Identidade · vitalidade · ego',
    Moon: 'Emoções · instinto · necessidades',
    Mercury: 'Mente · comunicação',
    Venus: 'Amor · beleza · valores',
    Mars: 'Impulso · energia · ação',
    Jupiter: 'Crescimento · sorte · expansão',
    Saturn: 'Disciplina · estrutura · limites',
    Uranus: 'Mudança · liberdade · insight',
    Neptune: 'Sonhos · intuição · espírito',
    Pluto: 'Poder · transformação',
    NorthNode: 'Caminho da alma · crescimento',
    SouthNode: 'Passado · dons inatos',
    Lilith: 'Sombra · instinto bruto',
    Chiron: 'O curador ferido',
    Ceres: 'Acolhimento · ciclos',
    Pallas: 'Sabedoria · estratégia',
    Juno: 'Compromisso · parceria',
    Vesta: 'Foco · devoção',
    Fortune: 'Fortuna · vitalidade · facilidade',
  },
  angles: {
    As: {
      title: 'Ascendente',
      sub: 'Signo ascendente, o eu e as primeiras impressões',
    },
    Ds: {
      title: 'Descendente',
      sub: 'Relacionamentos e o “outro”',
    },
    Mc: {
      title: 'Meio do Céu (Medium Coeli)',
      sub: 'Carreira, reputação e vida pública',
    },
    Ic: {
      title: 'Fundo do Céu',
      sub: 'Lar, raízes e vida privada',
    },
    Vx: {
      title: 'Vértex',
      sub: 'Encontros predestinados e pontos de virada; o ponto oeste do primeiro vertical',
    },
    Avx: {
      title: 'Antivértex',
      sub: 'A extremidade leste do eixo do Vértex, oposta ao Vértex',
    },
  },
  motion: {
    retrograde: 'Retrógrado',
    stationary: 'Estacionário',
  },
} as const;
