// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/aspectLinesHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const aspectLinesHud = {
  title: 'Açılar',
  closeAria: 'Açılar’ı kapat',
  closeHint: 'Bu pencereyi kapatın. Çizgiler açık kalır — onları Ayarlar ▸ Gelişmiş ▸ Çizgiler bölümünden kapatın.',
  filters: {
    label: 'Filtreler',
  },
  harmonious: {
    title: 'Uyumlu',
    hint: 'Altmışlık ve üçgen çizgileri. Geometri bakımından tek bir aile: her çizgi, ekseninin bir ucundan altmışlık, diğer ucundan üçgen olarak okunur.',
  },
  challenging: {
    title: 'Zorlayıcı',
    hint: 'Kare çizgileri — bir eksenin bir ucuna kare olan, diğer ucuna da karedir; bu yüzden bu aile tek başına durur.',
  },
  mcAxis: {
    title: 'Tepe Noktası ekseni',
    hint: 'MC ile açı yapan çizgiler (her biri IC ucundan da okunabilir).',
  },
  ascAxis: {
    title: 'Ufuk ekseni',
    hint: 'Yükselenle açı yapan çizgiler (her biri Alçalandan da okunabilir).',
  },
  orbs: {
    label: 'Açı orbları',
    infoTitle: 'Açı orbları',
    infoHint: 'Harita çarkında ve açı listelerinde tam açıdan en fazla uzaklık (derece). Dünya haritasındaki açı çizgileri tam açıyı işaretler ve orb almaz.',
  },
} as const;
