// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/autoFlip.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const autoFlip = {
  suppress: 'Bir daha gösterme',
  ok: 'Anladım',
  'overlay-frame-held': {
    title: 'Katman çerçevesi Dönüş köşeleri üzerinde tutulur',
    body: 'Dönüş haritası, kendi köşeleriyle kendine ait bir andır; harita artık natal köşelere göre değil, bu köşelere göre çiziliyor. Önceki çerçeve silinmedi, beklemede — dönüşten çıkınca ya da kutucuktaki ✕ ile hemen geri gelir.',
  },
  'line-system-held': {
    title: 'Jeodezik beklemede',
    body: 'Jeodezik çizgi sistemi tropikal zodyağı Dünya’nın boylamlarına yerleştirir; bu yüzden çizilecek bir sidereal sürümü yoktur. Seçiminiz silinmedi, beklemede — zodyağı yeniden Tropikal yapın, geri gelir.',
  },
  'line-projection': {
    title: 'Bu çizgiler In Mundo çiziliyor',
    body: 'Her program, bir gök cisminin çizgisini çizebilmek için önce onun nerede “olduğuna” karar vermek zorundadır. In Mundo onu gökyüzünde durduğu yere, enlemiyle birlikte yerleştirir. In Zodiaco ise önce bu enlemi ekliptiğe indirger.',
  },
  'theme-held': {
    title: 'Temanız beklemede',
    body: 'Seçtiğiniz tema şu anda kullanılamıyor; bu yüzden uygulama, ondan önce kullandığınız temayla gösteriliyor. Hiçbir şey silinmedi: yeniden kullanılabilir olduğunda bıraktığınız gibi geri gelir.',
  },
  'theme-edits-held': {
    title: 'Kendi sürümünüz beklemede',
    body: 'Bu temanın size ait sürümü şu anda kullanılamıyor; bu yüzden onun yerine standart sürümü gösteriliyor. Hiçbir şey silinmedi: sizinki, yeniden kullanılabilir olduğunda bıraktığınız gibi geri gelir.',
  },
  'language-detected': {
    title: 'Artık tarayıcınızın dilinde',
    body: 'AstroLina’nın artık tarayıcınızın istediği dilde bir çevirisi var ve bu dilde açılıyor. İngilizceye dönmek ya da başka bir dil seçmek için şu yolu kullanın: {route}.',
  },
  'language-held': {
    title: 'Seçtiğiniz dil beklemede',
    body: 'Seçtiğiniz dil bu cihazda çevrilir; bu, şu anda burada mümkün olmadığı için uygulama her zamanki dilinde gösteriliyor. Seçiminiz korunuyor, silinmedi. Başka bir dil seçmek için şu yolu kullanın: {route}.',
  },
} as const;
