// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/captureHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const captureHud = {
  title: 'Görüntü Alma',
  closeAria: 'Görüntü Alma penceresini kapat',
  closeHint: 'Görüntü Alma aracını kapatın.',
  subject: {
    label: 'Görüntü Alma',
    map: 'Harita',
    mapHint: 'Çerçevelenen haritayı dışa aktarın — dünyanın üzerinde çizgileriniz, yanlarında isteğe bağlı bir panel olarak çark.',
    chart: 'Çark',
    chartHint: 'Yalnızca çarkı dışa aktarın: kenar çubuğundaki gibi çizilen çark (ya da konumlar) çerçeveyi tam doldurur — açılar, katman halkası dahil. Dünya haritası yok, resim yazısı aynı.',
  },
  aspect: {
    label: 'Çerçeve',
    square: '1:1',
    squareHint: 'Kare çerçeve (1:1) — gönderiler ve profil resimleri için en iyisi.',
    portrait: '4:5',
    portraitHint: 'Dikey çerçeve (4:5) — telefon akışları için uzun biçim.',
    landscape: '16:9',
    landscapeHint: 'Yatay çerçeve (16:9) — geniş; slaytlar ve başlık görselleri için.',
  },
  transparent: {
    title: 'Saydam (Yerel Uzay)',
    hint: 'Temiz bir yerel uzay dışa aktarımı için tek anahtar: çizgi oklarını gizler, çizgileri haritanın geri kalanı gibi etiketler (etiketler çerçeve kenarlarına yaslanır, yön dereceleri gösterilmez) ve altlık haritayı boş bırakır; böylece dışa aktarılan görüntünün arka planı saydam kalır — bir kat planının ya da kendi arka planınızın üzerine yerleştirmeye hazır. Görüntü Alma ya da Yerel Uzay kapandığında her şey geri gelir.',
    needLs: 'Önce Yerel Uzay aracını açın (Görünüm ▸ Yerel Uzay) — bu temiz, saydam dışa aktarım yerel uzay pusulası ve çizgileri üzerine kuruludur.',
  },
  lsLabels: {
    name: {
      title: 'Ad etiketi',
      hint: 'Yerel uzay etiketinde her gezegenin adını simgesinden sonra yazdırın (ör. “♂ Mars”).',
    },
    degrees: {
      title: 'Dereceler',
      hint: 'Her yerel uzay çizgisinin yönünü çizgi boyunca, etiketinin hemen iç tarafına, pusula merkezine doğru yazdırın.',
    },
  },
  view: {
    none: 'Yok',
    noneHint: 'Çerçevede harita ayrıntısı yok — yalnızca dünya haritası, raptiye, kenar etiketleri ve resim yazısı.',
    wheel: 'Çark',
    wheelHint: 'Haritayı çerçevenin içinde bir çark olarak gösterin — kenar çubuğundakiyle aynı çark. Gezegenler / Köşeler anahtarları onu doldurur; Denge altına element·nitelik tablosunu ekler.',
    list: 'Liste',
    listHint: 'Haritayı gezegen / köşe konumlarının listesi olarak gösterin (element·nitelik sayımıyla birlikte); satırlar kenar çubuğundakilerle aynı.',
    phoneTitle: 'Telefonlarda kullanılamıyor',
    phoneHint: 'Telefon boyutundaki bir çerçeve, çarkı ya da listeyi dünya haritasının yanında net gösteremeyecek kadar küçük; bu yüzden ayrıntılar burada kapalı kalır. Çarkı tek başına dışa aktarmak için Görüntü Alma seçimini Çark yapın — çark böylece çerçeveyi doldurur ve bu boyutta düzgün okunur.',
    tooSmallHint: 'Bu çerçeve, çarkı dünya haritasının yanında gösteremeyecek kadar küçük — çark kenarı kesik çizilirdi. Daha geniş bir çerçeve seçin (en çok yer 16:9’da), pencereyi büyütün, çarka yerini geri vermek için Denge anahtarını kapatın ya da çarkı tek başına aktarmak için Görüntü Alma seçimini Çark yapın.',
    tooSmallBody: 'Bu çerçeveye dünya haritasının yanında okunaklı bir çark sığmıyor, bu yüzden ayrıntılar kapalı. Çark seçilerek alınan görüntüde çark çerçevenin tamamını kaplar.',
    switchToChart: 'Harita çarkını tek başına al',
    tooSmallCardHint: 'Bu çerçeve çarka tam bir haritanın gerektirdiği alanı veremiyor — açılar ve katman halkası burada olandan daha fazla genişlik ister, geniş ve basık bir çerçeve de çarka neredeyse hiç yükseklik bırakmaz. 1:1 ya da 4:5 seçin, pencereyi büyütün, çarka yerini geri vermek için Denge anahtarını kapatın ya da bunun yerine konumları Liste olarak alın.',
    tooSmallCardBody: 'Bu çerçeve tam haritayı çizmek için çok küçük, bu yüzden onun yerine konumlar gösteriliyor. Daha uzun bir pencere — ya da 1:1 veya 4:5 oranında bir çerçeve — çarka ihtiyaç duyduğu alanı verir.',
    clippedBody: 'Bazı ayrıntılar bu çerçeveye sığmıyor ve dışa aktarımda kesilecek. Daha geniş bir çerçeve, daha büyük bir pencere ya da daha az grup deneyin.',
  },
  extras: {
    label: 'Ayrıntılar',
    angles: 'Köşeler',
    anglesHint: 'Haritanın köşelerini (AS, MC, DS, IC…) panele, gezegenlerden sonra ekleyin.',
    balance: 'Denge',
    balanceHint: 'Element + nitelik dengesini ekleyin — hangi gezegenlerin Ateş/Toprak/Hava/Su ve Öncü/Sabit/Değişken gruplarına düştüğü.',
  },
  caption: {
    label: 'Resim yazısı',
    name: 'Ad',
    nameHint: 'Harita adını alttaki resim yazısında gösterin.',
    date: 'Tarih',
    dateHint: 'Doğum tarihini alttaki resim yazısında gösterin.',
    time: 'Saat',
    timeHint: 'Doğum saatini alttaki resim yazısında gösterin.',
    location: 'Konum',
    locationHint: 'Yeri alttaki resim yazısında gösterin: doğum yeri ya da bir raptiye bıraktığınızda raptiyeniz.',
    coordinates: 'Koordinatlar',
    coordinatesHint: 'Yerin tam enlem ve boylamını resim yazısında gösterin: doğum yeri ya da bir raptiye bıraktığınızda raptiyeniz.',
    calculations: 'Hesaplamalar',
    calculationsHint: 'Etkin hesaplama sistemlerini (Bilgi görünümündeki satırın aynısı) ve çizili olduğu sürece zaman katmanını tarihiyle birlikte alttaki resim yazısında gösterin.',
    discreet: 'Gizlilik modu açık; bu yüzden ad, doğum tarihi ve saati burada ve dışa aktarılan görüntüde gizlenir. Göstermek için P tuşuna basın.',
  },
  calcOverlay: {
    transits: 'Transitler',
    progressed: 'İkincil progres',
    'tertiary-progressed': 'Üçüncül progres',
    'solar-arc': 'Güneş yayı',
    'primary-directions': 'Primer direksiyonlar',
    cyclo: 'CCG',
  },
  share: {
    title: 'Paylaş',
    hint: 'Görüntüyü kaydetmek ya da göndermek için cihazınızın paylaşım menüsünü açın (mobil cihazlar ve desteklenen masaüstleri).',
    sheetTitle: 'AstroLina Kartografi',
    sheetText: 'AstroLina — meraklı zihinler için web tabanlı astrokartografi',
  },
  download: {
    title: 'İndir',
    hint: 'Çerçevelenen görünümü PNG dosyası olarak kaydedin.',
  },
  copy: {
    title: 'Kopyala',
    hint: 'Çerçevelenen görünümü yapıştırmaya hazır biçimde panoya kopyalayın.',
    done: 'Kopyalandı',
  },
  link: {
    title: 'Bağlantıyı kopyala',
    hint: 'Bu haritayı ve görünümü açan bir bağlantı kopyalayın — doğum bilgileri bağlantıyla taşınır, bu yüzden onu yalnızca bunları görmesine izin verilen kişilerle paylaşın.',
    done: 'Bağlantı kopyalandı',
    warnAria: 'Paylaşım bağlantısı gizlilik uyarısı',
    warnBody: 'NOT: Bu bağlantı, haritanın tüm doğum bilgilerini (tarih, saat ve yer) taşır.',
    warnSuppress: 'Bir daha hatırlatma',
    warnConfirm: 'Bağlantıyı kopyala',
    warnCancel: 'İptal',
  },
  busy: 'İşleniyor…',
  failed: 'Dışa aktarma başarısız oldu — lütfen yeniden deneyin.',
  failedReason: {
    'no-frame': 'Harita görünümü hazır değildi. Görüntü Alma aracını yeniden açıp bir kez daha deneyin.',
    'no-canvas': 'Bu tarayıcı dışa aktarım için bir çizim yüzeyi sağlamadı.',
    'taint-basemap': 'Harita döşemeleri dışa aktarılmayı reddetti. Genellikle izleme önleme ya da bir içerik engelleyici buna yol açar — bu siteye izin verin, sonra yeniden deneyin.',
    encode: 'Görüntü kodlanamayacak kadar büyüktü. Daha küçük bir çerçeve oranı deneyin.',
    overlay: 'Resim yazısı ve etiketler çizilemedi, bu yüzden görüntü oluşturulmadı. Uygulamayı yeniden yükleyip tekrar deneyin.',
  },
} as const;
