// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/chartSwitcher.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const chartSwitcher = {
  noChart: 'Seçili harita yok',
  tip: 'Harita değiştirin, düzenleyin veya ekleyin',
  tabHint: '{key} tuşu sizi önceki haritanıza götürür — son beş harita arasında dolaşmak için basmaya devam edin.',
  empty: 'Henüz kayıtlı harita yok.',
  searchAdd: 'Ara + ad ekle',
} as const;
