// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/chartWheel.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const chartWheel = {
  resizeLabel: 'Çark boyutunu değiştir',
  shrink: 'Çarkı küçült',
  enlarge: 'Çarkı büyüt',
  openSidebar: 'Tam çarkı aç',
  openSidebarHint: 'Açılar ve gezegen tablosuyla daha büyük bir çark, kenar çubuğunda.',
  openSidebarLabel: 'Harita kenar çubuğunu göster',
  placeholder: 'Seçili harita yok',
  noChart: 'HARİTA YOK (CCG)',
} as const;
