// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/chartManager.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const chartManager = {
  dialogLabel: 'Haritalar',
  title: 'Haritalarım',
  comparisonTitle: '{name} ile sinastri',
  comparisonLabel: 'Sinastri',
  searchPlaceholder: 'Ad veya yer arayın…',
  searchLabel: 'Haritalarda ara',
  clearSearch: 'Aramayı temizle',
  filter: {
    label: 'Etiket filtresi',
    all: 'Tümü',
    starred: 'Yıldız',
    space: 'Uzay',
    unknown: 'Bilinmeyen',
    shared: 'Paylaşılan',
  },
  folders: {
    new: 'Yeni klasör',
    newChild: 'İçinde yeni klasör',
    rename: 'Yeniden adlandır',
    remove: 'Kaldır',
    moveTo: 'Şuraya taşı',
    unfiled: 'Klasörsüz',
    nameLabel: 'Klasör adı',
    namePlaceholder: 'Klasör adı',
  },
  discreet: {
    hide: 'Gizlilik modunu aç',
    show: 'Gizlilik modunu kapat',
  },
  empty: 'Henüz kayıtlı harita yok.',
  noMatches: 'Eşleşen harita yok.',
  addQuery: '“{name}” ekle',
  editingHeader: 'Düzenleniyor: {name}',
  saveChanges: 'Değişiklikleri kaydet',
  addChart: 'Harita ekle',
} as const;
