// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/common.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const common = {
  close: 'Kapat',
  cancel: 'İptal',
  edit: 'Düzenle',
  delete: 'Sil',
  keep: 'Koru',
  locationFallbackOcean: 'Okyanus',
  tzWarning: '⚠ ABD/AB dışında 1970 öncesi saat dilimi: yaz saatini bir atlasla doğrulayın',
  timeUnknownBanner: 'Doğum saati bilinmiyor',
  provisionalTimeBanner: '⚠ {time} deneniyor — geçici, kaydedilmedi',
  locked: {
    feature: '{feature} bir {tier} özelliğidir.',
    featureAnyTier: '{feature} planınızda yok.',
  },
  cardinal: {
    north: 'K',
    south: 'G',
    east: 'D',
    west: 'B',
  },
  hud: {
    dragToMove: 'Taşımak için sürükleyin',
    dockKey: 'Çift',
    dockHint: 'tıklayarak yerleştirin · ortaya oturur',
    recentreHint: 'tıklayarak ortalayın',
    collapse: 'Paneli daralt',
    expand: 'Paneli genişlet',
    collapseHint: 'Denetimleri gösterin veya gizleyin.',
    closeNamed: '{name} penceresini kapat',
  },
} as const;
