// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/creditsModal.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const creditsModal = {
  title: 'Emeği geçenler ve lisanslar',
  thanks: {
    tip: 'Özel teşekkürler',
    hint: 'Emeği geçenleri görüntüleyin',
    title: 'Özel teşekkürler',
    leadRole: 'AstroLina’nın astroloğu',
    leadBody: 'Bu uygulama onun pratiği olarak başladı ve hâlâ ona hesap veriyor. İzlediği yöntemler, bağlı kaldığı kurallar ve çizdiği her çizginin ardındaki muhakeme onundur — yazılım bu zanaatla örtüşene dek sabırla, çoğu zaman birden fazla kez anlatıldı.',
    othersHeading: 'Ayrıca teşekkürler',
    body: 'İki astroloji profesyoneli bu projeye zamanlarını, uzmanlıklarını ve büyük bir sabır ayırdı — soruları yanıtladı, kuralları denetledi ve erken bir aracın ayaklarının yere basmasına yardım etti. Onlar olmadan daha eksik bir şey olurdu.',
    role: 'Astroloji profesyoneli',
  },
  intro: 'AstroLina açık veri ve açık kaynaklı yazılım üzerine kuruludur. Lisans metinlerinin tamamı proje deposunda bulunur.',
  notice: {
    lead: 'Bu işte yeniyiz ve yardımınıza seviniriz.',
    body: 'Astronomi sağlam — Swiss Ephemeris, JPL verileri; NASA’nın Horizons hizmetiyle karşılaştırılarak bir yay saniyesinin çok altında bir farkla denetlendi. Etrafındaki uygulama ise birinci sürüm ve o kadar çok şey yapıyor ki lansmandan önce her köşesine ulaşmamız mümkün olmadı. Bu yüzden bir çizgi yanlış görünürse, bir rakam tuhaf gelirse ya da bir şey istediğinizi yapmıyorsa lütfen bize bildirin — her rapor bir insan tarafından okunur ve bunu güvenebileceğiniz bir araç hâline getirmekte kararlıyız.',
    report: 'Bir sorun bildirin.',
  },
  groups: {
    astrolina: 'AstroLina',
    mapsPlaces: 'Haritalar ve yerler',
    astronomy: 'Astronomi',
    typeSoftware: 'Yazı tipi ve yazılım',
  },
  notes: {
    astrolina: '© 2026 AstroLina. GNU Affero General Public License v3.0 kapsamında özgür, açık kaynaklı yazılım.',
    sourceCode: 'Kaynak kodun tamamı, AGPL gereğince erişilebilir durumda. Katkılara açığız.',
    openstreetmap: 'Altlık harita verileri (haritanın kendisinde de belirtilir).',
    openfreemap: 'Ücretsiz vektör karoları, etiket yazı tipleri ve simge grafikleri.',
    mapStyles: 'MapTiler Basic, OSM Bright, Dark Matter, Positron ve Fiord Color; bazıları uyarlanmıştır. © MapTiler.com ve OpenMapTiles katkıda bulunanlar; © Mapbox; © CartoDB.',
    geonames: 'Çevrimdışı yer adı arama ve şehir sorgulama.',
    photon: 'Çevrimiçi yer ve adres arama; veriler © OpenStreetMap katkıda bulunanlar.',
    swisseph: 'Gezegen konumları (JPL DE441). © Astrodienst AG, @swisseph/browser aracılığıyla.',
    nasaEclipse: 'Güneş ve Ay tutulması katalogları (tarihler, türler, Saros serileri). Tutulma tahminleri: Fred Espenak ve Jean Meeus (NASA/GSFC).',
    jplSbdb: 'Küçük gezegen etiketlerinin dayandığı yörünge sınıfları.',
    noto: 'Astrolojik simgeler. © 2022 The Noto Project Authors.',
    maplibre: 'Etkileşimli harita çizimi.',
    rtlText: 'Sağdan sola harita etiketleri: birleştirilmiş Arap harfleri, okuma sırasına dizilmiş Arapça ve İbranice. © 2017 Mapbox.',
    icu: 'Sağdan sola etiket eklentisindeki harf şekillendirme ve çift yönlü metin kodu. © Unicode, Inc.',
    other: 'Ayrıca proje deposunda listelenen, MIT lisanslı diğer kütüphaneler.',
  },
  footer: ' · Astrokartografi hesaplamaları ve arayüz tasarımı AstroLina’nın kendi eseridir; temeldeki efemeris ve harita verilerinin kaynakları yukarıda belirtilmiştir.',
} as const;
