// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/localSpaceHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const localSpaceHud = {
  title: 'Yerel Uzay',
  closeAria: 'Yerel Uzay’ı kapat',
  closeHint: 'Yerel uzay görünümünü kapatın.',
  lsOrigin: {
    pin: 'Raptiyeden',
    pinHint: 'Relokasyon yerel uzayı: çizgiler etkin raptiyeden yayılır (hiçbir yer sabitlenmemişse doğum yerinden).',
    birthplace: 'Doğum yeri',
    birthplaceHint: 'Çizgiler, bir raptiye konmuş olsa bile doğum yerine bağlı kalır.',
    home: 'Ev',
    homeHint: 'Yönleri, bu haritanın sahibinin şu an yaşadığı yerden yayın — tam burada ayarlayın ya da değiştirin. Ev konumu ayarlanmamışken doğum yerini kullanır.',
    homeUnset: 'Bu harita için ev konumu ayarlanmamış — biri ayarlanana kadar yönler doğum yerinden yayılır.',
  },
  hideInbound: {
    title: 'Ters yön çizgileri',
    hint: 'Her yerel uzay çizgisinin ters yön uzantısı — gök cisminin antipoduna uzanan kesikli yarı; ileri (düz) yönün tam karşısı. Yalnızca ileri yöndeki yarıları tutmak için kapatın.',
  },
  hideDegrees: {
    title: 'Dereceler',
    hint: 'Her ileri yön etiketinde derece ve dakika cinsinden yön. Kapalıyken etiketlerde yalnızca LS ve simge kalır.',
  },
  hideCompass: {
    title: 'Pusula',
    hint: 'Yakınlaştırdığınızda başlangıç noktasında beliren yerel ufuk pusula çarkı.',
  },
  flyToOrigin: {
    title: 'Başlangıç noktasına uç',
    hint: 'Yerel ufka inin: kamerayı çizgilerin yayıldığı başlangıç noktasına uçurun.',
  },
} as const;
