// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/map.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const map = {
  ctrl: {
    zoomIn: 'Yakınlaştır',
    zoomOut: 'Uzaklaştır',
    resetBearing: 'Yönü ve eğimi sıfırla',
  },
  pin: {
    natal: 'Natal doğum yeri (kaldırmak için sağ tıklayın)',
    custom: 'Sabitlenen konum (kaldırmak için sağ tıklayın)',
    home: 'Ev — bu haritanın şu an yaşadığı yer (raptiyeyi kaldırmak için sağ tıklayın)',
  },
  home: {
    tip: 'Ev',
    hint: 'Haritayı burada okumak için tıklayın',
  },
  flyToZenith: '{prefix}{planet} zenitine uçun',
  flyToAspectPoint: '{planet} için {aspect} açısı derecesinin tepede olduğu yere uçun (geri dönmek için yeniden tıklayın)',
  flyToMidpoint: '{planetA}/{planetB} orta noktasının tepede olduğu yere uçun (geri dönmek için yeniden tıklayın)',
  aspectNames: {
    sextile: 'altmışlık',
    square: 'kare',
    trine: 'üçgen',
  },
  flyToParan: 'Bu paranın kesişim noktasına uçun (geri dönmek için yeniden tıklayın)',
  flyToLocalSpaceOrigin: 'Yerel uzay başlangıç noktasına uçun (raptiye)',
  ecliptic: 'Ekliptik',
  polarNote: 'Kutup bölgesi: bu çizginin zirvesinin ötesinde doğuş ve batış yer değiştirir.',
  eclipse: {
    central: 'Merkez çizgisi',
    pathEdge: 'Merkezî yolun kenarı',
    isoline: '{pct} maksimum tutulma',
    outerLimit: 'Görünürlük sınırı — bu çizginin içinde az da olsa tutulma görülür',
    horizon: '{phase} için Ay doğuş/batış çizgisi',
    localMax: 'Güneş’in burada örtülen kısmı {pct}, saat {time} (UTC)',
    lunarAllVisible: 'Tutulmanın tamamı buradan görülebilir',
    lunarPartView: 'Tutulmanın bir kısmı buradan görülebilir ({total} kontaktan {n})',
  },
  eclipseCard: {
    notVisible: 'Tutulma buradan görünmüyor',
    utc: 'UTC',
    c1: 'Parçalı evre başlar',
    c2: 'Tam evre başlar',
    c2Annular: 'Halka başlar',
    max: 'Maksimum',
    c3: 'Tam evre biter',
    c3Annular: 'Halka biter',
    c4: 'Parçalı evre biter',
    atSunrise: 'gün doğumunda',
    atSunset: 'gün batımında',
    maxValue: 'Büyüklük {mag} · örtülme {obsc}',
    duration: 'Süre',
    phase: {
      P1: 'Yarı gölge başlar',
      U1: 'Parçalı evre başlar',
      U2: 'Tam evre başlar',
      max: 'Maksimum',
      U3: 'Tam evre biter',
      U4: 'Parçalı evre biter',
      P4: 'Yarı gölge biter',
    },
    belowHorizon: 'Ay ufkun altında',
    moonrise: 'Ay doğuşu',
    moonset: 'Ay batışı',
  },
  lineCard: {
    distance: '{label} {km} km / {mi} mil',
  },
  zenithTitle: '{planet} zeniti',
  zenithSub: 'burada {planet} tam tepede',
  nadirTitle: '{planet} nadiri',
  nadirSub: 'burada {planet} tam ayakucunda',
  geoReadout: {
    place: '{place} GE',
    coords: '{lat} {lng} GE',
    as: 'AS',
    mc: 'MC',
  },
  geoLegend: {
    aria: 'Bölge gölgelendirme lejantı',
    isolate: 'Yalnızca {group} bölgelerini göster',
    clear: 'Tüm bölgeleri göster',
  },
  zoomOutToWide: 'Geniş görünüme uzaklaştır',
  zoomOut: 'Uzaklaştır',
  webgl: {
    unsupportedTitle: 'Bu harita WebGL gerektirir',
    unsupportedBody: 'Tarayıcınız bu sayfaya bir WebGL grafik bağlamı sağlamıyor, bu yüzden harita çizilemiyor.',
    tipsHeading: 'Deneyebileceğiniz birkaç şey:',
    tipAccel: 'Tarayıcı ayarlarınızda donanım hızlandırmayı açın, ardından yeniden yükleyin.',
    tipShield: 'Parmak izi engelleyici ya da gizlilik kalkanı kullanıyorsanız bu site için WebGL / canvas kullanımına izin verin.',
    tipBrowser: 'Ya da AstroLina’yı güncel başka bir tarayıcıda açın.',
    lostTitle: 'Harita grafik bağlamını kaybetti',
    lostBody: 'Bu durum, cihazın grafik belleği azaldığında yaşanabilir. Çoğu zaman kendiliğinden düzelir — düzelmezse sayfayı yeniden yükleyin.',
    reload: 'Sayfayı yeniden yükle',
  },
} as const;
