// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/missions.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const missions = {
  guideTitle: 'Görevler',
  title: 'Rehber',
  close: 'Kapat',
  skipTip: 'Bu rehberi atlayın',
  ok: 'Tamam, anladım',
  okLocked: 'Devam etmek için tüm görevleri tamamlayın',
  dontShowAgain: 'Bir daha gösterme',
  prevGuide: 'Önceki rehber',
  nextGuide: 'Sonraki rehber',
  guidePosition: 'Rehber {current}, toplam {total}',
  gesture: {
    double: 'Çift',
    right: 'Sağ',
    hold: 'Basılı tut',
    shift: 'Shift',
    drag: 'Sürükle',
    click: 'Tıkla',
    tap: 'Dokun',
    doubleTap: 'Çift dokun',
    longPress: 'Uzun bas',
    touchDrag: 'Dokun ve sürükle',
    twoFinger: 'İki parmakla sürükle',
    pinch: 'Kıstır',
    snap: 'Yasla',
  },
  pill: {
    double: 'Çift {icon} tıkla',
    right: 'Sağ {icon} tıkla',
    hold: 'Tutup {icon} sürükle',
    shiftDrag: 'Shift ile {icon} sürükle',
    rightDrag: 'Sağ {icon} sürükle',
    tapSnap: 'Yasla’ya {icon} dokun',
    holdShift: 'Shift’i {icon} basılı tut',
  },
  mapBasics: {
    subtitle: 'Bir {pin} raptiye nasıl konur',
    createPin: 'raptiye koymak için',
    removePin: 'raptiyeyi kaldırmak için',
    placeNatal: 'natal raptiyeyi koymak için',
  },
  measureBasics: {
    subtitle: '{ruler} Ölçüm aracı nasıl kullanılır',
    drawLine: 've {drag} çizgi çizmek için',
    touchDrawLine: 'çizgi çizmek için',
    shiftSnap: 'ölçüm sırasında bir çizginin üzerinde, ona yaslanmak için — o çizgiye olan tam mesafe',
    rightCancel: 'aracı iptal etmek için',
    touchSnap: 'sonra yaslamak için çizgi üzerinde sürükleyin',
    touchCancel: 'çıkmak için yeniden Ölçüm aracına',
  },
  zoomBasics: {
    subtitle: 'Hızlıca {zoom} nasıl yakınlaştırılır',
    zoomOut: '“Uzaklaştır” düğmesine',
    quickZoom: 'yakınlaştırma penceresi oluşturmak için',
    perspective: 'perspektifi değiştirmek için (yalnızca 3B küre projeksiyonu görünümünde)',
    touchQuickZoom: 'yakınlaştırmak ya da uzaklaştırmak için',
  },
} as const;
