// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/planets.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const planets = {
  Sun: {
    name: 'Güneş',
    theme: 'Temel kimliğiniz, yaşam gücünüz ve parladığınız yer.',
  },
  Moon: {
    name: 'Ay',
    theme: 'Duygular, içgüdüler ve kendinizi evinizde hissettiren şeyler.',
  },
  Mercury: {
    name: 'Merkür',
    theme: 'Zihin: nasıl düşündüğünüz, öğrendiğiniz ve iletişim kurduğunuz.',
  },
  Venus: {
    name: 'Venüs',
    theme: 'Aşk, güzellik, haz ve değer verdikleriniz.',
  },
  Mars: {
    name: 'Mars',
    theme: 'Dürtü, cesaret ve kendinizi nasıl ortaya koyup harekete geçtiğiniz.',
  },
  Jupiter: {
    name: 'Jüpiter',
    theme: 'Büyüme, şans ve hayatın genişleyip cömert hissettirdiği yer.',
  },
  Saturn: {
    name: 'Satürn',
    theme: 'Disiplin, sınırlar ve olgunluğun zor kazanılmış dersleri.',
  },
  Uranus: {
    name: 'Uranüs',
    theme: 'Ani değişim, özgürlük ve içinizdeki isyan kıvılcımı.',
  },
  Neptune: {
    name: 'Neptün',
    theme: 'Düşler, sezgi, maneviyat ve güzel yanılsama.',
  },
  Pluto: {
    name: 'Plüton',
    theme: 'Güç, yoğunluk, derin dönüşüm ve yeniden doğuş.',
  },
  NorthNode: {
    name: 'K. Düğüm',
    theme: 'Gelişim sınırınız: hayatın sizi ileriye çağırdığı ve aidiyetin sizi bulduğu yer.',
  },
  SouthNode: {
    name: 'G. Düğüm',
    theme: 'Tanıdık zemin: miras kalan yetenekler, derin kökler ve bırakmaya hazır olduklarınız.',
  },
  Lilith: {
    name: 'Lilith',
    tipName: 'Kara Ay Lilith',
    theme: 'Ham, evcilleşmemiş içgüdü ve evcilleştirilmeyi reddettiğiniz yer.',
  },
  Chiron: {
    name: 'Chiron',
    theme: 'Yaralı şifacı: en derin acınızın içinden gelen şifa.',
  },
  Ceres: {
    name: 'Ceres',
    theme: 'Şefkatli bakım, beslenme ve hayatın kayıp ve geri dönüş döngüleri.',
  },
  Pallas: {
    name: 'Pallas',
    theme: 'Strateji, beceri ve net bir bakışla sorun çözme.',
  },
  Juno: {
    name: 'Juno',
    theme: 'Bağlılık, ortaklık ve ilişkinin eşit olduğunu hissetmeniz için gerekenler.',
  },
  Vesta: {
    name: 'Vesta',
    theme: 'Adanmışlık, odak ve kutsal tuttuğunuz iç ateş.',
  },
  Fortune: {
    name: 'Şans Noktası',
    theme: 'Rahatlık, serpilme ve bedenin ve dünyevi yaşamın refaha erdiği yer.',
  },
} as const;
