// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/profile.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const profile = {
  planTag: {
    new: 'YENİ',
    adv: 'GELİŞMİŞ',
    tip: 'Gelişmiş mod',
    hint: 'Deneyimli astrologlar için tasarlanmış daha gelişmiş özellikleri gösterir.',
    tipBasic: 'Standart mod',
    hintBasic: 'Daha sade, standart bir görünüm için gelişmiş özellikleri gizler.',
  },
} as const;
