// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/settings.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const settings = {
  sections: {
    appearance: 'Görünüş',
    mapFilters: 'Harita filtreleri',
    calculation: 'Hesaplama',
    advanced: 'Gelişmiş',
  },
  headings: {
    theme: 'Tema',
    privacy: 'Gizlilik',
    details: 'Ayrıntılar',
    projection: 'Projeksiyon',
    language: 'Dil',
    planets: 'Gezegenler',
    points: 'Noktalar',
    minorBodies: 'Küçük gök cisimleri',
    angles: 'Köşeler',
    lines: 'Çizgiler',
    lineSystem: 'Çizgi sistemi',
    lineProjection: 'Çizgi izdüşümü',
    geoGrid: 'Jeodezik ızgara',
    lunarNode: 'Ay düğümü',
    houseSystem: 'Ev sistemi',
    zodiac: 'Zodyak',
    aspectOrbs: 'Açı orbları',
    primaryRate: 'Primer dir. anahtarı',
    display: 'Görüntüleme',
    arc: 'Yay',
    progAngles: 'Köşeler',
    magnitudeSteps: 'Büyüklük adımları',
    fortuneFormula: 'Şans Noktası',
    rulerships: 'Yöneticilikler',
  },
  details: {
    roadsRivers: 'Yollar/Nehirler',
    roadsRiversHint: 'Altlık haritadaki yol ve nehir çizimlerini gösterir. Astrokartografi çizgilerinin ardında daha sade bir zemin için gizleyin.',
    placeNames: 'Adlar/Etiketler',
    placeNamesHint: 'Altlık haritadaki şehir ve ülke yazılarını gösterir. Bu, her durumda görünür kalan ACG çizgi etiketlerinden ayrıdır.',
  },
  shiftTag: 'Shift',
  natal: {
    title: 'Natal harita',
    hint: 'Alttaki doğum haritası. Gizlediğinizde katman onun yerine geçer — haritanın çizgilerini, çarkını ve göstergelerini devralır.',
  },
  languageUnavailable: 'Yakında.',
  machine: {
    section: 'Otomatik çeviri',
    sectionHint: 'Yukarıdaki diller AstroLina ile birlikte gelir. Aşağıdaki diller bu cihazda otomatik olarak çevrilecek.',
    hint: 'Uygulamayı kullandıkça bu cihazda İngilizceden çevrilir. Bazı ifadeler tam doğru olmayabilir.',
    downloadHint: 'Bu cihazda İngilizceden çevrilir. İlk seferde çeviri modeli cihaza indirilir.',
    partialHint: 'Uygulamanın bir kısmı hâlâ İngilizce. Çevirinin bu cihaza indirilmesini tamamlamak için dili yeniden seçin.',
    heldDownloadHint: 'Seçiminiz, çeviri bu cihaza yeniden indirilene kadar beklemede. İndirmek için dili seçin.',
    heldHint: 'Bu cihaz şu anda bu dile çeviri yapamıyor. Seçiminiz korunur ve cihaz çeviri yapabildiğinde geri gelir.',
    cacheHint: 'Bu cihazın daha önce çevirdiklerinden gösteriliyor. Burada artık çeviri yapamıyor; bu yüzden yeni metinler İngilizce kalır.',
    downloading: '{language} bu cihaza indiriliyor… %{percent}',
    translating: '{language} diline çevriliyor…',
    failed: '{language} dili bu cihazda kurulamadı.',
    disclosure: 'Bu cihazda makineyle çevrildi. Bazı ifadeler tam doğru olmayabilir; henüz çevrilmemiş her şey İngilizce görünür.',
  },
  dock: {
    open: 'Ayarları aç',
    close: 'Ayarları kapat',
  },
  userRate: {
    label: 'Yılda derece',
  },
  parans: {
    title: 'Paranlar',
    hint: 'İki gök cisminin aynı anda köşede olduğu enlemler: biri doğarken öteki kulmine olur ve benzeri. Haritanızın paranları bir katmanın yanında da açık kalır.',
    blockedCyclo: 'Tek bir gökyüzü anı yok — Siklokartografi progres ve transit gök cisimlerini birlikte okur. Haritanın kendi paranlarını geri getirmek için “Natal harita”yı gösterin.',
    blockedOverlay: 'Paranlar haritadan okunur ve bu katman onun yerine geçiyor. Haritanın paranlarını geri getirmek için “Natal harita”yı gösterin.',
  },
  aspectLines: {
    title: 'Açı çizgileri',
    hint: 'Bir gezegenin MC ya da Yükselen ile altmışlık (⚹), kare (□) veya üçgen (△) yaptığı çizgiler — her açı iki kez, her yanda bir kez. AS ile üçgen, DS ile altmışlık da sayılır; iki yorumu görmek için çizginin üzerine gelin. Kavuşumlar ve karşıtlıklar gezegenin zaten haritadaki kendi köşe çizgileridir.',
    openHud: 'Özelleştir',
    openHudHint: 'Açılar penceresini açın: haritanın çizgilerini niteliğe ve eksene göre filtreleyin, tüm açı orblarını tek seferde ayarlayın.',
  },
  midpointLines: {
    title: 'Orta nokta çizgileri',
    hint: 'Görünür iki gök cisminin orta noktasının tam olarak bir köşeye denk geldiği çizgiler (ör. Su/Mo MC). In Mundo cisimsel orta noktayı (ortalama RA ve deklinasyon), In Zodiaco klasik boylam orta noktasını kullanır. Seti okunabilir tutmak için gezegen filtresini daraltın.',
    blockedCyclo: 'Burada bir orta nokta, progres bir gök cismiyle transit bir gök cismini tek bir noktada ortalardı — iki farklı zaman arasında tutarsız.',
  },
  zenithNadir: {
    title: 'Zenitler/Nadirler',
    hint: 'Her cismin tam tepede (zenit — MC çizgisinde daire) ve ayak altında (nadir — IC çizgisinde baklava dilimi) olduğu yeri işaretler. Tanımak için üzerine gelin, uçmak için tıklayın.',
  },
  aspectOrbs: {
    hint: 'Çarktaki ve açı listelerindeki her açı için tam açıdan en fazla uzaklık (derece). Işıklar, Güneş veya Ay söz konusu olduğunda her orbu genişletir; Paraleller deklinasyon orbudur.',
    setDegrees: 'Derece ayarla',
    orbAria: '{aspect} açıları için orb, derece cinsinden',
    lumLabel: 'Işıklar +',
    lumHint: 'Güneş veya Ay söz konusu olduğunda eklenen orb derecesi.',
    lumAria: 'Bir ışık söz konusu olduğunda ek orb, derece cinsinden',
    declinationLabel: 'Paraleller',
    declinationAria: 'Paralel ve kontraparalel açılar için orb, deklinasyon derecesi cinsinden',
  },
  zodiac: {
    tropical: {
      label: 'Tropikal',
      hint: 'Mevsimlere bağlı burçlar (0° Koç = mart ekinoksu). Batı astrolojisinin varsayılanı.',
    },
    lahiri: {
      label: 'Sidereal · Lahiri',
      hint: 'Sabit yıldızlara bağlı burçlar, Lahiri ayanamsa ile (Vedik standart; bugün tropikalin ~24° gerisinde). Çarkı ve göstergeleri değiştirir; harita çizgileri zodyaktan bağımsız olayları gösterir ve yerinde kalır.',
    },
    'fagan-bradley': {
      label: 'Sidereal · Fagan/Bradley',
      hint: 'Sabit yıldızlara bağlı burçlar, Fagan/Bradley ayanamsa ile (Batı’nın sidereal standardı). Çarkı ve göstergeleri değiştirir; harita çizgileri yerinde kalır.',
    },
  },
  natalLines: {
    title: 'Natal çizgiler',
    hint: 'Doğum haritasının Yükselen, MC, Alçalan ve IC üzerindeki köşe çizgileri — bir katmanın yanında da paranları. Çark ve göstergeler kalır; gizli çizgilere tıklanamaz.',
  },
  starLines: {
    title: 'Sabit yıldızlar',
    hint: 'Klasik sabit yıldızların (Regulus, Spica, Algol ve diğerleri) köşe çizgileri: küçük yıldızlarla dizili noktalı çizgiler, ortak bir yıldız ışığı tonunda. Kutup çevresi yıldızlarda doğuş/batış çizgileri atlanır; orada geleneksel yorum paranlardır.',
    bright: 'Başlıca yıldızlar',
    brightHint: 'Dört kraliyet yıldızı ve en parlak klasikler (18 yıldız).',
    all: 'Tam set',
    allHint: 'Paketteki çalışma setinin tamamı (40 yıldız). Kalabalık bir harita bekleyin.',
  },
  nightShade: {
    title: 'Gece gölgesi',
    hint: 'Gösterilen anda Dünya’nın gece olan yarısını gölgeler.',
  },
  discreet: {
    title: 'Gizlilik modu',
    hint: 'Ekrandaki her yerde adları, doğum tarihlerini ve doğum yerlerini gizler — bir Görüntü Alma resim yazısı ve dışa aktardığı görsel de dahil — böylece yanınızda biri varken çalışabilirsiniz. Harita ve çizgileri değişmez; oturup hazırladığınız bir belge ise gerçek bilgileri taşımaya devam eder.',
  },
  orbZones: {
    title: 'Orb bölgeleri',
    hint: 'Gölgeli etki bölgeleri: her gezegen köşe çizgisinin ve her paranın çevresinde yer mesafesiyle ölçülen bir kuşak. Etki mesafeyle azalır; kenar bir uçurum değil, bir kabuldür.',
    unitAria: 'Orb bölgesi mesafe birimi (km veya mil)',
    lineAria: 'Çizgi orb bölgesi genişliği, her yanda',
    paranLabel: 'Paranlar',
    paranAria: 'Paran orb genişliği, her yanda',
  },
  theme: {
    glass: {
      label: 'Cam',
      hint: 'Krem rengi karalar ve açık mavi denizlerle parlak, ayrıntılı bir harita üzerinde buzlu gümüş paneller.',
    },
    dark: {
      label: 'Koyu',
      hint: 'Koyu paneller altında, gece geç saatler için yapılmış, her çizginin belirgin durduğu derin arduvaz grisi bir harita.',
    },
    vintage: {
      label: 'Toprak',
      hint: 'Sıcak bir atlas görünümü: yumuşak mavi denizler ve kum rengi karalar, parşömen kahvesi panellerle çerçeveli.',
    },
    customize: 'Özelleştir',
    customizeHint: 'Tema düzenleyicisini açın: renkler, çizgi stilleri ve efektler; birkaç genel seçimden tek tek her değere kadar.',
    customHeld: 'Şu anda kullanılamıyor. Bu arada uygulama, bundan önce kullandığınız temayla çiziliyor; seçiminiz korunuyor, silinmedi.',
    customEditsHeld: 'Bu temanın size ait sürümü şu anda kullanılamıyor, bu yüzden standart sürümü çiziliyor; sizinki korunuyor, silinmedi.',
    outlineUnavailable: 'Dilsiz harita yalnızca kıyı çizgilerinden oluşur: yol, nehir ya da yer adı içermez. Bunu kullanmak için Özelleştir bölümünde başka bir Harita seçin; seçiminiz korunur.',
    lockedNote: 'Bu hesaba henüz açık değil. Kilidini neyin açtığını görmek için basın.',
    keptNote: 'Sizde kalır. Başka bir temaya geçerseniz, bu temaya geri dönmek rozette gösterileni gerektirir.',
  },
  projection: {
    hint: 'Dünyanın nasıl çizildiği — herhangi bir şeyin nerede olduğu değil. İki görünüm de aynı koordinatları çizer ve uygulamanın raporladığı her mesafe (bir çizgi kartının en yakın mesafe satırı, tıklayıp sürükleyerek ölçüm, orb bölgeleri) küre üzerinde ölçülen gerçek bir yer mesafesidir. Yine de yakınlığı gözle değerlendirmek için iki görünüm de güvenli değildir: Düz görünüm ölçeği kutuplara doğru gerer, küre ise kenarına doğru sıkıştırır; bu yüzden aradaki boşluğa değil, mesafeye bakın.',
    '2d': {
      label: 'Düz',
      hint: 'Klasik Web-Mercator haritası',
    },
    '3d': {
      label: 'Küre',
      hint: 'Döndürülebilir 3B küre',
    },
  },
  lineSystem: {
    celestial: {
      label: 'Göksel',
      hint: 'Standart astrokartografi: köşeler gökyüzüne göre konumlanır (yıldız zamanı)',
    },
    geodetic: {
      label: 'Jeodezik',
      hint: 'Jeodezik eşleme: zodyak Dünya’nın boylamlarına eşlenir (Greenwich = 0° Koç, her zaman tropikal), doğum saatinden bağımsız',
    },
  },
  geoGrid: {
    mc: {
      title: 'MC meridyenleri',
      hint: 'Greenwich’in doğusunda 30° arayla on iki meridyen. Jeodezik bir haritada her biri bir MC burcunun başladığı yerdir; burç haritanın üst kenarında işaretlenir.',
    },
    asc: {
      title: 'Yükselen eğrileri',
      hint: 'Her burcun doğmaya başladığı yer: eğri üzerindeki her yerde Yükselen, o burcun 0 derecesindedir. Harita çizgisi çizilmezken varsayılan olarak açıktır; seçiminiz buna üstün gelir.',
    },
    zones: {
      title: 'Bölge tonlaması',
      hint: 'On iki MC bölgesini doldurur: element renk, nitelik ton olarak (Öncü en koyu, Değişken en açık). Haritadaki lejant tek bir elementi ya da niteliği tek başına gösterir.',
    },
    presentation: {
      title: 'Sunum',
      hint: 'Bölgeleri başka birine göstermek için bölge tonlamasını soluktan güçlüye yükseltir.',
    },
  },
  coordSystem: {
    mundo: {
      label: 'In Mundo',
      hint: 'Çizgiler her gök cisminin gökyüzündeki kendi yerini kullanır (RA / dekl.). Ekliptik üzerinde duran Güneş için In Zodiaco ile aynıdır; fark en çok Plüton ve Ay’dadır.',
    },
    zodiaco: {
      label: 'In Zodiaco',
      hint: 'Çizgiler çizilmeden önce gök cisimleri ekliptiğe izdüşürülür (yaygın bir ACG varsayılanı).',
    },
  },
  fortuneFormula: {
    hint: 'Şans Noktası, canlılık ve dünyevi rahatlıkla ilgili hesaplanmış bir kısımdır — gökyüzünde bir cisim değil, ekliptik üzerinde bir noktadır; bu yüzden onu yalnızca zodyakal bir çerçeve yerleştirebilir: harita çizgileri için Çizgi izdüşümü ayarının In Zodiaco olması (ya da Jeodezik çizgi sistemi) gerekir. Harita raptiyesinin yerini değiştirmek onu harita çarkında o yer için yeniden hesaplar; harita çizgileri ise natal Şans Noktanızı korur.',
    sect: {
      label: 'Sekte dayalı (gündüz/gece)',
      hint: 'Gündüz doğumlarında Yükselen + Ay − Güneş kullanılır; gece doğumlarında formül tersine döner: Yükselen + Güneş − Ay. Geleneksel uygulama.',
    },
    ptolemaic: {
      label: 'Ptolemaik (sabit)',
      hint: 'Gündüz ya da gece, her harita için Yükselen + Ay − Güneş. Alternatif tarihsel uygulama.',
    },
  },
  rulership: {
    hint: 'Harita çarkının asalet okumasının kullandığı yöneticilik tablosu. Modern, kimsenin yerini almadan dış üç gezegeni EKLER: Mars, Plüton’un yanında Akrep’i korur ve ikisi de karşıdaki Boğa’da zarardadır. Geleneksel seçeneği dış gezegenlerin satırlarını kaldırır ve listede başka hiçbir şeyi değiştirmez.',
    traditional: {
      label: 'Geleneksel',
      hint: 'Yalnızca yedi gezegenli tablo — Mars Akrep’i, Satürn Kova’yı, Jüpiter Balık’ı yönetir. Uranüs, Neptün ve Plüton hiçbir şeyi yönetmez, bu yüzden asaletleri yoktur.',
    },
    modern: {
      label: 'Modern',
      hint: 'Aynı yedi gezegen, artı Akrep’te Plüton, Kova’da Uranüs ve Balık’ta Neptün. Bu üç burcun iki yöneticisi vardır ve her satır kendi çağını belirtir.',
    },
  },
  inert: {
    fortuneMundo: 'Bir kısım, ekliptik üzerinde olup gökyüzünde konumu olmayan bir noktadır; bu yüzden In Mundo onu yerleştirecek bir yer bulamaz. Bu çizgiyi görmek için izdüşümü In Zodiaco olarak ayarlayın (Hesaplama).',
    fortuneAdvanced: 'Şans Noktası Gelişmiş bir yorumdur — kullanmak için Gelişmiş modu açın.',
    geodeticSidereal: 'Jeodezik çizgi sistemi TROPİKAL zodyağı Dünya’nın boylamlarına haritalar; sidereal sürümü yoktur. Kullanmak için zodyağı Tropikal yapın (Gelişmiş); seçiminiz korunur.',
    geodeticHeld: 'Jeodezik, nasıl çizdiğini kontrol ettiğimiz süre boyunca inceleme altında — arkasında duramayacağımız bir harita çizmektense onu beklemede tutmayı tercih ederiz. Seçiminiz korunuyor, silinmedi; yakında yeniden bakın.',
    skyHeldWhy: 'Gökyüzüyle birlikte dönmeyen jeodezik haritalarda kullanılamaz.',
    skyHeldFix: 'Kullanmak için Hesaplama bölümünde çizgi sistemini Göksel olarak değiştirin.',
    skyHeld: 'Gökyüzüyle birlikte dönmeyen jeodezik haritalarda kullanılamaz. Kullanmak için Hesaplama bölümünde çizgi sistemini Göksel olarak değiştirin.',
    skyHeldAction: 'Hesaplama’yı aç',
    skyHeldForNow: 'Jeodezik haritalarda şimdilik kullanılamaz.',
    skyHeldForNowFull: 'Jeodezik haritalarda şimdilik kullanılamaz. Kullanmak için Hesaplama bölümünde çizgi sistemini Göksel olarak değiştirin.',
    anglesHeld: 'Jeodezik haritalarda bir yerin köşeleri koordinatlarından gelir; bu yüzden zamanla hareket etmez.',
    paransHeld: 'Jeodezik haritalarda paranlar gösterilmez.',
    paransHeldFull: 'Jeodezik haritalarda paranlar gösterilmez. Kullanmak için Hesaplama bölümünde çizgi sistemini Göksel olarak değiştirin.',
  },
  nodeType: {
    true: {
      label: 'Gerçek Düğüm',
      hint: 'Gerçek (oskülatör) düğüm Ay’ın anlık yörüngesini izler; ortalamanın çevresinde ±~1,5° salınır ve kısa süreliğine direkt harekete geçebilir (varsayılan).',
    },
    mean: {
      label: 'Ortalama Düğüm',
      hint: 'Düzleştirilmiş uzun vadeli ortalama; her zaman sabit bir hızla retro hareket eder.',
    },
  },
  houseSystem: {
    placidus: {
      label: 'Placidus',
      hint: 'Yarı yay zaman bölümü (yaygın modern varsayılan)',
    },
    koch: {
      label: 'Koch',
      hint: 'Doğum enlemi üzerinde yarı yay (GOH)',
    },
    regiomontanus: {
      label: 'Regiomontanus',
      hint: 'Gök ekvatorunun eşit bölümleri',
    },
    campanus: {
      label: 'Campanus',
      hint: 'İlk düşeyin eşit bölümleri',
    },
    porphyry: {
      label: 'Porphyry',
      hint: 'Her çeyrek ekliptik boylamda üçe bölünür',
    },
    alcabitus: {
      label: 'Alcabitus',
      hint: 'Gündüz / gece yayları üzerinde antik yarı yay',
    },
    meridian: {
      label: 'Meridyen',
      hint: 'MC noktasından başlayan, saat çemberleriyle izdüşürülmüş eşit 30° ekvator yayları; 1. ev başlangıcı Yükselen değil, bir Doğu Noktasıdır. Her enlemde iyi tanımlıdır.',
    },
    morinus: {
      label: 'Morinus',
      hint: 'Ekliptik kutup çemberleriyle izdüşürülmüş eşit ekvator yayları; hiç Yükselen ya da MC kullanmaz, bu yüzden kutup enlemlerinde bile sorunsuz çalışır.',
    },
    whole: {
      label: 'Tam Burç',
      hint: 'Yükselen burçtan başlayarak her ev tam bir burçtur',
    },
    equal: {
      label: 'Eşit',
      hint: 'Yükselenden ölçülen 30° genişliğinde evler',
    },
  },
  primaryRate: {
    ptolemy: {
      label: 'Ptolemy (1°/yıl)',
      hint: 'Derece başına bir yıl.',
    },
    naibod: {
      label: 'Naibod (59′08″/yıl)',
      hint: 'Yılda 0,985647°, Güneş’in ortalama hareketi.',
    },
    cardan: {
      label: 'Cardan (59′12″/yıl)',
      hint: 'Yılda 0,986667°.',
    },
    'kepler-ra': {
      label: 'Güneş’in günlük hareketi (RA)',
      hint: 'Kepler’in anahtarı — natal Güneş’in sağ açıklıktaki günlük hareketi × yıl.',
    },
    'solar-long': {
      label: 'Güneş’in günlük hareketi (boylam)',
      hint: 'Natal Güneş’in ekliptik boylamdaki günlük hareketi × yıl.',
    },
    'placidus-ra': {
      label: 'Gerçek Güneş yayı (RA)',
      hint: 'Sabit bir yıllık oran yerine, progres Güneş’in bu yaşa kadar katettiği gerçek mesafeyi zaman anahtarı olarak kullanır. Güneş’in hızı yıl boyunca değiştiği için yay düzensiz birikir — bu yüzden bu anahtar, doğum mevsimine göre sabit oranlı seçeneklerin biraz önünde ya da gerisinde gider.',
    },
    user: {
      label: 'Kullanıcı oranı',
      hint: 'Kendi yıllık derece değerinizi aşağıya girin.',
    },
    control: {
      tip: 'Primer direksiyonların zaman anahtarı',
      hint: 'Primer direksiyonlar günlük dönüşü modeller: gök cisimleri gökyüzündeki natal yerlerini korurken haritanın köşeleri ileri taşınır. Oran, zaman anahtarıdır — yaşamın her yılında ne kadar yay biriktiği. Ekoller ayrışır ve fark gerçektir: bir ömür boyunca Ptolemy ile Naibod arasındaki fark bir yılı aşar.',
    },
  },
  positioning: {
    'relative-to-natal': {
      label: 'Natal köşeler',
      short: 'Natal',
      tip: 'Doğum haritasının kendi köşeleri',
      hint: 'Natal çerçeveyi sabit tutar; böylece çizgileri yalnızca gezegenlerin kendi ikincil hareketi oynatır. Günlük dönüş çıkarılır. Şunu yanıtlar: bu transit, Dünya’nın neresinde Yükselen, MC, Alçalan veya IC üzerine düşerdi? Çizgiler haftalar ve aylar içinde, her gezegenin kendi hızıyla kayar.',
      returnHintSolar: 'Dönüşün gezegenlerini natal köşelere göre çizer. Dönüş Güneş’i natal derecesine geri gelmiştir ve Güneş’in ekliptik enlemi yoktur; bu yüzden çizgileri iki izdüşümde de tam olarak natal Güneş çizgilerinin üzerine düşer — her yıl aynı yer.',
      returnHintLunar: 'Dönüşün gezegenlerini natal köşelere göre çizer. Dönüş Ay’ı natal boylamına geri gelmiştir; bu yüzden In Zodiaco izdüşümünde çizgileri natal Ay çizgilerinin üzerine düşer; In Mundo izdüşümünde ise yakına düşer ama tam üstüne değil, çünkü Ay’ın enlemi doğumdan bu yana değişmiştir.',
    },
    'transit-moment': {
      label: 'Transit köşeler',
      short: 'Transit',
      returnLabel: 'Dönüş köşeleri',
      returnShort: 'Dönüş',
      tip: 'Anın kendi köşeleri',
      returnTip: 'Dönüş haritasının kendi köşeleri',
      hint: 'Gökyüzünü anın kendi çerçevesine göre okur; böylece çizgiler birincil hareketi taşır — tüm set saatte 15° süpürür ve günde bir kez tam tur atar. Her gök cisminin çizgisi, o anda gerçekten köşede olduğu yeri gösterir. İşin içinde natal harita yoktur. Bir mevsim boyunca değil, bir anda okunur.',
      returnHint: 'Dönüş haritası, kendi köşeleri olan, kendine ait bir andır. Harita, natal köşeler yerine dönüşün köşelerine göre çizilir.',
    },
  },
  arcMethod: {
    'sa-long': {
      label: 'Güneş yayı — boylamda',
      angles: 'Köşeleri, progres Güneş’in bu katmanın kendi anına kadar katettiği mesafe kadar ilerletir; mesafe ekliptik boyunca ölçülür.',
      bodies: 'Her gök cismini, bu haritanın progres Güneş’inin gerçekte katettiği mesafe kadar ilerletir; mesafe ekliptik boyunca ölçülür. Klasik yöntem.',
    },
    'sa-ra': {
      label: 'Güneş yayı — sağ açıklıkta',
      angles: 'Köşeleri, progres Güneş’in bu katmanın kendi anına kadar katettiği mesafe kadar ilerletir; mesafe ekvator boyunca ölçülür.',
      bodies: 'Her gök cismini, bu haritanın progres Güneş’inin gerçekte katettiği mesafe kadar ilerletir; mesafe ekvator boyunca ölçülür.',
    },
    'naibod-long': {
      label: 'Naibod, ortalama hız — boylamda',
      angles: 'Köşeleri, bu katmanın kendi zaman aralığı boyunca Güneş’in ortalama hızıyla ilerletir; ekliptik boyunca ölçülür.',
      bodies: 'Her gök cismini Güneş’in ortalama yıllık hareketiyle ilerletir; ekliptik boyunca ölçülür.',
    },
    'naibod-ra': {
      label: 'Naibod, ortalama hız — sağ açıklıkta',
      angles: 'Köşeleri, bu katmanın kendi zaman aralığı boyunca Güneş’in ortalama hızıyla ilerletir; ekvator boyunca ölçülür.',
      bodies: 'Her gök cismini Güneş’in ortalama yıllık hareketiyle ilerletir; ekvator boyunca ölçülür.',
    },
    headerAngles: 'Köşeler ne kadar ilerler',
    headerBodies: 'Gök cisimleri ne kadar ilerler',
  },
  progAngles: {
    natal: {
      label: 'Natal köşeler',
      short: 'Natal',
      tip: 'Doğum haritasının kendi köşeleri',
      hint: 'Progres gezegenler natal köşelere göre okunur. Doğum haritasının çerçevesi sabit tutulur; böylece yalnızca gezegenler hareket eder.',
    },
    progressed: {
      label: 'Progres köşeler',
      short: 'Progres',
      tip: 'Progres haritanın kendi köşeleri',
      hint: 'Progres haritanın kendi anı vardır — yaşamın her yılı için doğumdan sonra bir gün — o yüzden kendi köşeleri de vardır. Harita natal köşelere değil, bunlara göre çizilir.',
      hintTertiary: 'Üçüncül haritanın kendi anı vardır — her tropikal ay (27,32 gün) için doğumdan sonra bir gün — o yüzden kendi köşeleri de vardır. Harita natal köşelere değil, bunlara göre çizilir.',
    },
    idle: {
      tip: 'Devrede değil',
      hint: 'Köşeler natal haritada sabit tutulur, bu yüzden onlara yay uygulanmaz. Burada bir hesaplama seçmek, haritayı da Progres köşeler seçeneğine geçirir.',
    },
  },
  eclipses: {
    kind: {
      total: 'Tam',
      annular: 'Halkalı',
      hybrid: 'Hibrit',
      partial: 'Parçalı',
      penumbral: 'Yarı gölge',
    },
    body: {
      solar: 'Güneş',
      lunar: 'Ay',
    },
    details: {
      maximum: 'Maksimum',
      maximumValue: '{date} · {time} (UTC)',
      type: 'Tür',
      central: 'merkezi',
      nonCentral: 'merkezi olmayan',
      magnitude: 'Büyüklük',
      gamma: 'Gama',
      saros: 'Saros serisi',
      lunation: 'Lunasyon',
      sunPosition: 'Tutulma derecesi',
      sunPositionTip: 'Tutulmanın zodyak derecesi — Güneş ve Ay burada, {sign} burcunda buluşur.',
      moonPositionTip: '{sign} burcundaki tutulan Ay’ın zodyak derecesi — Güneş’in karşısında durur.',
      hemisphere: 'Yarımküre',
      north: 'Kuzey',
      south: 'Güney',
      duration: 'En uzun süre',
      width: 'Yol genişliği',
      widthValue: '{n} km',
      umbralMag: 'Tam gölge büyüklüğü',
      penumbralMag: 'Yarı gölge büyüklüğü',
      penumbralDur: 'Yarı gölge evresi',
      partialDur: 'Parçalı evre',
      totalDur: 'Tam evre',
    },
    contacts: {
      heading: 'Natal temaslar',
      none: '3° içinde temas yok — bu tutulma haritanın yanından sessizce geçer.',
      aspect: {
        conjunction: 'kavuşum',
        square: 'kare',
        opposition: 'karşıt',
      },
      asc: 'Yükselen',
      mc: 'Tepe Noktası',
    },
    otherLines: {
      title: 'Diğer çizgiler',
      hint: 'Haritada tutulma dışındaki her şey; yol tek başına okunsun diye tek basışta temizlenir — bu kapalıyken diğer çizgi anahtarlarını geçersiz kılar. Harita çarkı ve göstergeler kalır.',
    },
    chartLines: {
      title: 'Tutulma haritası',
      hint: 'Tutulma maksimumunun haritası — o anda çerçevelenen gökyüzü — natal haritanın yanında ikinci bir halka olarak harita çarkına eklenir.',
    },
    isoStep: {
      '10': {
        label: '%10',
        hint: 'Dokuz eğri — yoğun bir referans ızgarası.',
      },
      '20': {
        label: '%20',
        hint: 'Dört eğri — dengeli bir orta yol.',
      },
      '25': {
        label: '%25',
        hint: 'Çeyrek adımlarla üç eğri (klasik tutulma haritası geleneği).',
      },
    },
  },
  lineType: {
    MC: {
      hint: 'Tepe Noktası (kariyer, kamusal yaşam)',
    },
    IC: {
      hint: 'Dip Noktası (ev, kökler)',
    },
    ASC: {
      hint: 'Yükselen (benlik, kimlik)',
    },
    DSC: {
      hint: 'Alçalan (ilişkiler)',
    },
    VX: {
      hint: 'Vertex (kaderin getirdiği karşılaşmalar); Vx noktasını harita çarkına da ekler',
    },
    AVX: {
      hint: 'Anti-Vertex (eksenin doğu ucu); Avx noktasını çarka da ekler',
    },
  },
} as const;
