// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/synastryHud.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const synastryHud = {
  title: 'Sinastri',
  chooseComparison: 'Karşılaştırma haritası seçin',
  choosePrompt: 'Karşılaştırılacak harita seçin',
  barToggle: {
    show: 'Sinastri seçeneklerini göster',
    hide: 'Sinastri seçeneklerini gizle',
  },
  method: {
    label: 'Tür',
    davison: {
      label: 'Davison',
      hint: 'İki haritanın zaman ve yer bakımından orta noktası; gerçek bir harita olarak hesaplanır.',
    },
    composite: {
      label: 'Komp. orta noktalar',
      hint: 'Her gezegen ve köşe iki haritanın orta noktasında; her gezegen gerçek bir enlem ve deklinasyon taşır. Dünya haritasının çerçevesi kompozit Tepe Noktasını izler.',
    },
  },
  generate: {
    label: 'Oluştur',
    hint: 'Haritayı oluşturun, etkin hâle getirin ve sinastri karşılaştırma haritasını temizleyin.',
    needPartner: 'Önce yukarıdan bir karşılaştırma haritası seçin.',
    compositeParent: 'Kompozit bir harita yeniden birleştirilemez; iki normal harita seçin.',
  },
} as const;
