// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/timeline.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const timeline = {
  nubMode: {
    transits: 'Transitler',
    progressed: 'İkincil progres',
    'tertiary-progressed': 'Üçüncül progres',
    'solar-arc': 'Güneş yayı',
    'primary-directions': 'Primer',
    cyclo: 'CCG',
  },
  nubFallback: 'Katman',
  barToggle: {
    show: 'Zaman çizelgesini göster',
    hide: 'Zaman çizelgesini gizle',
    hint: 'Tarih kaydırıcısı + oynatma denetimleri. Tutamaç her iki durumda da kalır.',
  },
  drawer: {
    show: 'Görüntü anahtarlarını göster',
    hide: 'Görüntü anahtarlarını gizle',
  },
  cyclo: {
    label: 'Karışım',
    spName: 'Progres kişisel gezegenler',
    spTip: 'Sp — ikincil progres',
    spHint: 'Güneş, Ay, Merkür, Venüs ve Mars ikincil progres konumlarından okunur — bir günü bir yıla sayan hız onları dış cisimlerin yanında okunabilir kılar. Çizgileri Sp etiketini taşır.',
    trName: 'Transit dış cisimler',
    trTip: 'Tr — transit',
    trHint: 'Jüpiter ve ötesindeki her şey — ayrıca düğümler, Lilith, Chiron ve asteroitler — gerçek transit konumundan okunur. Çizgileri Tr etiketini taşır.',
  },
  positioning: {
    groupAria: 'Katman çerçevesi',
    lockedNoTime: 'Doğum saati bilinmiyor — tutulacak bir natal çerçeve yok, bu yüzden harita yalnızca anın gökyüzünü gösterebilir.',
    heldForReturn: 'Bu çerçeve, dünya haritası bir dönüşteyken beklemede — bir dönüş haritası ancak kendi çerçevesinde kendisidir. Bunu seçmek beklemeyi sonlandırır ve dünya haritasını bu çerçeveye geri döndürür.',
  },
  units: {
    minute: 'Dakika',
    hour: 'Saat',
    day: 'Gün',
    week: 'Hafta',
    month: 'Ay',
    year: 'Yıl',
  },
  unitsLower: {
    minute: 'dakika',
    hour: 'saat',
    day: 'gün',
    week: 'hafta',
    month: 'ay',
    year: 'yıl',
  },
  minorLabel: {
    minute: '1 dk',
    hour: '10 dk',
    day: '6 saat',
    week: '1 gün',
    month: '5 gün',
    year: '1 ay',
  },
  stepWords: {
    minute: '{n, plural, one {dakika} other {dakika}}',
    hour: '{n, plural, one {saat} other {saat}}',
    day: '{n, plural, one {gün} other {gün}}',
    week: '{n, plural, one {hafta} other {hafta}}',
    month: '{n, plural, one {ay} other {ay}}',
    year: '{n, plural, one {yıl} other {yıl}}',
  },
  stepSymbol: {
    minute: '{n, plural, one {dk} other {dk}}',
    hour: '{n, plural, one {sa} other {sa}}',
    day: '{n, plural, one {g} other {g}}',
    month: '{n, plural, one {ay} other {ay}}',
  },
  transport: {
    stepBack: '{count} {unit} geri',
    stepForward: '{count} {unit} ileri',
    stepBackAria: 'Geri adım',
    stepForwardAria: 'İleri adım',
    play: 'Oynat',
    pause: 'Duraklat',
    stepAmountIn: {
      minute: 'Adım miktarı (dakika)',
      hour: 'Adım miktarı (saat)',
      day: 'Adım miktarı (gün)',
      month: 'Adım miktarı (ay)',
    },
    stepAmountInAria: {
      minute: 'Adım miktarı (dakika)',
      hour: 'Adım miktarı (saat)',
      day: 'Adım miktarı (gün)',
      month: 'Adım miktarı (ay)',
    },
  },
  ruler: {
    aria: 'Tarihi ileri geri sar',
  },
  now: {
    label: 'Şimdi',
    tip: 'Zamanı şu ana ayarlayın',
  },
  returns: {
    label: 'Dönüşler',
    reframes: 'Dönüşün kendi anı için haritanın çerçevesini ödünç alır. Natal çerçevede dönen gök cismi doğum derecesine sabitlenir, bu yüzden çizgileri bir dönüşten ötekine hiç yer değiştirmezdi. Çerçeveniz silinmez, beklemede tutulur ve dönüşten çıktığınızda geri gelir.',
    chip: {
      solar: 'Güneş dönüşü',
      lunar: 'Ay dönüşü',
      tip: 'Harita bir dönüşte',
      hint: 'Dünya haritası bir dönüşteyken katman çerçevesi ödünç alınır, çünkü bir dönüş haritasının köşeleri kendisine aittir. Önceki çerçeve altta beklemede tutulur ve dönüşten çıkınca geri gelir. Oklarla dönüşler arasında geçmek beklemeyi korur.',
      clear: 'Dönüşten çık',
      clearHint: 'Katman çerçevesini önceki haline döndürür. Tarih olduğu gibi kalır.',
      clearAria: 'Dönüşten çık ve katman çerçevesini önceki haline döndür',
    },
    solar: {
      name: 'Güneş',
      chartName: 'Güneş dönüşü',
      snap: 'En yakın Güneş dönüşü',
      snapAria: 'En yakın Güneş dönüşüne atla',
      prev: 'Önceki Güneş dönüşü',
      prevAria: 'Önceki Güneş dönüşü',
      next: 'Sonraki Güneş dönüşü',
      nextAria: 'Sonraki Güneş dönüşü',
    },
    lunar: {
      name: 'Ay',
      chartName: 'Ay dönüşü',
      snap: 'En yakın Ay dönüşü',
      snapAria: 'En yakın Ay dönüşüne atla',
      prev: 'Önceki Ay dönüşü',
      prevAria: 'Önceki Ay dönüşü',
      next: 'Sonraki Ay dönüşü',
      nextAria: 'Sonraki Ay dönüşü',
    },
  },
  scale: {
    label: 'Ölçek',
  },
  rate: {
    label: 'Anahtar',
  },
  dateField: {
    tipChartZone: 'Transit / progres anı, haritanın saat diliminde',
    tipChartZonePlace: 'Transit / progres anı, {place} saatiyle — haritanın doğum yeri; bulunduğunuz yer olmayabilir',
    tipUtc: 'Transit / progres anı, UTC olarak',
  },
  datePicker: {
    open: 'Tarih ve saati düzenle',
    title: 'Tarih ve saati ayarla',
    scrollKey: 'Kaydır',
    scrollHint: 'artırmak ya da azaltmak için',
    apply: 'Ayarla',
    yearRange: 'Bu seçici {min} ile {max} arasını kapsar — bunun dışındaki bir yıl en yakın uca çekilir.',
  },
  labelFull: {
    transits: 'Transitler · {datetime} (UTC)',
    progressed: 'İkincil progres · yaş {years}',
    'tertiary-progressed': 'Üçüncül progres · yaş {years}',
    'solar-arc': 'Güneş yayı · {deg}°',
    'primary-directions': 'Primer direksiyonlar · {deg}°',
    cyclo: 'Siklo·karto·grafi · {datetime} (UTC)',
    synastry: 'Sinastri · {partner}',
    eclipses: 'Tutulma · {datetime} (UTC)',
  },
  measure: {
    progressedAge: 'Yaş {years}',
  },
} as const;
