// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/topNav.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const topNav = {
  overlay: {
    menuLabel: 'Katman',
    none: {
      label: 'Yok',
      hint: 'Yalnızca natal harita; herhangi bir zaman tekniği uygulanmaz.',
    },
    blocked: {
      composite: 'Kompozit bir an değil, bir orta nokta haritasıdır — bu tekniğin ilerletebileceği bir doğum anı yoktur. Kullanmak için tek kişilik bir haritaya geçin.',
      'no-time': 'Bu haritanın doğum saati bilinmiyor, bu yüzden ilerletilecek kesin bir natal an yok — buna dayanan bir teknik onu sessizce uydurmuş olurdu. Kullanmak için bir doğum saati ekleyin.',
      davison: 'Bu harita zaten iki kişilik bir harita, bu yüzden eklenecek kimse kalmadı. Sinastri kurmak için tek kişilik bir haritaya geçin.',
    },
    modes: {
      transits: {
        label: 'Transitler',
        desc: 'Gezegenlerin şu anki konumları, natal haritanızın üzerinde.',
      },
      progressed: {
        label: 'İkincil progres',
        tipTitle: 'İkincil progresyonlar',
        desc: 'İkincil progresyonlar: bir günün bir yıla karşılık geldiği sembolik bir açılım.',
      },
      'tertiary-progressed': {
        label: 'Üçüncül progres',
        tipTitle: 'Üçüncül progresyonlar',
        desc: 'Üçüncül progresyonlar: bir gün bir tropikal aya (27,32 gün) karşılık gelir; zamanlama için daha ince bir ibre.',
      },
      'solar-arc': {
        label: 'Güneş yayı',
        desc: 'Her nokta, Güneş’in yılda bir derecelik yayıyla ilerletilir.',
      },
      'primary-directions': {
        label: 'Primer direksiyonlar',
        desc: 'Gökyüzünün dönüşüyle işleyen antik bir zamanlama yöntemi.',
      },
      cyclo: {
        label: 'Siklokartografi',
        tipTitle: 'Siklokartografi (CCG)',
        desc: 'Jim Lewis’in melez yöntemi: ikincil progres kişisel gezegenler ile transit Jüpiter ve ötesi, tek bir haritada.',
      },
      synastry: {
        label: 'Sinastri',
        desc: 'İlişkiler için sizinkinin üzerine yerleştirilen başka bir kişinin haritası.',
      },
      eclipses: {
        label: 'Tutulmalar',
        desc: 'Harita genelinde Güneş tutulması yolları ve büyüklük eğrileri, ayrıca bir Ay tutulmasının görülebildiği yerler.',
      },
    },
  },
  status: {
    natal: 'NATAL',
    hover: 'İMLEÇ',
    pinned: 'SABİTLENMİŞ',
    'natal-pinned': 'NATAL RAPTİYE',
  },
  sidebarToggle: {
    showAria: 'Harita kenar çubuğunu göster',
    hideAria: 'Harita kenar çubuğunu gizle',
    showTip: 'Kenar çubuğu haritasını gösterin',
    hideTip: 'Kenar çubuğunu gizleyin',
  },
  pin: {
    centerTip: 'Haritayı raptiyeye ortalayın',
    pinNatalTip: 'Raptiyeyi natal konuma yerleştirin',
    controlsTip: 'Harita raptiyesi denetimleri',
  },
  tools: {
    menuLabel: 'Araçlar',
    measure: 'Mesafe ölç',
    measureItem: 'Ölçüm',
    measureHint: 'Büyük daire mesafesini ölçmek için haritada tıklayıp sürükleyin',
    toolbarHint: 'Ölçmek için haritada {click} ve {drag}{rightExit}',
    measureKm: '{n} km',
    measureMi: '{n} mil',
    snap: 'Yasla',
    snapTip: 'Uç noktayı harita çizgilerine yaslayın (ya da Shift tuşunu basılı tutun)',
    slideItem: 'Kaydırma',
    slideHint: 'Dünyayı sabit natal çizgilerin altında kaydırın — paranların gün boyunca nasıl oluştuğunu göstermek için zamanı ilerletir. Düz ya da küre görünümünde çalışır.',
    slideUnavailable: 'Kaydırma için natal çizgilerin çizili olması gerekir. Natal çizgiler anahtarı kapalıyken (Gelişmiş ▸ Çizgiler, Shift+N), Diğer çizgiler anahtarı onları temizlemişken ya da bir katman haritanın yerine geçmişken kullanılamaz.',
    slideToolbarHint: 'Dünyayı sabit çizgilerin altında kaydırmak için {pan}',
    slideNudgeBack1h: 'Bir saat geri',
    slideNudgeBack4m: 'Dört dakika geri (≈ 1° dönüş)',
    slideNudgeFwd4m: 'Dört dakika ileri (≈ 1° dönüş)',
    slideNudgeFwd1h: 'Bir saat ileri',
    slideReset: 'Natal gökyüzüne dön',
    slidePrevEvent: 'Etkin noktadaki önceki doğuşa, kulminasyona ya da batışa atla',
    slideNextEvent: 'Etkin noktadaki sonraki doğuşa, kulminasyona ya da batışa atla',
    slideElapsedTip: 'Harita anından bu yana kaydırılan süre',
    slideClockTip: 'Doğum yerindeki saat ve tarih, haritanın saat diliminde',
    slideAngleTip: 'Kutup çevresinde dönüş',
    captureItem: 'Görüntü Alma',
    captureHint: 'Haritayı çerçeveleyin ve PNG olarak dışa aktarın — bir en-boy oranı seçin, nelerin dahil edileceğini belirleyin, ardından indirin ya da kopyalayın.',
    captureToolbarHint: 'Çerçevenin içinde kadrajı ayarlamak için {pan} ve {zoom}{escExit}',
    hintKey: {
      click: 'Tıkla',
      tap: 'Dokun',
      doubleClick: 'Çift {icon} tıkla',
      doubleTap: 'Çift {icon} dokun',
      drag: 'Sürükle',
      pan: 'Kaydır',
      zoom: 'Yakınlaştır',
      esc: 'Esc',
      rightClick: 'Sağ {icon} tıkla',
      toExit: 'ile çıkın',
    },
  },
  view: {
    menuLabel: 'Görünüm',
    coordinates: 'Koordinatlar',
    coordinatesHint: 'Etkin noktanın yerini, koordinatlarını ve relokasyon haritası köşelerini gösteren canlı bir gösterge.',
    minimap: 'Mini harita',
    minimapHint: 'Dünya haritasını keşfederken köşede küçük tutulan natal harita çarkı.',
    settings: 'Ayarlar',
    settingsHint: 'Temalar, ev sistemleri, zodyak ve çark ile dünya haritasının nasıl çizildiği.',
    teleport: 'Işınlanma',
    teleportHint: 'Herhangi bir yeri arayın ve haritayı doğrudan oraya uçurun.',
    skyTimes: 'Gökyüzü Saatleri',
    skyTimesHint: 'Etkin noktadaki günlük doğuş, kulminasyon ve batış zamanları, alttaki kuşak boyunca.',
    localSpace: 'Yerel Uzay',
    localSpaceHint: 'Haritanın başlangıç noktasından her gezegene uzanan yön çizgileri — yerel uzay pusulanız.',
    info: 'Bilgi',
    infoHint: 'Haritanın etkin sistemlerini özetleyen köşedeki bir kutucuk — çizgi çerçevesi, evler ve zodyak.',
    guides: 'Rehberler',
    guidesHint: 'Tanıtım rehberlerine, haritanın denetimlerine dair bir sözlük olarak yeniden göz atın.',
  },
} as const;
