// AstroLina: web-based astrocartography for curious minds.
// Copyright (C) 2026 AstroLina <https://astrolina.org>
// SPDX-License-Identifier: AGPL-3.0-only
// Licensed under the GNU AGPL v3.0 with an additional attribution term under
// AGPL section 7(b). See the LICENSE and NOTICE files; this notice must be kept.

// GENERATED by the translation tooling (scripts/i18n/emit.mjs) — Türkçe for ../en/wheel.ts; the notes for every string are there.
// Values may be hand-edited (kept; see ../tr.lock.json). Keys, order and layout are rewritten on every run.
export const wheel = {
  house: '{number, selectordinal, other {#.}} ev',
  signMeanings: {
    aries: 'Ateş · Öncü · girişkenlik',
    taurus: 'Toprak · Sabit · istikrar',
    gemini: 'Hava · Değişken · merak',
    cancer: 'Su · Öncü · şefkat',
    leo: 'Ateş · Sabit · kendini ifade',
    virgo: 'Toprak · Değişken · titizlik',
    libra: 'Hava · Öncü · denge',
    scorpio: 'Su · Sabit · yoğunluk',
    sagittarius: 'Ateş · Değişken · macera',
    capricorn: 'Toprak · Öncü · hırs',
    aquarius: 'Hava · Sabit · yenilikçilik',
    pisces: 'Su · Değişken · hayal gücü',
  },
  houseMeanings: {
    h1: 'Benlik · kimlik · ilk izlenimler',
    h2: 'Para · mülkler · öz değer',
    h3: 'İletişim · kardeşler · öğrenme',
    h4: 'Ev · aile · kökler',
    h5: 'Yaratıcılık · romantizm · çocuklar',
    h6: 'İş · sağlık · günlük rutin',
    h7: 'Ortaklık · evlilik · “öteki”',
    h8: 'Yakınlık · ortak kaynaklar · yeniden doğuş',
    h9: 'Seyahat · felsefe · yüksek öğrenim',
    h10: 'Kariyer · itibar · kamusal yaşam',
    h11: 'Arkadaşlar · topluluk · umutlar',
    h12: 'Yalnızlık · görünmeyen · maneviyat',
  },
  tip: {
    longitude: 'Boylam {lon}',
    latitude: 'Enlem {lat}',
    minorCluster: '{n, plural, one {# küçük gök cismi} other {# küçük gök cismi}}',
    minorLine: '{name} {lon}',
    minorMore: '+{n} daha',
    overlayMinor: '{name} · {chart}',
    overlayMinorCluster: '{chart}: {n, plural, one {# küçük gök cismi} other {# küçük gök cismi}}',
    minorLineOverlay: '{name} {lon} · {chart}',
    fortuneGeodetic: 'Jeodezik Yükselenden',
    fortuneGeodeticDay: 'Jeodezik Yükselenden, gündüz doğumu olarak. Gece doğumunda Yükselene göre yansıtılırdı',
    fortuneGeodeticNight: 'Jeodezik Yükselenden, gece doğumu olarak. Gündüz doğumunda Yükselene göre yansıtılırdı',
    rangeNote: 'Doğum saati bilinmiyor: doğum tarihinde bu aralığın herhangi bir yerinde',
  },
  planetMeanings: {
    Sun: 'Kimlik · canlılık · ego',
    Moon: 'Duygular · içgüdü · ihtiyaçlar',
    Mercury: 'Zihin · iletişim',
    Venus: 'Aşk · güzellik · değerler',
    Mars: 'Dürtü · enerji · eylem',
    Jupiter: 'Büyüme · şans · genişleme',
    Saturn: 'Disiplin · yapı · sınırlar',
    Uranus: 'Değişim · özgürlük · içgörü',
    Neptune: 'Düşler · sezgi · ruh',
    Pluto: 'Güç · dönüşüm',
    NorthNode: 'Ruhun yolu · gelişim',
    SouthNode: 'Geçmiş · doğuştan yetiler',
    Lilith: 'Gölge · ham içgüdü',
    Chiron: 'Yaralı şifacı',
    Ceres: 'Şefkat · döngüler',
    Pallas: 'Bilgelik · strateji',
    Juno: 'Bağlılık · ortaklık',
    Vesta: 'Odak · adanmışlık',
    Fortune: 'Talih · canlılık · rahatlık',
  },
  angles: {
    As: {
      title: 'Yükselen',
      sub: 'Yükselen burç, benlik ve ilk izlenimler',
    },
    Ds: {
      title: 'Alçalan',
      sub: 'İlişkiler ve “öteki”',
    },
    Mc: {
      title: 'Tepe Noktası (Medium Coeli)',
      sub: 'Kariyer, itibar ve kamusal yaşam',
    },
    Ic: {
      title: 'Dip Noktası',
      sub: 'Ev, kökler ve özel yaşam',
    },
    Vx: {
      title: 'Vertex',
      sub: 'Kaderî karşılaşmalar ve dönüm noktaları; ilk düşey dairenin batı noktası',
    },
    Avx: {
      title: 'Anti-Vertex',
      sub: 'Vertex ekseninin doğu ucu, Vertex’in karşısında',
    },
  },
  motion: {
    retrograde: 'Retro',
    stationary: 'Durağan',
  },
} as const;
